import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,realpathSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {openStorage} from '../storage.js';
import {prepareConversationAction} from '../conversation-action-contract.js';
import {normalizeConversationProposal} from '../frontend/features/chat/conversation-actions.js';
import {normalizeMessages} from '../frontend/features/chat/logic.js';
import {conversationHandoff} from '../frontend/lib/conversation-handoff.js';
function fixture(t){const root=mkdtempSync(join(realpathSync(tmpdir()),'nestlet-reference-protocol-'));const store=openStorage({filename:join(root,'records.sqlite')});t.after(()=>{store.close();rmSync(root,{recursive:true,force:true});});const record=store.createCase('owner',{title:'Synthetic review',sourceText:'',fields:[],draftType:'followup',draftText:''}),conversation=store.createConversation('owner',record.id),message=store.appendMessage('owner',conversation.id,{role:'user',state:'complete',content:'Owner: Synthetic Owner',clientMessageId:randomUUID()});return{store,record,conversation,message};}
test('proposal and handoff carry friendly source references while UUID authority and request contract remain unchanged',t=>{const f=fixture(t),request={action:'prepare_case_suggestion',expectedVersion:f.record.version,sourceConversationId:f.conversation.id,sourceMessageId:f.message.id,factChanges:{owner:{value:'Synthetic Owner'}},changes:{}};const proposal=prepareConversationAction(request,f);assert.equal(proposal.sourceDisplayId,'XX00000001');assert.equal(proposal.conversationDisplayId,'DH00000001');assert.equal(proposal.sourceMessageId,f.message.id);assert.deepEqual(proposal.request,request);const normalized=normalizeConversationProposal({requestId:randomUUID(),proposal});assert.equal(normalized.proposal.sourceDisplayId,'XX00000001');assert.equal(normalized.proposal.apply.body.conversationAction.sourceMessageId,f.message.id);const [message]=normalizeMessages([f.message]);assert.equal(message.displayId,'XX00000001');const handoff=conversationHandoff(message,{userId:'owner',caseId:f.record.id,conversationId:f.conversation.id});assert.equal(handoff.messageDisplayId,'XX00000001');assert.equal(handoff.messageId,f.message.id);});
test('display metadata is typed and cannot change source kind or smuggle an alternate write identifier',t=>{const f=fixture(t),request={action:'prepare_case_suggestion',expectedVersion:f.record.version,sourceConversationId:f.conversation.id,sourceMessageId:f.message.id,factChanges:{owner:{value:'Synthetic Owner'}},changes:{}};const proposal=prepareConversationAction(request,f);assert.throws(()=>normalizeConversationProposal({requestId:randomUUID(),proposal:{...proposal,sourceDisplayId:'KF00000001'}}),{code:'CHAT_STREAM_FAILED'});assert.throws(()=>normalizeMessages([{...f.message,displayId:'XXbad'}]),{code:'INVALID_RESPONSE'});assert.throws(()=>prepareConversationAction({...request,sourceMessageId:'XX00000001'},f),{code:'CONVERSATION_ACTION_INVALID'});});
test('case source-reference display map never adds fields to canonical issue/authority objects',t=>{const f=fixture(t),issue={id:randomUUID(),question:'Synthetic question',status:'pending',resolution:'',sourceMessageId:f.message.id,updatedAt:new Date().toISOString()};const updated=f.store.updateCase('owner',f.record.id,{title:f.record.title,sourceText:'',fields:[],draftType:'followup',draftText:'',caseIssues:[issue]},f.record.version);assert.equal(updated.sourceDisplayIds[f.message.id],'XX00000001');assert.deepEqual(updated.caseIssues,[issue]);assert.equal(updated.id,f.record.id);});
