// Exact historical schema9 DDL; real SQLite and immutable synthetic asset bytes, no model calls.
import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,realpathSync,rmSync,mkdirSync,writeFileSync,readFileSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes,randomUUID,scryptSync,createHash} from 'node:crypto';
import {spawn} from 'node:child_process';
import {openStorage} from '../storage.js';
import {backupPrivateData,restorePrivateBackup,verifyPrivateBackup} from '../scripts/private-data-operations.js';
const inspect=(filename,fn)=>{const db=new DatabaseSync(filename);try{return fn(db);}finally{db.close();}};
const hashFile=file=>createHash('sha256').update(readFileSync(file)).digest('hex');
const snapshot=db=>{const tables=db.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all();return{rows:Object.fromEntries(tables.map(({name})=>[name,db.prepare(`SELECT * FROM ${name} ORDER BY rowid`).all()])),schema:db.prepare("SELECT name,type,sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY name").all()};};
function fixture(t){const root=mkdtempSync(join(realpathSync(tmpdir()),'nestlet-schema10-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const source=join(root,'source');mkdirSync(source,{mode:0o700});const filename=join(source,'db.sqlite'),assetsDirectory=join(source,'assets');mkdirSync(assetsDirectory,{mode:0o700});writeFileSync(filename,'',{mode:0o600});const id=randomUUID(),client=randomUUID(),record=randomUUID(),conversation=randomUUID(),message=randomUUID(),artifact=randomUUID(),at='2026-10-08T00:00:00.000Z',salt=randomBytes(16),hash=`scrypt$${salt.toString('base64url')}$${scryptSync('synthetic-migration-password',salt,32).toString('base64url')}`;inspect(filename,db=>{db.exec(readFileSync(new URL('./fixtures/schema9.sql',import.meta.url),'utf8'));db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run('owner','owner','owner',null,at);db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(id,'synthetic-existing','trial',hash,at);db.prepare('INSERT INTO clients VALUES(?,?,?,?,?,?)').run(client,id,'Synthetic customer',2,at,at);db.prepare('INSERT INTO cases VALUES(?,?,?,?,?,?,?,?)').run(record,id,'Synthetic case',JSON.stringify({title:'Synthetic case',sourceText:'Synthetic retained',fields:[],draftType:'followup',draftText:''}),3,at,at,client);db.prepare('INSERT INTO conversations VALUES(?,?,?,?,?,?)').run(conversation,id,record,'Synthetic old conversation',at,at);db.prepare('INSERT INTO messages VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(message,id,conversation,1,'user','Synthetic prior message','complete',null,randomUUID(),'[]',at);db.prepare('INSERT INTO artifacts VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(artifact,id,record,'followup','Synthetic draft','draft','Synthetic content',1,3,conversation,message,'{}',at);db.prepare('INSERT INTO email_identities VALUES(?,?,?)').run(id,'synthetic-existing@example.invalid',Date.parse(at));db.prepare('INSERT INTO email_rate_buckets VALUES(?,?,?)').run('a'.repeat(64),2,Date.now()+3600000);});return{root,source,filename,assetsDirectory,id,client,record,conversation,message,artifact};}
test('genuine schema9→10 is additive and assigns stable scoped display IDs without changing old rows or credentials',t=>{const f=fixture(t),before=inspect(f.filename,snapshot);let store=openStorage({filename:f.filename});const ids={client:store.getClient(f.id,f.client).displayId,case:store.getCase(f.id,f.record).displayId,conversation:store.getConversation(f.id,f.conversation).displayId,message:store.listMessages(f.id,f.conversation)[0].displayId,artifact:store.getArtifact(f.id,f.artifact).displayId};assert.deepEqual(ids,{client:'KF00000001',case:'SX00000001',conversation:'DH00000001',message:'XX00000001',artifact:'WS00000001'});assert.equal(store.serviceEntitlements.read(f.id).mode,'default');assert.equal(store.getCase(f.id,f.record).id,f.record);assert.equal(store.getCase('owner',f.record),null);assert.equal(store.recordDisplayId('owner','case',f.record),null);store.close();inspect(f.filename,db=>{assert.equal(db.prepare('PRAGMA user_version').get().user_version,10);for(const[name,rows]of Object.entries(before.rows))assert.deepEqual(db.prepare(`SELECT * FROM ${name} ORDER BY rowid`).all(),rows,name);for(const old of before.schema)assert.deepEqual(db.prepare('SELECT name,type,sql FROM sqlite_master WHERE name=?').get(old.name),old);assert.deepEqual(db.prepare('PRAGMA foreign_key_check').all(),[]);});store=openStorage({filename:f.filename});assert.equal(store.getClient(f.id,f.client).displayId,ids.client);store.close();});
test('display references survive rename/delete/reopen and account/type counters do not mix or recycle',t=>{const f=fixture(t);let store=openStorage({filename:f.filename});const first=store.createCase(f.id,{title:'Second',sourceText:'',fields:[],draftType:'followup',draftText:''});assert.equal(first.displayId,'SX00000002');store.deleteCase(f.id,first.id,first.version);const third=store.createCase(f.id,{title:'Third',sourceText:'',fields:[],draftType:'followup',draftText:''});assert.equal(third.displayId,'SX00000003');assert.equal(store.createClient('owner',{displayName:'Another account'}).displayId,'KF00000001');assert.equal(store.updateClient(f.id,f.client,{displayName:'Renamed'},2).displayId,'KF00000001');store.close();store=openStorage({filename:f.filename});assert.equal(store.getCase(f.id,third.id).displayId,'SX00000003');store.close();});
test('display counter overflow rolls back the new record rather than collide or reuse',t=>{const f=fixture(t),store=openStorage({filename:f.filename});inspect(f.filename,db=>db.prepare("UPDATE record_display_counters SET last_number=99999999 WHERE owner_user_id=? AND kind='case'").run(f.id));assert.throws(()=>store.createCase(f.id,{title:'Overflow',sourceText:'',fields:[],draftType:'followup',draftText:''}));assert.equal(store.listCases(f.id).length,1);store.close();});
test('schema10 migration failure rolls back all additions and keeps genuine schema9 unchanged',t=>{const f=fixture(t);inspect(f.filename,db=>db.exec('CREATE TABLE service_usage(existing TEXT) STRICT;'));const before=inspect(f.filename,snapshot);assert.throws(()=>openStorage({filename:f.filename}));inspect(f.filename,db=>{assert.equal(db.prepare('PRAGMA user_version').get().user_version,9);assert.deepEqual(snapshot(db),before);});});
test('schema10 backup/restore preserves IDs/usage/data but pauses all ordinary services with recovery audit and no source mutation',async t=>{const f=fixture(t),store=openStorage({filename:f.filename});const owner={userId:'owner',role:'owner'},state=store.serviceEntitlements.read(f.id);store.serviceEntitlements.set(owner,f.id,{enabled:true,expiresAt:null,requestsPerHour:15,expectedVersion:state.version});store.serviceEntitlements.consume({userId:f.id,role:'trial'},randomUUID());const other=store.createTrialUser({username:'synthetic-default-service',passwordHash:store.getUserById(f.id).passwordHash});const display=store.getCase(f.id,f.record).displayId;store.close();const original=hashFile(f.filename),backup=join(f.root,'backup');assert.equal((await backupPrivateData({...f,output:backup})).schemaVersion,10);const snap=hashFile(join(backup,'nestlet.sqlite'));const restored=await restorePrivateBackup({input:backup,output:join(f.root,'restored')});const recovered=openStorage({filename:restored.filename});try{assert.equal(recovered.getCase(f.id,f.record).displayId,display);assert.equal(recovered.serviceEntitlements.read(f.id).status,'paused');assert.equal(recovered.serviceEntitlements.read(f.id).used,1);assert.equal(recovered.serviceEntitlements.read(other.id).status,'paused');assert.equal(recovered.serviceEntitlements.read('owner').status,'available');assert.ok(recovered.serviceEntitlements.audit(owner).events.some(row=>row.source==='recovery'));assert.equal(recovered.getCase(f.id,f.record).sourceText,'Synthetic retained');}finally{recovered.close();}assert.equal(hashFile(f.filename),original);assert.equal(hashFile(join(backup,'nestlet.sqlite')),snap);assert.equal(verifyPrivateBackup({input:backup}).schemaVersion,10);});
test('future schema11 refuses before data changes and old schema9 snapshots remain recoverable',async t=>{const f=fixture(t),pre=join(f.root,'pre');await backupPrivateData({...f,output:pre});const restored=await restorePrivateBackup({input:pre,output:join(f.root,'schema9-recovery')});assert.equal(restored.schemaVersion,9);inspect(f.filename,db=>db.exec('PRAGMA user_version=11'));const hash=hashFile(f.filename);assert.throws(()=>openStorage({filename:f.filename}),{code:'STORAGE_VERSION_UNSUPPORTED'});assert.equal(hashFile(f.filename),hash);await assert.rejects(backupPrivateData({...f,output:join(f.root,'bad')}));assert.equal(hashFile(f.filename),hash);});


test('concurrent real processes allocate distinct account-scoped references in their insert transactions',async t=>{
 const f=fixture(t);openStorage({filename:f.filename}).close();
 const run=index=>new Promise((resolve,reject)=>{
  const script=`import {openStorage} from ${JSON.stringify(new URL('../storage.js',import.meta.url).href)};const s=openStorage({filename:${JSON.stringify(f.filename)}});try{console.log(s.createClient(${JSON.stringify(f.id)},{displayName:'Synthetic concurrent '+${index}}).displayId);}finally{s.close();}`;
  const child=spawn(process.execPath,['--input-type=module','-e',script],{stdio:['ignore','pipe','pipe']});let output='',errors='';child.stdout.on('data',part=>output+=part);child.stderr.on('data',part=>errors+=part);child.once('exit',code=>code===0?resolve(output.trim()):reject(Error(errors)));
 });
 const ids=await Promise.all(Array.from({length:5},(_,index)=>run(index)));
 assert.equal(new Set(ids).size,5);assert.deepEqual(ids.sort(),['KF00000002','KF00000003','KF00000004','KF00000005','KF00000006']);
 const store=openStorage({filename:f.filename});assert.equal(store.getClient(f.id,f.client).displayId,'KF00000001');assert.equal(store.listClients(f.id).length,6);store.close();
});


test('schema9 restore fence pauses ordinary services atomically on first schema10 startup, unlike normal migration',async t=>{
 const f=fixture(t),backup=join(f.root,'schema9-backup');await backupPrivateData({...f,output:backup});const snapshotHash=hashFile(join(backup,'nestlet.sqlite'));
 const restored=await restorePrivateBackup({input:backup,output:join(f.root,'legacy-restored')});const marker=restored.filename+'.service-reconfirm.json';assert.equal(restored.schemaVersion,9);assert.equal(restored.serviceRecovery,'schema10-startup-fence');assert.equal(restored.preserveRestoreDirectory,true);assert.ok(existsSync(marker));
 const beforeFence=readFileSync(marker);let store=openStorage({filename:restored.filename});assert.equal(store.serviceEntitlements.read(f.id).status,'paused');assert.equal(store.getCase(f.id,f.record).sourceText,'Synthetic retained');assert.equal(store.serviceEntitlements.audit({userId:'owner',role:'owner'}).events.filter(row=>row.source==='recovery').length,1);store.close();assert.equal(existsSync(marker),false);
 // Simulate committed DB plus a leftover fence after the operator has verified
 // and released any stale startup lock. This is receipt idempotency, not
 // automatic recovery from a real process crash that also leaves its lock.
 store=openStorage({filename:restored.filename});const old=store.serviceEntitlements.read(f.id);store.serviceEntitlements.set({userId:'owner',role:'owner'},f.id,{enabled:true,expiresAt:null,requestsPerHour:10,expectedVersion:old.version});store.close();writeFileSync(marker,beforeFence,{mode:0o600,flag:'wx'});
 store=openStorage({filename:restored.filename});assert.equal(store.serviceEntitlements.read(f.id).status,'available');assert.equal(store.serviceEntitlements.audit({userId:'owner',role:'owner'}).events.filter(row=>row.source==='recovery').length,1);store.close();assert.equal(existsSync(marker),false);assert.equal(hashFile(join(backup,'nestlet.sqlite')),snapshotHash);
 const ordinary=openStorage({filename:f.filename});assert.equal(ordinary.serviceEntitlements.read(f.id).status,'available');ordinary.close();
});
test('malformed or wrong-database recovery fences reject before schema/data mutation',async t=>{
 const f=fixture(t),backup=join(f.root,'backup');await backupPrivateData({...f,output:backup});const restored=await restorePrivateBackup({input:backup,output:join(f.root,'bad-fence')});const marker=restored.filename+'.service-reconfirm.json',original=readFileSync(marker),before=hashFile(restored.filename);
 writeFileSync(marker,'not-json');assert.throws(()=>openStorage({filename:restored.filename}),{code:'SERVICE_RECOVERY_INVALID'});assert.equal(hashFile(restored.filename),before);
 const parsed=JSON.parse(original);parsed.databaseSha256='f'.repeat(64);writeFileSync(marker,JSON.stringify(parsed));assert.throws(()=>openStorage({filename:restored.filename}),{code:'SERVICE_RECOVERY_INVALID'});assert.equal(hashFile(restored.filename),before);assert.equal(inspect(restored.filename,db=>db.prepare('PRAGMA user_version').get().user_version),9);
});
test('concurrent schema10 startups consume one legacy recovery fence and do not duplicate recovery grants/audits',async t=>{
 const f=fixture(t),backup=join(f.root,'backup');await backupPrivateData({...f,output:backup});const restored=await restorePrivateBackup({input:backup,output:join(f.root,'concurrent-recovery')});
 const run=()=>new Promise((resolve,reject)=>{const source=`import {openStorage} from ${JSON.stringify(new URL('../storage.js',import.meta.url).href)};const s=openStorage({filename:${JSON.stringify(restored.filename)}});s.close();`;const child=spawn(process.execPath,['--input-type=module','-e',source],{stdio:['ignore','pipe','pipe']});let errors='';child.stderr.on('data',part=>errors+=part);child.once('exit',code=>code===0?resolve():reject(Error(errors)));});
 await Promise.all([run(),run(),run()]);const store=openStorage({filename:restored.filename});assert.equal(store.serviceEntitlements.read(f.id).status,'paused');assert.equal(store.serviceEntitlements.read(f.id).version,1);assert.equal(store.serviceEntitlements.audit({userId:'owner',role:'owner'}).events.length,1);store.close();assert.equal(existsSync(restored.filename+'.service-reconfirm.json'),false);
});

test('historical schema4 restored copy keeps old compatibility until fenced schema10 startup pauses service',async t=>{
 const f=fixture(t);rmSync(f.filename);writeFileSync(f.filename,'',{mode:0o600});inspect(f.filename,db=>{const sql=readFileSync(new URL('./fixtures/schema5.sql',import.meta.url),'utf8');db.exec(sql.slice(0,sql.indexOf('CREATE TABLE email_identities')));const at=new Date().toISOString(),salt=randomBytes(16),hash=`scrypt$${salt.toString('base64url')}$${scryptSync('synthetic-legacy-four',salt,32).toString('base64url')}`;db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run('owner','owner','owner',null,at);db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(f.id,'synthetic-legacy-four','trial',hash,at);});
 const snapshot=join(f.root,'schema4');await backupPrivateData({...f,output:snapshot});const before=hashFile(join(snapshot,'nestlet.sqlite'));const restored=await restorePrivateBackup({input:snapshot,output:join(f.root,'restored-four')});assert.equal(restored.schemaVersion,4);assert.equal(inspect(restored.filename,db=>db.prepare('PRAGMA user_version').get().user_version),4);const store=openStorage({filename:restored.filename});assert.equal(store.serviceEntitlements.read(f.id).status,'paused');store.close();assert.equal(hashFile(join(snapshot,'nestlet.sqlite')),before);
});
test('legacy recovery with a WAL/journal sidecar refuses before any SQLite open or automatic repair',async t=>{
 const f=fixture(t),snapshot=join(f.root,'snapshot');await backupPrivateData({...f,output:snapshot});const restored=await restorePrivateBackup({input:snapshot,output:join(f.root,'unsafe-sidecar')});const before=hashFile(restored.filename),sidecar=restored.filename+'-journal';writeFileSync(sidecar,'Synthetic incomplete recovery',{mode:0o600});assert.throws(()=>openStorage({filename:restored.filename}),{code:'SERVICE_RECOVERY_INVALID'});assert.equal(hashFile(restored.filename),before);assert.equal(readFileSync(sidecar,'utf8'),'Synthetic incomplete recovery');
});

test('a stale restore-startup lock fails closed without deleting the lock, marker or changing the database',async t=>{
 const f=fixture(t),snapshot=join(f.root,'snapshot');await backupPrivateData({...f,output:snapshot});const restored=await restorePrivateBackup({input:snapshot,output:join(f.root,'stale-lock')});const lock=restored.filename+'.service-reconfirm.lock',marker=restored.filename+'.service-reconfirm.json';writeFileSync(lock,'Synthetic stale lock retained for operator review',{mode:0o600,flag:'wx'});const dbBefore=hashFile(restored.filename),markerBefore=readFileSync(marker);assert.throws(()=>openStorage({filename:restored.filename}),{code:'SERVICE_RECOVERY_INVALID'});assert.equal(hashFile(restored.filename),dbBefore);assert.deepEqual(readFileSync(marker),markerBefore);assert.equal(readFileSync(lock,'utf8'),'Synthetic stale lock retained for operator review');assert.equal(inspect(restored.filename,db=>db.prepare('PRAGMA user_version').get().user_version),9);
});

test('an INCOMPLETE recovery directory cannot be started even before a reconfirmation fence was written',t=>{
 const f=fixture(t),before=hashFile(f.filename),marker=join(f.source,'INCOMPLETE');writeFileSync(marker,'Synthetic unfinished restore',{mode:0o600});assert.throws(()=>openStorage({filename:f.filename}),{code:'SERVICE_RECOVERY_INVALID'});assert.equal(hashFile(f.filename),before);assert.equal(readFileSync(marker,'utf8'),'Synthetic unfinished restore');assert.equal(inspect(f.filename,db=>db.prepare('PRAGMA user_version').get().user_version),9);
});
