export const chatCopy = {
  zh: {
    title:'围绕一个案例，继续处理', subtitle:'已确认的案例资料会作为上下文使用。聊天输入不会覆盖材料、核对结果或文书。',
    conversation:'会话', newConversation:'新会话', untitledConversation:'案例会话', untitledCase:'未命名案例',
    loading:'正在读取已保存会话…', empty:'从一个问题开始。首次发送会先建立案例和会话，后续可以回来继续。',
    composer:'这次想处理什么？', placeholder:'输入问题，或粘贴 PNG / JPEG 图片…', send:'发送给 DeepSeek', stop:'停止回复',
    sending:'正在等待真实模型回复…', saving:'正在保存案例与会话…', decoding:'正在检查图片…',
    attach:'添加图片或文档', remove:'移除图片', you:'你', assistant:'助手', incomplete:'回复未完成；不能把它当作已完成的文书。',
    localOnly:'这段内容暂只保留在当前页面，尚未确认已保存。', oldImage:'原图片未保留；需要重新查看时请再次添加。',
    consent:'我有权将本会话的去标识文字、所附图片及已保存案例上下文在点击发送后交给 DeepSeek。',
    privacy:'请勿发送 SSN、银行、税务或身份证件信息。图片最多 2 张，每张 2 MiB、边长不超过 8192 像素，仅 PNG / JPEG。图片本体不留存。',
    openingDocuments:'文档已交给材料与事实页面处理；聊天内容没有覆盖案例材料。',
    documents:'PDF、CSV、XLS 和 XLSX 请到「文书」页面导入并核对；这里不会把文件内容冒充图片发送。',
    signIn:'请先登录，再打开自己的案例会话。', unavailable:'真实模型连接尚未启用，请联系管理员检查设置。资料不会被假回复替代。',
    retry:'重新编辑这次问题', retryNote:'问题已放回输入框。检查后再次点击发送，会发起一次新的模型请求。',
    reload:'重新读取会话', copy:'复制回复', copied:'已复制回复', copyFailed:'复制失败，请手动选择文字复制。',
    resetAsk:'切换会话会停止当前回复，并清除尚未发送的文字和图片。已保存消息不会删除。继续？',
    stopped:'已停止。已收到的部分回复会保留为未完成；可重新读取确认保存状态。',
    saved:'消息保存在当前案例中', refreshFailed:'保存状态暂时无法读取。当前文字仍在页面上，请不要关闭页面，稍后重新读取。',
    restored:'已从服务器恢复会话', unsupportedFile:'此处仅接受 PNG / JPEG 图片。文档请在「文书」页面导入。',
    emptyError:'请先输入问题或添加图片。', tooLarge:'输入或图片超过限制，请缩短文字或减少图片。', imageError:'图片无法读取或超过 PNG / JPEG 限制，请换一张图片。',
    authError:'登录已失效，请重新登录。当前请求不会自动重发。', storageError:'案例或会话未能保存。问题仍保留，请检查后重试。',
    conflict:'案例已在别处更新，请重新打开最新案例后继续。', notFound:'当前案例或会话不存在，或不属于此账号。',
    busy:'已有请求在处理中，请稍后再试。', quota:'本时段使用次数已达上限，请稍后再试。',
    sensitive:'检测到可能的敏感标识，请删除或去标识后再发送。', streamError:'回复中断或未完整结束。已收到的内容仍保留为未完成。',
    saveError:'回复未能确认保存。不要把它当成已保存结果，请保留当前文字并重新读取会话。',
    duplicate:'这次问题已提交过。请重新读取会话；如需再问，使用一次新的明确发送。',
    capacity:'保存空间或条数已达上限，未发起新的模型请求。', network:'网络请求失败，请检查连接。不会自动重复收费请求。',
    generic:'操作未完成，请稍后重试。', attachmentCount:'张图片', pending:'尚未发送', imageOnly:'附图问题'
  },
  en: {
    title:'Continue working on one case', subtitle:'Confirmed case details are reused as context. Chat input never replaces source material, reviewed facts, or documents.',
    conversation:'Conversation', newConversation:'New conversation', untitledConversation:'Case conversation', untitledCase:'Untitled case',
    loading:'Loading saved conversation…', empty:'Start with a question. The first send creates a case and conversation so you can return later.',
    composer:'What would you like to work on?', placeholder:'Enter a question, or paste a PNG / JPEG image…', send:'Send to DeepSeek', stop:'Stop reply',
    sending:'Waiting for the real model response…', saving:'Saving the case and conversation…', decoding:'Checking images…',
    attach:'Add images or documents', remove:'Remove image', you:'You', assistant:'Assistant', incomplete:'This reply is incomplete and must not be treated as a completed document.',
    localOnly:'This text is currently retained only on this page; its saved state is not yet confirmed.', oldImage:'The original image was not retained. Attach it again if it needs to be inspected.',
    consent:'I am authorized to send this conversation’s de-identified text, attached images, and saved case context to DeepSeek when I click Send.',
    privacy:'Do not send SSNs, banking, tax, or identity-document information. Up to 2 PNG / JPEG images, 2 MiB each, with sides no larger than 8192 pixels. Image bytes are not retained.',
    openingDocuments:'Documents were handed to Materials and Facts. Chat did not replace the case source.',
    documents:'Import and review PDF, CSV, XLS, and XLSX files on the Documents page. Files are never disguised as images here.',
    signIn:'Sign in before opening your case conversations.', unavailable:'The real model connection is not enabled. Ask the administrator to check settings. No fabricated response will replace it.',
    retry:'Edit this question again', retryNote:'The question is back in the composer. Review it and click Send to start a new model request.',
    reload:'Reload conversation', copy:'Copy reply', copied:'Reply copied', copyFailed:'Copy failed. Select and copy the text manually.',
    resetAsk:'Switching conversations stops the current reply and clears unsent text and images. Saved messages will not be deleted. Continue?',
    stopped:'Stopped. Received text remains incomplete; reload to confirm its saved state.',
    saved:'Messages are saved with this case', refreshFailed:'Saved state could not be loaded. Current text remains on this page; keep it open and reload later.',
    restored:'Conversation restored from the server', unsupportedFile:'Only PNG / JPEG images are accepted here. Import documents on the Documents page.',
    emptyError:'Enter a question or attach an image first.', tooLarge:'The text or images exceed a limit. Shorten the text or remove images.', imageError:'The image cannot be read or exceeds PNG / JPEG limits. Choose another image.',
    authError:'Your session expired. Sign in again. This request will not be resent automatically.', storageError:'The case or conversation could not be saved. Your question remains available to retry.',
    conflict:'The case was updated elsewhere. Reopen its latest version before continuing.', notFound:'This case or conversation does not exist or does not belong to this account.',
    busy:'Another request is processing. Try again shortly.', quota:'The usage limit for this period has been reached. Try again later.',
    sensitive:'Possible sensitive identifiers were detected. Remove or de-identify them before sending.', streamError:'The reply was interrupted or did not finish. Received text remains marked incomplete.',
    saveError:'The reply could not be confirmed as saved. Keep the current text and reload the conversation before treating it as retained.',
    duplicate:'This question was already submitted. Reload the conversation; a new send must be an explicit action.',
    capacity:'The storage or record limit was reached; no new model request was started.', network:'The network request failed. Check your connection. Paid requests are never retried automatically.',
    generic:'The action could not be completed. Try again later.', attachmentCount:'images', pending:'Unsent', imageOnly:'Question with images'
  }
};
const errorKeys = {
  CHAT_EMPTY:'emptyError', CHAT_TOO_LARGE:'tooLarge', INPUT_TOO_LARGE:'tooLarge', CHAT_IMAGE_INVALID:'imageError', CHAT_IMAGE_UNSUPPORTED:'imageError',
  AUTH_REQUIRED:'authError', CSRF_REJECTED:'authError', OPERATOR_SETUP_REQUIRED:'authError', HTTPS_REQUIRED:'authError', ORIGIN_REJECTED:'authError',
  LIVE_DISABLED:'unavailable', API_KEY_REQUIRED:'unavailable', CASE_INVALID:'storageError', CONVERSATION_INVALID:'storageError', INVALID_RESPONSE:'storageError',
  CASE_CONFLICT:'conflict', CASE_NOT_FOUND:'notFound', CONVERSATION_NOT_FOUND:'notFound', BUSY:'busy', CHAT_CONVERSATION_BUSY:'busy',
  TRIAL_LIMIT_REACHED:'quota', SENSITIVE_DATA:'sensitive', CHAT_PROVIDER_FAILED:'streamError', CHAT_STREAM_FAILED:'streamError', CHAT_INCOMPLETE:'streamError', CHAT_UNSUPPORTED_OUTPUT:'streamError',
  CHAT_SAVE_FAILED:'saveError', CHAT_TURN_EXISTS:'duplicate', CAPACITY_REACHED:'capacity', CASE_LIMIT_REACHED:'capacity', NETWORK_ERROR:'network'
};
export function chatErrorText(error, lang='zh') { const words=chatCopy[lang] || chatCopy.zh; return words[errorKeys[error?.code] || 'generic']; }
