export const chatCopy = {
  zh: {
    title:'围绕一个案例，继续处理', subtitle:'已确认的案例资料会作为上下文使用。聊天输入不会覆盖材料、核对结果或文书。',
    conversation:'已有会话', newConversation:'+ 新建', chooseConversation:'选择已有会话', noConversations:'暂无已保存会话', noConversationsReason:'首次发送消息时会建立并保存会话。', untitledConversation:'案例会话', untitledCase:'未命名案例',
    loading:'正在读取已保存会话…', empty:'从一个问题开始。首次发送会先建立案例和会话，后续可以回来继续。',
    composer:'这次想处理什么？', placeholder:'输入问题，或粘贴 PNG / JPEG 图片…', send:'发送给 DeepSeek', stop:'停止回复',
    sending:'正在等待真实模型回复…', saving:'正在保存案例与会话…', decoding:'正在检查图片…', imageBusy:'上一批图片仍在检查，请完成后再添加。',
    attach:'添加图片或文档', remove:'移除图片', you:'你', assistant:'助手', incomplete:'回复未完成；不能把它当作已完成的文书。',
    localOnly:'这段内容暂只保留在当前页面，尚未确认已保存。', oldImage:'原图片未保留；需要重新查看时请再次添加。',
    consent:'我有权将本会话的去标识文字、所附图片及已保存案例上下文在点击发送后交给 DeepSeek。',
    libraryConsent:'仅本次发送：允许 AI 检索我保存的资料库，并将相关记录摘录发送给 DeepSeek。',
    libraryUnavailable:'当前服务器不支持资料库检索；普通聊天仍可使用。检索不会静默降级。',
    libraryBoundary:'可检索本人保存的客户、案例、文件和文书。检索不代表完整审阅；只读取，不会修改资料或自动提交。',
    libraryActivity:'本次资料检索', librarySources:'本次引用来源', librarySourcesNote:'下列状态区分仅找到记录、读取摘录和正文不可读。完整引用随回复保存；不是完整资料库审查。',
    librarySearchingStarted:'已开始搜索保存的记录', librarySearchingCompleted:'记录搜索已结束', librarySearchingError:'记录搜索未完成',
    libraryReadingStarted:'已开始读取相关摘录', libraryReadingCompleted:'摘录读取已结束', libraryReadingError:'摘录读取未完成',
    libraryRetrievingStarted:'已开始资料检索', libraryRetrievingCompleted:'资料检索已结束', libraryRetrievingError:'资料检索未完成',
    libraryCount:'记录数', libraryMetadata:'仅记录信息，未读取正文', libraryRead:'已读取部分摘录', libraryUnreadable:'正文不可读',
    libraryClient:'客户', libraryCase:'案例', libraryAsset:'文件', libraryArtifact:'文书', libraryVersion:'版本', libraryStale:'历史版本，需重新核对', libraryDraft:'草稿', libraryFinal:'终稿', libraryTitleTruncated:'标题已截短', libraryExcerptTruncated:'仅读取了受限摘录',
    libraryConsentError:'本次检索需要明确授权，请重新选择后发送。', libraryRequestError:'资料检索请求未能完成，不能据此声称已检查资料。',
    librarySensitive:'相关记录可能含敏感标识，检索已阻止；请先检查并去标识。', libraryMissing:'相关记录不可用或不属于此账号。',
    libraryLimit:'本次检索已到达读取限制；结果可能不完整。', libraryStopped:'资料检索已停止或超时；已收到内容仍需核对。',
    libraryCitation:'模型给出了未核实的来源引用，不能把本次结果当作已核实结论。',
    privacy:'请勿发送 SSN、银行、税务或身份证件信息。图片最多 2 张，每张 2 MiB、边长不超过 8192 像素，仅 PNG / JPEG。图片本体不留存。',
    openingDocuments:'文档已交给材料与事实页面处理；聊天内容没有覆盖案例材料。',
    documents:'PDF、CSV、XLS 和 XLSX 请到「文书」页面导入并核对；这里不会把文件内容冒充图片发送。',
    signIn:'请先登录，再打开自己的案例会话。', unavailable:'真实模型连接尚未启用，请联系管理员检查设置。资料不会被假回复替代。',
    retry:'重新编辑这次问题', retryNote:'问题已放回输入框。检查后再次点击发送，会发起一次新的模型请求。',
    reload:'重新读取会话', copy:'复制回复', copied:'已复制回复', copyFailed:'复制失败，请手动选择文字复制。',
    resetAsk:'切换会话会停止当前回复，并清除尚未发送的文字和图片。已保存消息不会删除。继续？',
    stopped:'已停止。已收到的部分回复会保留为未完成；可重新读取确认保存状态。',
    saved:'消息保存在当前案例中', refreshFailed:'保存状态暂时无法读取。当前文字仍在页面上，请不要关闭页面，稍后重新读取。',
    restored:'已从服务器恢复会话', draftRestored:'已恢复当前标签页中的未发送文字。图片请重新添加；重发前先查看已保存会话。', cacheUnavailable:'这段输入无法加入临时恢复缓存，请保持页面打开或手动复制。', unsupportedFile:'此处仅接受 PNG / JPEG 图片。文档请在「文书」页面导入。',
    emptyError:'请先输入问题或添加图片。', tooLarge:'输入或图片超过限制，请缩短文字或减少图片。', imageError:'图片无法读取或超过 PNG / JPEG 限制，请换一张图片。',
    authError:'登录已失效，请重新登录。当前请求不会自动重发。', storageError:'案例或会话未能保存。问题仍保留，请检查后重试。',
    conflict:'案例已在别处更新，请重新打开最新案例后继续。', notFound:'当前案例或会话不存在，或不属于此账号。',
    busy:'已有请求在处理中，请稍后再试。', quota:'本时段使用次数已达上限，请稍后再试。',
    sensitive:'检测到可能的敏感标识，请删除或去标识后再发送。', streamError:'回复中断或未完整结束。已收到的内容仍保留为未完成。',
    saveError:'回复未能确认保存。不要把它当成已保存结果，请保留当前文字并重新读取会话。',
    duplicate:'这次问题已提交过。请重新读取会话；如需再问，使用一次新的明确发送。',
    capacity:'保存空间或条数已达上限，未发起新的模型请求。', network:'网络请求失败，请检查连接。不会自动重复收费请求。',
    generic:'操作未完成，请稍后重试。', attachmentCount:'张图片', pending:'尚未发送', imageOnly:'附图问题'
  },
  en: {
    title:'Continue working on one case', subtitle:'Confirmed case details are reused as context. Chat input never replaces source material, reviewed facts, or documents.',
    conversation:'Saved conversations', newConversation:'+ New', chooseConversation:'Choose a saved conversation', noConversations:'No saved conversations', noConversationsReason:'Your first send creates and saves a conversation.', untitledConversation:'Case conversation', untitledCase:'Untitled case',
    loading:'Loading saved conversation…', empty:'Start with a question. The first send creates a case and conversation so you can return later.',
    composer:'What would you like to work on?', placeholder:'Enter a question, or paste a PNG / JPEG image…', send:'Send to DeepSeek', stop:'Stop reply',
    sending:'Waiting for the real model response…', saving:'Saving the case and conversation…', decoding:'Checking images…', imageBusy:'The previous images are still being checked. Add more after processing finishes.',
    attach:'Add images or documents', remove:'Remove image', you:'You', assistant:'Assistant', incomplete:'This reply is incomplete and must not be treated as a completed document.',
    localOnly:'This text is currently retained only on this page; its saved state is not yet confirmed.', oldImage:'The original image was not retained. Attach it again if it needs to be inspected.',
    consent:'I am authorized to send this conversation’s de-identified text, attached images, and saved case context to DeepSeek when I click Send.',
    libraryConsent:'For this send only: allow AI to search my saved library and send relevant record excerpts to DeepSeek.',
    libraryUnavailable:'This server does not support library retrieval. Ordinary chat remains available; retrieval will not silently fall back.',
    libraryBoundary:'Searches your saved customers, cases, files, and documents. Retrieval is not an exhaustive review. It only reads; it does not change records or submit anything.',
    libraryActivity:'Retrieval for this request', librarySources:'Sources for this request', librarySourcesNote:'These states distinguish found metadata, read excerpts, and unavailable text. Full references are saved with the reply; this is not a full-library review.',
    librarySearchingStarted:'Saved-record search started', librarySearchingCompleted:'Saved-record search finished', librarySearchingError:'Saved-record search did not complete',
    libraryReadingStarted:'Relevant excerpt reading started', libraryReadingCompleted:'Excerpt reading finished', libraryReadingError:'Excerpt reading did not complete',
    libraryRetrievingStarted:'Library retrieval started', libraryRetrievingCompleted:'Library retrieval finished', libraryRetrievingError:'Library retrieval did not complete',
    libraryCount:'Records', libraryMetadata:'Metadata only; body not read', libraryRead:'Partial excerpts read', libraryUnreadable:'Body unavailable',
    libraryClient:'Customer', libraryCase:'Case', libraryAsset:'File', libraryArtifact:'Document', libraryVersion:'Version', libraryStale:'Historical version; review again', libraryDraft:'Draft', libraryFinal:'Final', libraryTitleTruncated:'Title shortened', libraryExcerptTruncated:'Excerpt window limited',
    libraryConsentError:'Library retrieval needs explicit consent for this send. Select it again before sending.', libraryRequestError:'Library retrieval could not complete. Do not treat this as confirmation that records were checked.',
    librarySensitive:'A relevant record may contain sensitive identifiers. Retrieval was blocked; review and de-identify it first.', libraryMissing:'A relevant record is unavailable or does not belong to this account.',
    libraryLimit:'This request reached a retrieval limit. Results may be incomplete.', libraryStopped:'Library retrieval stopped or timed out. Review any received content.',
    libraryCitation:'The model supplied an unverified source reference. Do not treat this result as verified.',
    privacy:'Do not send SSNs, banking, tax, or identity-document information. Up to 2 PNG / JPEG images, 2 MiB each, with sides no larger than 8192 pixels. Image bytes are not retained.',
    openingDocuments:'Documents were handed to Materials and Facts. Chat did not replace the case source.',
    documents:'Import and review PDF, CSV, XLS, and XLSX files on the Documents page. Files are never disguised as images here.',
    signIn:'Sign in before opening your case conversations.', unavailable:'The real model connection is not enabled. Ask the administrator to check settings. No fabricated response will replace it.',
    retry:'Edit this question again', retryNote:'The question is back in the composer. Review it and click Send to start a new model request.',
    reload:'Reload conversation', copy:'Copy reply', copied:'Reply copied', copyFailed:'Copy failed. Select and copy the text manually.',
    resetAsk:'Switching conversations stops the current reply and clears unsent text and images. Saved messages will not be deleted. Continue?',
    stopped:'Stopped. Received text remains incomplete; reload to confirm its saved state.',
    saved:'Messages are saved with this case', refreshFailed:'Saved state could not be loaded. Current text remains on this page; keep it open and reload later.',
    restored:'Conversation restored from the server', draftRestored:'Unsent text was restored from this tab. Reattach images and check saved history before sending again.', cacheUnavailable:'This input could not be added to temporary recovery. Keep the page open or copy it manually.', unsupportedFile:'Only PNG / JPEG images are accepted here. Import documents on the Documents page.',
    emptyError:'Enter a question or attach an image first.', tooLarge:'The text or images exceed a limit. Shorten the text or remove images.', imageError:'The image cannot be read or exceeds PNG / JPEG limits. Choose another image.',
    authError:'Your session expired. Sign in again. This request will not be resent automatically.', storageError:'The case or conversation could not be saved. Your question remains available to retry.',
    conflict:'The case was updated elsewhere. Reopen its latest version before continuing.', notFound:'This case or conversation does not exist or does not belong to this account.',
    busy:'Another request is processing. Try again shortly.', quota:'The usage limit for this period has been reached. Try again later.',
    sensitive:'Possible sensitive identifiers were detected. Remove or de-identify them before sending.', streamError:'The reply was interrupted or did not finish. Received text remains marked incomplete.',
    saveError:'The reply could not be confirmed as saved. Keep the current text and reload the conversation before treating it as retained.',
    duplicate:'This question was already submitted. Reload the conversation; a new send must be an explicit action.',
    capacity:'The storage or record limit was reached; no new model request was started.', network:'The network request failed. Check your connection. Paid requests are never retried automatically.',
    generic:'The action could not be completed. Try again later.', attachmentCount:'images', pending:'Unsent', imageOnly:'Question with images'
  }
};
const errorKeys = {
  LIBRARY_UNAVAILABLE:'libraryUnavailable', LIBRARY_CONSENT_REQUIRED:'libraryConsentError', LIBRARY_CONTEXT_INVALID:'libraryRequestError',
  LIBRARY_ARGUMENT_INVALID:'libraryRequestError', LIBRARY_TOOL_UNKNOWN:'libraryRequestError', LIBRARY_NOT_FOUND:'libraryMissing',
  LIBRARY_SENSITIVE_DATA:'librarySensitive', LIBRARY_RESULT_LIMIT:'libraryLimit', LIBRARY_TOOL_LIMIT:'libraryLimit',
  LIBRARY_ABORTED:'libraryStopped', LIBRARY_TIMEOUT:'libraryStopped', LIBRARY_UNVERIFIED_CITATION:'libraryCitation',
  CHAT_EMPTY:'emptyError', CHAT_TOO_LARGE:'tooLarge', INPUT_TOO_LARGE:'tooLarge', CHAT_IMAGE_INVALID:'imageError', CHAT_IMAGE_UNSUPPORTED:'imageError', CHAT_IMAGE_BUSY:'imageBusy',
  AUTH_REQUIRED:'authError', CSRF_REJECTED:'authError', OPERATOR_SETUP_REQUIRED:'authError', HTTPS_REQUIRED:'authError', ORIGIN_REJECTED:'authError',
  LIVE_DISABLED:'unavailable', API_KEY_REQUIRED:'unavailable', CASE_INVALID:'storageError', CONVERSATION_INVALID:'storageError', INVALID_RESPONSE:'storageError',
  CASE_CONFLICT:'conflict', CASE_NOT_FOUND:'notFound', CONVERSATION_NOT_FOUND:'notFound', BUSY:'busy', CHAT_CONVERSATION_BUSY:'busy',
  TRIAL_LIMIT_REACHED:'quota', SENSITIVE_DATA:'sensitive', CHAT_PROVIDER_FAILED:'streamError', CHAT_STREAM_FAILED:'streamError', CHAT_INCOMPLETE:'streamError', CHAT_UNSUPPORTED_OUTPUT:'streamError',
  CHAT_SAVE_FAILED:'saveError', CHAT_TURN_EXISTS:'duplicate', CAPACITY_REACHED:'capacity', CASE_LIMIT_REACHED:'capacity', NETWORK_ERROR:'network'
};
export function chatErrorText(error, lang='zh') { const words=chatCopy[lang] || chatCopy.zh; return words[errorKeys[error?.code] || 'generic']; }

const activityKeys = {
  searching:{started:'librarySearchingStarted',completed:'librarySearchingCompleted',error:'librarySearchingError'},
  reading:{started:'libraryReadingStarted',completed:'libraryReadingCompleted',error:'libraryReadingError'},
  retrieving:{started:'libraryRetrievingStarted',completed:'libraryRetrievingCompleted',error:'libraryRetrievingError'}
};
export function libraryActivityText(activity,lang='zh') {
  const words=chatCopy[lang]||chatCopy.zh;
  return words[activityKeys[activity?.phase]?.[activity?.state]] || words.libraryRequestError;
}
