import { conversationActionError } from './conversation-actions.js';
export const chatCopy = {
  "zh": {
    "caseSaveUncertain": "未能确认新案例是否已保存。请先在客户库检查并打开已保存的案例，避免重复创建；当前输入仍保留。",
    "keyboardHint": "Enter 发送 · Shift+Enter 换行",
    "title": "对话",
    "conversation": "已有会话",
    "newConversation": "新会话",
    "untitledConversation": "案例会话",
    "untitledCase": "未命名案例",
    "loading": "正在读取已保存会话…",
    "empty": "今天想处理什么？",
    "composer": "这次想处理什么？",
    "placeholder": "输入消息…",
    "send": "发送",
    "stop": "停止回复",
    "sending": "正在回复…",
    "saving": "正在保存…",
    "decoding": "正在检查图片…",
    "imageBusy": "上一批图片仍在检查，请完成后再添加。",
    "attach": "添加附件",
    "remove": "移除图片",
    "you": "你",
    "assistant": "助手",
    "incomplete": "回复已中断",
    "localOnly": "尚未确认保存，请复制保留。",
    "oldImage": "本对话不保留图片原始文件。已另存的原图可在「材料与事实」查看；否则请重新添加。",
    "openingDocuments": "文档已交给材料与事实页面处理；聊天内容没有覆盖案例材料。",
    "documents": "请在「材料与事实」页导入文件。",
    "signIn": "请先登录，再打开自己的案例会话。",
    "unavailable": "请先在设置中连接 DeepSeek。",
    "retry": "重新编辑这次问题",
    "retryNote": "已放回输入框，可修改后发送。",
    "reload": "重新读取会话",
    "copy": "复制回复",
    "copied": "已复制回复",
    "copyFailed": "复制失败，请手动选择文字复制。",
    "resetAsk": "切换会话会停止当前回复，并清除尚未发送的文字和图片。已保存消息不会删除。继续？",
    "stopped": "已停止回复",
    "refreshFailed": "无法读取保存状态，请保留当前页面并重试。",
    "restored": "已从服务器恢复会话",
    "draftRestored": "已恢复未发送的文字，请重新添加图片。",
    "cacheUnavailable": "请复制保留当前输入。",
    "unsupportedFile": "此处仅接受 PNG / JPEG 图片。文档请在「材料与事实」页面导入。",
    "emptyError": "请先输入问题或添加图片。",
    "tooLarge": "输入或图片超过限制，请缩短文字或减少图片。",
    "imageError": "图片无法读取或超过 PNG / JPEG 限制，请换一张图片。",
    "authError": "请重新登录后发送。",
    "storageError": "案例或会话未能保存。问题仍保留，请检查后重试。",
    "conflict": "案例已在别处更新，请重新打开最新案例后继续。",
    "notFound": "当前案例或会话不存在，或不属于此账号。",
    "busy": "已有请求在处理中，请稍后再试。",
    "quota": "本时段使用次数已达上限，请稍后再试。",
    "sensitive": "检测到可能的敏感标识，请删除或去标识后再发送。",
    "streamError": "回复中断，请重试。",
    "saveError": "未能确认回复保存，请复制保留后重试。",
    "duplicate": "这次问题已提交过。请重新读取会话；如需再问，使用一次新的明确发送。",
    "capacity": "存储空间已满，请整理已有记录。",
    "network": "连接失败，请检查网络后重试。",
    "generic": "操作未完成，请稍后重试。",
    "attachmentCount": "张图片",
    "pending": "尚未发送",
    "imageOnly": "附图问题",
    "chooseConversation": "选择已有会话",
    "noConversations": "暂无已保存会话",
    "noConversationsReason": "首次发送消息时会建立并保存会话。",
    "libraryConsent": "允许 AI 检索本账户资料库，并向 DeepSeek 提供相关摘录；可在设置中关闭。",
    "libraryUnavailable": "当前服务器不支持资料库检索；普通聊天仍可使用。检索不会静默降级。",
    "libraryBoundary": "可检索本人保存的客户、案例、文件和文书。检索不代表完整审阅；只读取，不会修改资料或自动提交。",
    "libraryActivity": "本次资料检索",
    "librarySources": "本次引用来源",
    "librarySourcesNote": "下列状态区分仅找到记录、读取摘录和正文不可读。引用已附在回复中；是否已保存请以回复状态为准。检索不代表完整资料库审查。",
    "librarySearchingStarted": "已开始搜索保存的记录",
    "librarySearchingCompleted": "记录搜索已结束",
    "librarySearchingError": "记录搜索未完成",
    "libraryReadingStarted": "已开始读取相关摘录",
    "libraryReadingCompleted": "摘录读取已结束",
    "libraryReadingError": "摘录读取未完成",
    "libraryRetrievingStarted": "已开始资料检索",
    "libraryRetrievingCompleted": "资料检索已结束",
    "libraryRetrievingError": "资料检索未完成",
    "libraryCount": "记录数",
    "libraryMetadata": "仅记录信息，未读取正文",
    "libraryRead": "已读取部分摘录",
    "libraryUnreadable": "正文不可读",
    "libraryClient": "客户",
    "libraryCase": "案例",
    "libraryAsset": "文件",
    "libraryArtifact": "文书",
    "libraryVersion": "版本",
    "libraryStale": "历史版本，需重新核对",
    "libraryDraft": "草稿",
    "libraryFinal": "终稿",
    "libraryTitleTruncated": "标题已截短",
    "libraryExcerptTruncated": "仅读取了受限摘录",
    "libraryConsentError": "资料库授权已更改或尚未授予。请在账户与设置中核对授权，再重新发送。",
    "libraryRequestError": "资料检索请求未能完成，不能据此声称已检查资料。",
    "librarySensitive": "相关记录可能含敏感标识，检索已阻止；请先检查并去标识。",
    "libraryMissing": "相关记录不可用或不属于此账号。",
    "libraryLimit": "本次检索已到达读取限制；结果可能不完整。",
    "libraryStopped": "资料检索已停止或超时；已收到内容仍需核对。",
    "libraryCitation": "模型给出了未核实的来源引用，不能把本次结果当作已核实结论。"
  },
  "en": {
    "caseSaveUncertain": "The new case may already be saved. Check Customers and open the saved case before trying again to avoid duplicates. Your input is preserved.",
    "keyboardHint": "Enter to send · Shift+Enter for a new line",
    "title": "Conversation",
    "conversation": "Saved conversations",
    "newConversation": "New conversation",
    "untitledConversation": "Case conversation",
    "untitledCase": "Untitled case",
    "loading": "Loading saved conversation…",
    "empty": "What would you like to work on?",
    "composer": "What would you like to work on?",
    "placeholder": "Message Nestlet…",
    "send": "Send",
    "stop": "Stop reply",
    "sending": "Replying…",
    "saving": "Saving…",
    "decoding": "Checking images…",
    "imageBusy": "The previous images are still being checked. Add more after processing finishes.",
    "attach": "Attach",
    "remove": "Remove image",
    "you": "You",
    "assistant": "Assistant",
    "incomplete": "Reply interrupted",
    "localOnly": "Save not confirmed. Copy this reply to keep it.",
    "oldImage": "This conversation does not retain image bytes. Previously saved originals may be in Materials; otherwise reattach.",
    "openingDocuments": "Documents were handed to Materials and Facts. Chat did not replace the case source.",
    "documents": "Import files on the Materials & facts page.",
    "signIn": "Sign in before opening your case conversations.",
    "unavailable": "Connect DeepSeek in Settings first.",
    "retry": "Edit this question again",
    "retryNote": "The message is back in the composer. Edit and send it again.",
    "reload": "Reload conversation",
    "copy": "Copy reply",
    "copied": "Reply copied",
    "copyFailed": "Copy failed. Select and copy the text manually.",
    "resetAsk": "Switching conversations stops the current reply and clears unsent text and images. Saved messages will not be deleted. Continue?",
    "stopped": "Reply stopped",
    "refreshFailed": "Could not check the saved status. Keep this page open and try again.",
    "restored": "Conversation restored from the server",
    "draftRestored": "Unsent text restored. Reattach images.",
    "cacheUnavailable": "Copy your current input to keep it.",
    "unsupportedFile": "Only PNG / JPEG images are accepted here. Import documents on the Materials & facts page.",
    "emptyError": "Enter a question or attach an image first.",
    "tooLarge": "The text or images exceed a limit. Shorten the text or remove images.",
    "imageError": "The image cannot be read or exceeds PNG / JPEG limits. Choose another image.",
    "authError": "Sign in again before sending.",
    "storageError": "The case or conversation could not be saved. Your question remains available to retry.",
    "conflict": "The case was updated elsewhere. Reopen its latest version before continuing.",
    "notFound": "This case or conversation does not exist or does not belong to this account.",
    "busy": "Another request is processing. Try again shortly.",
    "quota": "The usage limit for this period has been reached. Try again later.",
    "sensitive": "Possible sensitive identifiers were detected. Remove or de-identify them before sending.",
    "streamError": "The reply was interrupted. Try again.",
    "saveError": "Could not confirm the saved reply. Copy it before retrying.",
    "duplicate": "This question was already submitted. Reload the conversation; a new send must be an explicit action.",
    "capacity": "Storage is full. Review your saved records.",
    "network": "Connection failed. Check your network and try again.",
    "generic": "The action could not be completed. Try again later.",
    "attachmentCount": "images",
    "pending": "Unsent",
    "imageOnly": "Question with images",
    "chooseConversation": "Choose a saved conversation",
    "noConversations": "No saved conversations",
    "noConversationsReason": "Your first send creates and saves a conversation.",
    "libraryConsent": "Allow AI to search this account’s saved library and send relevant excerpts to DeepSeek; turn it off in settings.",
    "libraryUnavailable": "This server does not support library retrieval. Ordinary chat remains available; retrieval will not silently fall back.",
    "libraryBoundary": "Searches your saved customers, cases, files, and documents. Retrieval is not an exhaustive review. It only reads; it does not change records or submit anything.",
    "libraryActivity": "Retrieval for this request",
    "librarySources": "Sources for this request",
    "librarySourcesNote": "These states distinguish found metadata, read excerpts, and unavailable text. References are included with the reply; check its save status. This is not a full-library review.",
    "librarySearchingStarted": "Saved-record search started",
    "librarySearchingCompleted": "Saved-record search finished",
    "librarySearchingError": "Saved-record search did not complete",
    "libraryReadingStarted": "Relevant excerpt reading started",
    "libraryReadingCompleted": "Excerpt reading finished",
    "libraryReadingError": "Excerpt reading did not complete",
    "libraryRetrievingStarted": "Library retrieval started",
    "libraryRetrievingCompleted": "Library retrieval finished",
    "libraryRetrievingError": "Library retrieval did not complete",
    "libraryCount": "Records",
    "libraryMetadata": "Metadata only; body not read",
    "libraryRead": "Partial excerpts read",
    "libraryUnreadable": "Body unavailable",
    "libraryClient": "Customer",
    "libraryCase": "Case",
    "libraryAsset": "File",
    "libraryArtifact": "Document",
    "libraryVersion": "Version",
    "libraryStale": "Historical version; review again",
    "libraryDraft": "Draft",
    "libraryFinal": "Final",
    "libraryTitleTruncated": "Title shortened",
    "libraryExcerptTruncated": "Excerpt window limited",
    "libraryConsentError": "Saved-library permission changed or has not been granted. Review it in Account and settings before sending again.",
    "libraryRequestError": "Library retrieval could not complete. Do not treat this as confirmation that records were checked.",
    "librarySensitive": "A relevant record may contain sensitive identifiers. Retrieval was blocked; review and de-identify it first.",
    "libraryMissing": "A relevant record is unavailable or does not belong to this account.",
    "libraryLimit": "This request reached a retrieval limit. Results may be incomplete.",
    "libraryStopped": "Library retrieval stopped or timed out. Review any received content.",
    "libraryCitation": "The model supplied an unverified source reference. Do not treat this result as verified."
  }
};
const errorKeys = {
  LIBRARY_PERMISSION_REVOKED:'libraryConsentError', LIBRARY_PERMISSION_CONFLICT:'libraryConsentError', LIBRARY_PERMISSION_INVALID:'libraryConsentError', LIBRARY_UNAVAILABLE:'libraryUnavailable', LIBRARY_CONSENT_REQUIRED:'libraryConsentError', LIBRARY_CONTEXT_INVALID:'libraryRequestError',
  LIBRARY_ARGUMENT_INVALID:'libraryRequestError', LIBRARY_TOOL_UNKNOWN:'libraryRequestError', LIBRARY_NOT_FOUND:'libraryMissing',
  LIBRARY_SENSITIVE_DATA:'librarySensitive', LIBRARY_RESULT_LIMIT:'libraryLimit', LIBRARY_TOOL_LIMIT:'libraryLimit',
  LIBRARY_ABORTED:'libraryStopped', LIBRARY_TIMEOUT:'libraryStopped', LIBRARY_UNVERIFIED_CITATION:'libraryCitation',
  CHAT_EMPTY:'emptyError', CHAT_TOO_LARGE:'tooLarge', INPUT_TOO_LARGE:'tooLarge', CHAT_IMAGE_INVALID:'imageError', CHAT_IMAGE_UNSUPPORTED:'imageError', CHAT_IMAGE_BUSY:'imageBusy',
  AUTH_REQUIRED:'authError', CSRF_REJECTED:'authError', OPERATOR_SETUP_REQUIRED:'authError', HTTPS_REQUIRED:'authError', ORIGIN_REJECTED:'authError',
  LIVE_DISABLED:'unavailable', API_KEY_REQUIRED:'unavailable', CASE_INVALID:'storageError', CONVERSATION_INVALID:'storageError', INVALID_RESPONSE:'storageError',
  CASE_SAVE_UNCERTAIN:'caseSaveUncertain', CASE_CONFLICT:'conflict', CASE_NOT_FOUND:'notFound', CONVERSATION_NOT_FOUND:'notFound', BUSY:'busy', CHAT_CONVERSATION_BUSY:'busy',
  TRIAL_LIMIT_REACHED:'quota', SENSITIVE_DATA:'sensitive', CHAT_PROVIDER_FAILED:'streamError', CHAT_STREAM_FAILED:'streamError', CHAT_INCOMPLETE:'streamError', CHAT_UNSUPPORTED_OUTPUT:'streamError',
  CHAT_SAVE_FAILED:'saveError', CHAT_TURN_EXISTS:'duplicate', CAPACITY_REACHED:'capacity', CASE_LIMIT_REACHED:'capacity', NETWORK_ERROR:'network'
};
export function chatErrorText(error, lang='zh') { if(['CONVERSATION_ACTION_INVALID','CONVERSATION_ACTION_SOURCE_NOT_FOUND','CONVERSATION_ACTION_SOURCE_INCOMPLETE','DOCUMENT_ENGLISH_REQUIRED'].includes(error?.code))return conversationActionError(error,lang); const words=chatCopy[lang] || chatCopy.zh; return words[errorKeys[error?.code] || 'generic']; }

const activityKeys = {
  searching:{started:'librarySearchingStarted',completed:'librarySearchingCompleted',error:'librarySearchingError'},
  reading:{started:'libraryReadingStarted',completed:'libraryReadingCompleted',error:'libraryReadingError'},
  retrieving:{started:'libraryRetrievingStarted',completed:'libraryRetrievingCompleted',error:'libraryRetrievingError'}
};
export function libraryActivityText(activity,lang='zh') {
  const words=chatCopy[lang]||chatCopy.zh;
  return words[activityKeys[activity?.phase]?.[activity?.state]] || words.libraryRequestError;
}
