// Focused same-case rename regression: actual App + React DOM + HTTP + SQLite.
// Disposable synthetic data only. No provider or standalone browser run.
import test from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { createServer } from 'vite';
import { startBrowserFixture } from '../../../test/helpers/browser-fixture.mjs';
import { newCasePayload } from './logic.js';

test('saved case rename does not replace the conversation title or clear pending drafts', {timeout:30000}, async context => {
  const app=await startBrowserFixture({legacyUsers:['synthetic-title-refresh']});
  const realFetch=globalThis.fetch;
  const login=await realFetch(app.origin+'/api/login',{method:'POST',headers:{Origin:app.origin,'Content-Type':'application/json'},body:JSON.stringify({username:'synthetic-title-refresh',password:'Case26'})});
  assert.equal(login.status,200);const session=await login.json(),cookie=login.headers.get('set-cookie').split(';')[0];
  const seed=async(path,body)=>{const response=await realFetch(app.origin+path,{method:'POST',headers:{Origin:app.origin,Cookie:cookie,'Content-Type':'application/json','X-CSRF-Token':session.csrfToken},body:JSON.stringify(body)});assert.equal(response.status,201);return response.json();};
  const {case:record}=await seed('/api/cases',newCasePayload('Synthetic original title'));
  const {conversation:first}=await seed(`/api/cases/${record.id}/conversations`,{title:'Synthetic conversation to preserve'});
  await seed(`/api/cases/${record.id}/conversations`,{title:'Other synthetic conversation'});
  const dom=new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>',{url:app.origin,pretendToBeVisual:true});
  const originals=new Map(),set=(key,value)=>{originals.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});};
  for(const key of ['window','document','navigator','HTMLElement','Element','Node','MutationObserver','Event','MouseEvent'])set(key,dom.window[key]);
  set('getComputedStyle',dom.window.getComputedStyle.bind(dom.window));set('IS_REACT_ACT_ENVIRONMENT',true);set('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});
  dom.window.confirm=()=>true;dom.window.HTMLElement.prototype.scrollIntoView=function(){};
  const requests=[];
  let releaseInitialStatus, holdInitialStatus=true;
  const initialStatusGate=new Promise(resolve=>{releaseInitialStatus=resolve;});
  set('fetch',async(path,options={})=>{const response=await realFetch(app.origin+path,{...options,headers:{...options.headers,Origin:app.origin,Cookie:cookie}});requests.push({path,method:options.method||'GET',status:response.status});if(path==='/api/status'&&holdInitialStatus){holdInitialStatus=false;await initialStatusGate;}return response;});
  const React=await import('react'),{createRoot}=await import('react-dom/client');
  const vite=await createServer({server:{middlewareMode:true,hmr:false,ws:false,watch:null},logLevel:'error'});
  const {SessionProvider}=await vite.ssrLoadModule('/lib/session.jsx'),{default:App}=await vite.ssrLoadModule('/App.jsx');
  const root=createRoot(document.getElementById('root'));
  context.after(async()=>{await React.act(async()=>root.unmount());await vite.close();dom.window.close();for(const[key,descriptor]of originals){if(descriptor)Object.defineProperty(globalThis,key,descriptor);else delete globalThis[key];}await app.stop();});
  const flush=async()=>React.act(async()=>new Promise(resolve=>setTimeout(resolve,10)));
  const wait=async(predicate,label)=>{for(let end=Date.now()+5000;!predicate();){if(Date.now()>end)throw new Error(label);await flush();}};
  const button=(label,scope=document)=>[...scope.querySelectorAll('button')].find(node=>!node.closest('[hidden]')&&(node.textContent.trim()===label||node.getAttribute('aria-label')===label));
  const click=async node=>{assert.ok(node,'Expected button');assert.equal(node.disabled,false);await React.act(async()=>node.click());await flush();};
  const change=async(node,value)=>{assert.ok(node,'Expected input');await React.act(async()=>{const proto=node.tagName==='TEXTAREA'?dom.window.HTMLTextAreaElement.prototype:node.tagName==='SELECT'?dom.window.HTMLSelectElement.prototype:dom.window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(node,value);node.dispatchEvent(new dom.window.Event(node.tagName==='SELECT'?'change':'input',{bubbles:true}));});await flush();};
  const input=label=>{const node=[...document.querySelectorAll('label')].find(node=>!node.closest('[hidden]')&&node.textContent===label);return node&&document.getElementById(node.htmlFor);};
  const nav=async label=>{await wait(()=>{const scope=document.querySelector('nav[aria-label="Workspace navigation"]');return scope&&button(label,scope);},'Authenticated navigation ready');await click(button(label,document.querySelector('nav[aria-label="Workspace navigation"]')));};
  const title=()=>document.querySelector('.chat-toolbar [data-slot="card-title"]')?.textContent;
  await React.act(async()=>root.render(React.createElement(SessionProvider,null,React.createElement(App))));
  await wait(()=>button('Switch interface to English'),'App loaded');await click(button('Switch interface to English'));
  assert.equal(document.querySelector('nav[aria-label="Workspace navigation"]'),null,'Language is usable while authentication is still loading');
  releaseInitialStatus();
  await nav('Customers');await wait(()=>button('Open saved case: '+record.title),'Saved case listed');await click(button('Open saved case: '+record.title));
  await wait(()=>title()==='Other synthetic conversation'&&!button('New conversation',document.querySelector('.chat-toolbar')).disabled,'Conversation title loaded');
  await change(document.querySelector('.chat-toolbar select'),first.id);await wait(()=>!button('New conversation',document.querySelector('.chat-toolbar')).disabled,'Selected conversation loaded');
  await change(document.querySelector('.chat-input'),'Unsent chat question must survive');
  const historyReads=requests.filter(item=>item.path.startsWith('/api/conversations/')).length;
  await nav('Materials & facts');await wait(()=>input('Case name')?.value===record.title,'Material editor loaded');
  await change(input('Case name'),'Synthetic renamed case');await click(button('Save case'));
  await wait(()=>requests.some(item=>item.path===`/api/cases/${record.id}`&&item.method==='PUT'&&item.status===200)&&!button('Save case').disabled,'Rename persisted');
  await change(input('Case source text'),'Unsaved material draft after the rename');
  await nav('Conversation');
  await wait(()=>title()===first.title,'Saved case rename must not overwrite the conversation title');
  assert.equal(document.querySelector('.chat-input').value,'Unsent chat question must survive');
  assert.equal(document.querySelector('.chat-toolbar select').value,first.id);
  assert.equal(requests.filter(item=>item.path.startsWith('/api/conversations/')).length,historyReads,'Title refresh must not reload or replace conversation history');
  assert.equal(requests.filter(item=>item.path===`/api/cases/${record.id}`&&item.method==='PUT').length,1);
  await nav('Materials & facts');assert.equal(input('Case source text').value,'Unsaved material draft after the rename');
  assert.equal(input('Case name').value,'Synthetic renamed case');
  assert.equal(requests.some(item=>item.path==='/api/chat'||item.path==='/api/extract'),false);
});
