// Focused same-case rename regression: actual App + React DOM + HTTP + SQLite.
// Disposable synthetic data only. No provider or standalone browser run.
import test from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { createServer } from 'vite';
import { startBrowserFixture } from '../../../test/helpers/browser-fixture.mjs';
import { newCasePayload } from './logic.js';

test('unified history opens the exact conversation across cases and guards unsaved work without extra writes', {timeout:30000}, async context => {
  const app=await startBrowserFixture({legacyUsers:['synthetic-title-refresh']});
  const realFetch=globalThis.fetch;
  const login=await realFetch(app.origin+'/api/login',{method:'POST',headers:{Origin:app.origin,'Content-Type':'application/json'},body:JSON.stringify({username:'synthetic-title-refresh',password:'Case26'})});
  assert.equal(login.status,200);const session=await login.json(),cookie=login.headers.get('set-cookie').split(';')[0];
  const seed=async(path,body)=>{const response=await realFetch(app.origin+path,{method:'POST',headers:{Origin:app.origin,Cookie:cookie,'Content-Type':'application/json','X-CSRF-Token':session.csrfToken},body:JSON.stringify(body)});assert.equal(response.status,201);return response.json();};
  const {case:record}=await seed('/api/cases',newCasePayload('Synthetic original title'));
  const {conversation:first}=await seed(`/api/cases/${record.id}/conversations`,{title:'Synthetic conversation to preserve'});
  const {case:other}=await seed('/api/cases',newCasePayload('Synthetic second case'));
  const {conversation:second}=await seed(`/api/cases/${other.id}/conversations`,{title:'Second conversation title'});
  const dom=new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>',{url:app.origin,pretendToBeVisual:true});
  const originals=new Map(),set=(key,value)=>{originals.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});};
  for(const key of ['window','document','navigator','HTMLElement','Element','Node','MutationObserver','Event','MouseEvent'])set(key,dom.window[key]);
  set('getComputedStyle',dom.window.getComputedStyle.bind(dom.window));set('IS_REACT_ACT_ENVIRONMENT',true);set('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});
  dom.window.confirm=()=>true;dom.window.HTMLElement.prototype.scrollIntoView=function(){};
  const requests=[];
  let releaseInitialStatus, holdInitialStatus=true;
  const initialStatusGate=new Promise(resolve=>{releaseInitialStatus=resolve;});
  set('fetch',async(path,options={})=>{const response=await realFetch(app.origin+path,{...options,headers:{...options.headers,Origin:app.origin,Cookie:cookie}});requests.push({path,method:options.method||'GET',status:response.status});if(path==='/api/status'&&holdInitialStatus){holdInitialStatus=false;await initialStatusGate;}return response;});
  const React=await import('react'),{createRoot}=await import('react-dom/client');
  const vite=await createServer({server:{middlewareMode:true,hmr:false,ws:false,watch:null},logLevel:'error'});
  const {SessionProvider}=await vite.ssrLoadModule('/lib/session.jsx'),{default:App}=await vite.ssrLoadModule('/App.jsx');
  const root=createRoot(document.getElementById('root'));
  context.after(async()=>{await React.act(async()=>root.unmount());await vite.close();dom.window.close();for(const[key,descriptor]of originals){if(descriptor)Object.defineProperty(globalThis,key,descriptor);else delete globalThis[key];}await app.stop();});
  const flush=async()=>React.act(async()=>new Promise(resolve=>setTimeout(resolve,10)));
  const wait=async(predicate,label)=>{for(let end=Date.now()+5000;!predicate();){if(Date.now()>end)throw new Error(label);await flush();}};
  const button=(label,scope=document)=>[...scope.querySelectorAll('button')].find(node=>!node.closest('[hidden]')&&(node.textContent.trim()===label||node.getAttribute('aria-label')===label));
  const click=async node=>{assert.ok(node,'Expected button');assert.equal(node.disabled,false);await React.act(async()=>node.click());await flush();};
  const change=async(node,value)=>{assert.ok(node,'Expected input');await React.act(async()=>{const proto=node.tagName==='TEXTAREA'?dom.window.HTMLTextAreaElement.prototype:node.tagName==='SELECT'?dom.window.HTMLSelectElement.prototype:dom.window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(node,value);node.dispatchEvent(new dom.window.Event(node.tagName==='SELECT'?'change':'input',{bubbles:true}));});await flush();};
  const input=label=>{const node=[...document.querySelectorAll('label')].find(node=>!node.closest('[hidden]')&&node.textContent===label);return node&&document.getElementById(node.htmlFor);};
  const nav=async label=>{await wait(()=>{const scope=document.querySelector('nav[aria-label="Workspace navigation"]');return scope&&button(label,scope);},'Authenticated navigation ready');await click(button(label,document.querySelector('nav[aria-label="Workspace navigation"]')));};
  const title=()=>document.querySelector('.chat-toolbar [data-slot="card-title"]')?.textContent;
  await React.act(async()=>root.render(React.createElement(SessionProvider,null,React.createElement(App))));
  await wait(()=>button('Switch interface to English'),'App loaded');await click(button('Switch interface to English'));
  assert.equal(document.querySelector('nav[aria-label="Workspace navigation"]'),null,'Language is usable while authentication is still loading');
  releaseInitialStatus();
  const rail=()=>document.querySelector('nav[aria-label="Conversations"]');
  await wait(()=>rail()?.querySelectorAll('a').length===2,'Account history is loaded');
  assert.ok(document.querySelector('[data-conversation-opening]').textContent.includes('Hi, I’m Nestlet.'));
  const link=id=>rail().querySelector(`a[href="#chat?conversation=${id}"]`);
  const clickLink=async node=>{await React.act(async()=>node.dispatchEvent(new dom.window.MouseEvent('click',{bubbles:true,cancelable:true,button:0})));await flush();};
  await clickLink(link(first.id));await wait(()=>title()===first.title,'Exact first conversation opened');
  assert.equal(document.querySelector('.chat-toolbar select').value,first.id);
  assert.equal(window.location.hash,`#chat?conversation=${first.id}`);
  await change(document.querySelector('.chat-input'),'Unsent note');
  let confirmations=0;dom.window.confirm=()=>{confirmations++;return false;};
  await clickLink(link(second.id));assert.equal(document.querySelector('.chat-input').value,'Unsent note');assert.equal(title(),first.title);assert.equal(confirmations,1);
  dom.window.confirm=()=>true;await clickLink(link(second.id));await wait(()=>title()===second.title,'Cross-case exact conversation opened');
  assert.equal(document.querySelector('.chat-input').value,'');
  const reads=requests.filter(item=>item.path===`/api/conversations/${second.id}`).length;
  await clickLink(link(second.id));assert.equal(requests.filter(item=>item.path===`/api/conversations/${second.id}`).length,reads,'Reopening the active conversation is a no-op');
  assert.equal(requests.some(item=>item.method==='POST'),false,'Opening history performs no model calls or writes');
  await React.act(async()=>{window.location.hash=`#chat?conversation=${first.id}`;});
  await wait(()=>title()===first.title,'Exact conversation hash navigation works');
  assert.equal(requests.some(item=>item.path==='/api/chat'),false);
});
