// Focused same-case rename regression: actual App + React DOM + HTTP + SQLite.
// Disposable synthetic data only. No provider or standalone browser run.
import test from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { createServer } from 'vite';
import { startBrowserFixture } from '../../../test/helpers/browser-fixture.mjs';
import { newCasePayload } from './logic.js';

test('unified history opens the exact conversation across cases and guards unsaved work without extra writes', {timeout:30000}, async context => {
  const app=await startBrowserFixture({legacyUsers:['synthetic-title-refresh']});
  const realFetch=globalThis.fetch;
  const login=await realFetch(app.origin+'/api/login',{method:'POST',headers:{Origin:app.origin,'Content-Type':'application/json'},body:JSON.stringify({username:'synthetic-title-refresh',password:'Case26'})});
  assert.equal(login.status,200);const session=await login.json(),cookie=login.headers.get('set-cookie').split(';')[0];
  const seed=async(path,body)=>{const response=await realFetch(app.origin+path,{method:'POST',headers:{Origin:app.origin,Cookie:cookie,'Content-Type':'application/json','X-CSRF-Token':session.csrfToken},body:JSON.stringify(body)});assert.equal(response.status,201);return response.json();};
  const {case:record}=await seed('/api/cases',newCasePayload('Synthetic original title'));
  const {conversation:first}=await seed(`/api/cases/${record.id}/conversations`,{title:'Synthetic conversation to preserve'});
  const {case:other}=await seed('/api/cases',newCasePayload('Synthetic second case'));
  const {conversation:second}=await seed(`/api/cases/${other.id}/conversations`,{title:'Second conversation title'});
  const dom=new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>',{url:app.origin,pretendToBeVisual:true});
  const originals=new Map(),set=(key,value)=>{originals.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});};
  for(const key of ['window','document','navigator','HTMLElement','Element','Node','MutationObserver','Event','MouseEvent'])set(key,dom.window[key]);
  set('getComputedStyle',dom.window.getComputedStyle.bind(dom.window));set('IS_REACT_ACT_ENVIRONMENT',true);set('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});
  dom.window.confirm=()=>true;dom.window.HTMLElement.prototype.scrollIntoView=function(){};
  const requests=[];
  let releaseInitialStatus, holdInitialStatus=true;
  const initialStatusGate=new Promise(resolve=>{releaseInitialStatus=resolve;});
  set('fetch',async(path,options={})=>{const response=await realFetch(app.origin+path,{...options,headers:{...options.headers,Origin:app.origin,Cookie:cookie}});requests.push({path,method:options.method||'GET',status:response.status});if(path==='/api/status'&&holdInitialStatus){holdInitialStatus=false;await initialStatusGate;}if(path==='/api/status')return new Response(JSON.stringify({...await response.json(),liveEnabled:true}),{status:response.status,headers:{'Content-Type':'application/json'}});return response;});
  const React=await import('react'),{createRoot}=await import('react-dom/client');
  const vite=await createServer({server:{middlewareMode:true,hmr:false,ws:false,watch:null},logLevel:'error'});
  const {SessionProvider}=await vite.ssrLoadModule('/lib/session.jsx'),{default:App}=await vite.ssrLoadModule('/App.jsx');
  const root=createRoot(document.getElementById('root'));
  context.after(async()=>{await React.act(async()=>root.unmount());await vite.close();dom.window.close();for(const[key,descriptor]of originals){if(descriptor)Object.defineProperty(globalThis,key,descriptor);else delete globalThis[key];}await app.stop();});
  const flush=async()=>React.act(async()=>new Promise(resolve=>setTimeout(resolve,10)));
  const wait=async(predicate,label)=>{for(let end=Date.now()+5000;!predicate();){if(Date.now()>end)throw new Error(label);await flush();}};
  const button=(label,scope=document)=>[...scope.querySelectorAll('button')].find(node=>!node.closest('[hidden]')&&(node.textContent.trim()===label||node.getAttribute('aria-label')===label));
  const click=async node=>{assert.ok(node,'Expected button');assert.equal(node.disabled,false);await React.act(async()=>node.click());await flush();};
  const change=async(node,value)=>{assert.ok(node,'Expected input');await React.act(async()=>{const proto=node.tagName==='TEXTAREA'?dom.window.HTMLTextAreaElement.prototype:node.tagName==='SELECT'?dom.window.HTMLSelectElement.prototype:dom.window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(node,value);node.dispatchEvent(new dom.window.Event(node.tagName==='SELECT'?'change':'input',{bubbles:true}));});await flush();};
  const input=label=>{const node=[...document.querySelectorAll('label')].find(node=>!node.closest('[hidden]')&&node.textContent===label);return node&&document.getElementById(node.htmlFor);};
  const nav=async label=>{await wait(()=>{const scope=document.querySelector('nav[aria-label="Workspace navigation"]');return scope&&button(label,scope);},'Authenticated navigation ready');await click(button(label,document.querySelector('nav[aria-label="Workspace navigation"]')));};
  const title=()=>document.querySelector('.chat-toolbar [data-slot="card-title"]')?.textContent;
  await React.act(async()=>root.render(React.createElement(SessionProvider,null,React.createElement(App))));
  await wait(()=>button('Switch interface to English'),'App loaded');await click(button('Switch interface to English'));
  assert.equal(document.querySelector('nav[aria-label="Workspace navigation"]'),null,'Language is usable while authentication is still loading');
  releaseInitialStatus();
  const rail=()=>document.querySelector('nav[aria-label="Conversations"]');
  await wait(()=>rail()?.querySelectorAll('a').length===2,'Account history is loaded');
  assert.ok(document.querySelector('[data-conversation-opening]').textContent.includes('Hi, I’m Nestlet.'));
  const link=id=>rail().querySelector(`a[href="#chat?conversation=${id}"]`);
  const clickLink=async node=>{await React.act(async()=>node.dispatchEvent(new dom.window.MouseEvent('click',{bubbles:true,cancelable:true,button:0})));await flush();};
  await clickLink(link(first.id));await wait(()=>title()===first.title,'Exact first conversation opened');
  assert.equal(document.querySelector('.chat-toolbar select').value,first.id);
  assert.equal(window.location.hash,`#chat?conversation=${first.id}`);
  await change(document.querySelector('.chat-input'),'Unsent note');
  let confirmations=0;dom.window.confirm=()=>{confirmations++;return false;};
  await clickLink(link(second.id));assert.equal(document.querySelector('.chat-input').value,'Unsent note');assert.equal(title(),first.title);assert.equal(confirmations,1);
  dom.window.confirm=()=>true;await clickLink(link(second.id));await wait(()=>title()===second.title,'Cross-case exact conversation opened');
  assert.equal(document.querySelector('.chat-input').value,'');
  const reads=requests.filter(item=>item.path===`/api/conversations/${second.id}`).length;
  await clickLink(link(second.id));assert.equal(requests.filter(item=>item.path===`/api/conversations/${second.id}`).length,reads,'Reopening the active conversation is a no-op');
  assert.equal(requests.some(item=>item.method==='POST'),false,'Opening history performs no model calls or writes');
  await React.act(async()=>{window.location.hash=`#chat?conversation=${first.id}`;});
  await wait(()=>title()===first.title,'Exact conversation hash navigation works');
  assert.equal(requests.some(item=>item.path==='/api/chat'),false);
  await change(document.querySelector('.chat-input'),'Draft survives settings');
  await nav('Documents');await clickLink(link(first.id));
  assert.equal(window.location.hash,`#chat?conversation=${first.id}`,'Active-row return repairs the canonical route');
  const previousHash=window.location.hash;await click(button('Account and settings'));
  assert.equal(button('Account and settings').getAttribute('aria-current'),'page');
  await click(button('Back to workspace'));assert.equal(window.location.hash,previousHash);
  assert.equal(document.querySelector('.chat-input').value,'Draft survives settings');
  assert.equal(document.querySelector('[data-feature="chat"]').getAttribute('data-conversation-id'),first.id);
  assert.ok(document.querySelector('.wb-topbar nav[aria-label="Workspace navigation"]'));
  assert.equal(document.querySelector('.wb-center nav[aria-label="Workspace navigation"]'),null);
  app.withDatabase(db=>db.prepare('DELETE FROM conversations WHERE id=?').run(second.id));
  await clickLink(link(second.id));
  await wait(()=>document.body.textContent.includes('This conversation could not be loaded.'),'Stale exact target is visibly unavailable');
  assert.equal(document.querySelector('[data-feature="chat"]').getAttribute('data-conversation-id'),second.id);
  await change(document.querySelector('.chat-input'),'Must not create a replacement thread');
  assert.equal(button('Send').disabled,true);
  await React.act(async()=>{document.querySelector('.chat-composer').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));document.querySelector('.chat-input').dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));});
  await flush();assert.equal(requests.some(item=>item.method==='POST'),false,'Unavailable exact targets cannot silently create or send');
  await React.act(async()=>{window.location.hash='#chat?conversation=11111111-1111-4111-8111-111111111111';});
  await wait(()=>document.body.textContent.includes('This conversation is unavailable to this account.'),'Unknown link is rejected');
  assert.equal(document.querySelector('.wb-center > section[aria-label="Conversation"]').hidden,true,'Unknown route hides the unrelated active composer');
  await click(button('New conversation'));
  assert.equal(document.body.textContent.includes('This conversation is unavailable to this account.'),false,'Explicit New clears obsolete route errors');
  assert.equal(document.querySelector('[data-feature="chat"]').hasAttribute('data-conversation-id'),false);

});

for(const indexMode of ['other','empty'])test(`same-user pending reply stays accessible when the global index is ${indexMode} and its original conversation is missing`, {timeout:30000}, async context => {
  const app=await startBrowserFixture({legacyUsers:['synthetic-title-refresh']});
  const realFetch=globalThis.fetch;
  const login=await realFetch(app.origin+'/api/login',{method:'POST',headers:{Origin:app.origin,'Content-Type':'application/json'},body:JSON.stringify({username:'synthetic-title-refresh',password:'Case26'})});
  assert.equal(login.status,200);const session=await login.json(),cookie=login.headers.get('set-cookie').split(';')[0];
  const seed=async(path,body)=>{const response=await realFetch(app.origin+path,{method:'POST',headers:{Origin:app.origin,Cookie:cookie,'Content-Type':'application/json','X-CSRF-Token':session.csrfToken},body:JSON.stringify(body)});assert.equal(response.status,201);return response.json();};
  const {case:record}=await seed('/api/cases',newCasePayload('Synthetic original title'));
  const {conversation:first}=await seed(`/api/cases/${record.id}/conversations`,{title:'Synthetic conversation to preserve'});
  const {case:other}=await seed('/api/cases',newCasePayload('Synthetic second case'));
  const {conversation:second}=await seed(`/api/cases/${other.id}/conversations`,{title:'Second conversation title'});
  const dom=new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>',{url:app.origin+`/#chat?conversation=${first.id}`,pretendToBeVisual:true});
  const originals=new Map(),set=(key,value)=>{originals.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});};
  for(const key of ['window','document','navigator','HTMLElement','Element','Node','MutationObserver','Event','MouseEvent'])set(key,dom.window[key]);
  set('getComputedStyle',dom.window.getComputedStyle.bind(dom.window));set('IS_REACT_ACT_ENVIRONMENT',true);set('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});
  dom.window.confirm=()=>true;dom.window.HTMLElement.prototype.scrollIntoView=function(){};
  const requests=[];
  let releaseInitialStatus, holdInitialStatus=true;
  const initialStatusGate=new Promise(resolve=>{releaseInitialStatus=resolve;});
  set('fetch',async(path,options={})=>{const response=await realFetch(app.origin+path,{...options,headers:{...options.headers,Origin:app.origin,Cookie:cookie}});requests.push({path,method:options.method||'GET',status:response.status});if(path==='/api/status'&&holdInitialStatus){holdInitialStatus=false;await initialStatusGate;}if(path==='/api/status')return new Response(JSON.stringify({...await response.json(),liveEnabled:true}),{status:response.status,headers:{'Content-Type':'application/json'}});return response;});
  const React=await import('react'),{createRoot}=await import('react-dom/client');
  const vite=await createServer({server:{middlewareMode:true,hmr:false,ws:false,watch:null},logLevel:'error'});
  const {SessionProvider}=await vite.ssrLoadModule('/lib/session.jsx'),{default:App}=await vite.ssrLoadModule('/App.jsx');
  const root=createRoot(document.getElementById('root'));
  context.after(async()=>{await React.act(async()=>root.unmount());await vite.close();dom.window.close();for(const[key,descriptor]of originals){if(descriptor)Object.defineProperty(globalThis,key,descriptor);else delete globalThis[key];}await app.stop();});
  const flush=async()=>React.act(async()=>new Promise(resolve=>setTimeout(resolve,10)));
  const wait=async(predicate,label)=>{for(let end=Date.now()+5000;!predicate();){if(Date.now()>end)throw new Error(label);await flush();}};
  const button=(label,scope=document)=>[...scope.querySelectorAll('button')].find(node=>!node.closest('[hidden]')&&(node.textContent.trim()===label||node.getAttribute('aria-label')===label));
  const click=async node=>{assert.ok(node,'Expected button');assert.equal(node.disabled,false);await React.act(async()=>node.click());await flush();};
  const change=async(node,value)=>{assert.ok(node,'Expected input');await React.act(async()=>{const proto=node.tagName==='TEXTAREA'?dom.window.HTMLTextAreaElement.prototype:node.tagName==='SELECT'?dom.window.HTMLSelectElement.prototype:dom.window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(node,value);node.dispatchEvent(new dom.window.Event(node.tagName==='SELECT'?'change':'input',{bubbles:true}));});await flush();};
  const input=label=>{const node=[...document.querySelectorAll('label')].find(node=>!node.closest('[hidden]')&&node.textContent===label);return node&&document.getElementById(node.htmlFor);};
  const nav=async label=>{await wait(()=>{const scope=document.querySelector('nav[aria-label="Workspace navigation"]');return scope&&button(label,scope);},'Authenticated navigation ready');await click(button(label,document.querySelector('nav[aria-label="Workspace navigation"]')));};
  const title=()=>document.querySelector('.chat-toolbar [data-slot="card-title"]')?.textContent;
  app.withDatabase(db=>{db.prepare('DELETE FROM conversations WHERE id=?').run(first.id);if(indexMode==='empty')db.prepare('DELETE FROM conversations WHERE id=?').run(second.id);});
  const {draftVault}=await vite.ssrLoadModule('/lib/draft-vault.js'),workspace=crypto.randomUUID();
  draftVault.verifyUser(session.userId);
  assert.equal(draftVault.write({userId:session.userId,workspaceKey:'active',feature:'workspace'},{caseId:record.id,view:'chat',workspaceKey:workspace}),true);
  assert.equal(draftVault.write({userId:session.userId,workspaceKey:workspace,feature:'chat'},{input:'Newer restored draft',conversationId:first.id,pendingTurn:{userMessageId:crypto.randomUUID(),clientMessageId:crypto.randomUUID(),question:'Synthetic pending question',assistantMessageId:crypto.randomUUID(),reply:'Received unconfirmed reply must remain visible.',requestId:crypto.randomUUID()}}),true);
  draftVault.suspend(session.userId);
  await React.act(async()=>root.render(React.createElement(SessionProvider,null,React.createElement(App))));
  await wait(()=>button('Switch interface to English'),'App loaded');await click(button('Switch interface to English'));releaseInitialStatus();
  await wait(()=>button('Retry opening this conversation')&&!button('Retry opening this conversation').disabled,'Original missing scope is recoverable');
  const chat=()=>document.querySelector('[data-feature="chat"]'),visibleChat=()=>!document.querySelector('.wb-center > section[aria-label="Conversation"]').hidden;
  assert.equal(visibleChat(),true);assert.match(chat().textContent,/Received unconfirmed reply must remain visible/);
  assert.equal(document.querySelector('.chat-toolbar select').value,first.id,'Missing current placeholder survives an empty or unrelated account index');
  assert.equal(document.querySelector('.chat-input').value,'Newer restored draft');assert.equal(button('Send').disabled,true);assert.ok(button('Copy reply'));
  await React.act(async()=>{document.querySelector('.chat-input').dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));document.querySelector('.chat-composer').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));});await flush();
  assert.equal(requests.some(item=>item.method==='POST'),false);
  const reads=requests.filter(item=>item.path===`/api/conversations/${first.id}`).length;
  await click(button('Retry opening this conversation'));await wait(()=>requests.filter(item=>item.path===`/api/conversations/${first.id}`).length>reads,'Read-only retry remains scoped to original');
  assert.match(chat().textContent,/Received unconfirmed reply must remain visible/);assert.equal(document.querySelector('.chat-toolbar select').value,first.id);
  await React.act(async()=>{window.location.hash='#chat?conversation=11111111-1111-4111-8111-111111111111';});await wait(()=>!visibleChat(),'Unrelated unknown link does not expose this recovery');
  await React.act(async()=>{window.location.hash=`#chat?conversation=${first.id}`;});await wait(visibleChat,'Returning to the cached original exposes its unconfirmed copy');
  assert.equal(button('Send').disabled,true);assert.equal(requests.some(item=>item.method==='POST'),false);
});
