// Actual React DOM events + local HTTP + SQLite. Seeded synthetic conversation,
// not a model/provider, browser rendering, CSP, accessibility, or deployment claim.
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, realpath, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomBytes, randomUUID, scryptSync } from 'node:crypto';
import { spawn } from 'node:child_process';
import net from 'node:net';
import { JSDOM } from 'jsdom';
import { createServer } from 'vite';
import { openStorage } from '../../../storage.js';
import { conversationDraft } from '../../lib/conversation-handoff.js';

test('chat bridges a persisted conversation into append-only review and the real final-document flow without losing unsaved work', {timeout:45000}, async context => {
  const directory = await mkdtemp(join(await realpath(tmpdir()), 'nestlet-chat-bridge-'));
  const filename = join(directory, 'case.sqlite'), storage = openStorage({filename});
  const confirmedAt = new Date().toISOString(), confirmed = value => ({value,source:'Authored synthetic fixture reviewed by test operator',confirmed:true,confirmedAt,notApplicable:false,sourceMessageId:null});
  const record = storage.createCase('owner', {title:'Synthetic conversational workflow',sourceText:'Original source preserved',draftType:'followup',draftText:'',fields:['property','owner','pha','caseReference','rent'].map(key=>({key,value:key==='property'?'128 Synthetic Lane':key==='owner'?'Synthetic Owner LLC':'',source:'Synthetic confirmed source',confirmed:true,conflict:false})),documentContext:{recipientName:confirmed('Synthetic Intake Team'),recipientContact:confirmed('intake@example.invalid'),senderName:confirmed('Synthetic Sender')}});
  const conversation = storage.createConversation('owner',record.id,{title:'Synthetic saved conversation'});
  storage.appendMessage('owner',conversation.id,{role:'user',content:'Please review this proposed property update.',state:'complete'});
  const answer = storage.appendMessage('owner',conversation.id,{role:'assistant',content:'Property: 999 Unreviewed Proposal Lane\nThis is an authored synthetic assistant fixture, not live model output.',state:'complete'});
  const uncertainAnswer = storage.appendMessage('owner',conversation.id,{role:'assistant',content:'Synthetic answer whose durable save response will be deliberately dropped.',state:'complete'});
  const cancelAnswer = storage.appendMessage('owner',conversation.id,{role:'assistant',content:'Synthetic answer for cancellation and stale-case verification.',state:'complete'});
  const chineseAnswer = storage.appendMessage('owner',conversation.id,{role:'assistant',content:'这是未核实的中文建议。',state:'complete'});
  const otherCase = storage.createCase('owner',{title:'Second synthetic bridge case',sourceText:'Other case material',fields:[],draftType:'followup',draftText:''});
  storage.appendMessage('owner',conversation.id,{role:'assistant',content:'Incomplete proposal must have no workflow actions.',state:'interrupted'});
  storage.close();
  const password='public-chat-bridge-fixture-only',salt=randomBytes(16),hash=`scrypt$${salt.toString('base64url')}$${scryptSync(password,salt,32).toString('base64url')}`;
  const reservation=net.createServer(); await new Promise(resolve=>reservation.listen(0,'127.0.0.1',resolve)); const port=reservation.address().port; await new Promise(resolve=>reservation.close(resolve));
  const origin=`http://127.0.0.1:${port}`;
  let child;
  const start = async () => {
    child=spawn(process.execPath,['server.js'],{cwd:new URL('../../../',import.meta.url),env:{...process.env,HOST:'127.0.0.1',PORT:String(port),PUBLIC_ORIGIN:'',NESTLET_DB_PATH:filename,NESTLET_ASSETS_PATH:join(directory,'assets'),NESTLET_OPERATOR_USERNAME:'owner',NESTLET_OPERATOR_PASSWORD_HASH:hash,DEEPSEEK_API_KEY:'',ENABLE_LIVE_AI:'false',DEEPSEEK_MODEL:'deepseek-flash'},stdio:['ignore','pipe','pipe']});
    let output='';child.stdout.on('data',value=>output+=value);child.stderr.on('data',value=>output+=value);
    await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(output)),5000);child.once('exit',code=>{clearTimeout(timer);reject(new Error(`Server exited ${code}`));});child.stdout.on('data',value=>{if(value.toString().includes('Nestlet available')){clearTimeout(timer);resolve();}});});
  };
  const stop = async () => {if(child?.exitCode===null){const stopped=new Promise(resolve=>child.once('exit',resolve));child.kill('SIGTERM');await stopped;}};
  await start();
  const realFetch=globalThis.fetch;
  let cookie;
  const login=async()=>{const response=await realFetch(origin+'/api/login',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({password})});assert.equal(response.status,200);cookie=response.headers.get('set-cookie').split(';')[0];return response.json();};
  const session = await login();
  const read=async path=>{const response=await realFetch(origin+path,{headers:{Cookie:cookie}});assert.equal(response.status,200,path);return response.json();};
  const dom=new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>',{url:origin,pretendToBeVisual:true});
  const originals=new Map(),set=(key,value)=>{originals.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});};
  for(const key of ['window','document','navigator','HTMLElement','Element','Node','MutationObserver','Event','MouseEvent'])set(key,dom.window[key]);
  set('getComputedStyle',dom.window.getComputedStyle.bind(dom.window));set('IS_REACT_ACT_ENVIRONMENT',true);set('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});
  dom.window.confirm=()=>true;dom.window.HTMLElement.prototype.scrollIntoView=function(){};dom.window.matchMedia=()=>({matches:false});
  const requests=[];
  let dropDraftResponse = false, heldHistory = null, conflictDraft = false;
  set('fetch',async(path,options={})=>{
    if (conflictDraft && options.method === 'POST' && path.endsWith('/artifacts')) {
      conflictDraft = false;
      const latest = (await read(`/api/cases/${record.id}`)).case;
      const updated = await realFetch(origin+`/api/cases/${record.id}`,{method:'PUT',headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json','X-CSRF-Token':session.csrfToken},body:JSON.stringify({title:latest.title+' updated elsewhere',sourceText:latest.sourceText,fields:latest.fields,draftType:latest.draftType,draftText:latest.draftText,extractionMode:latest.extractionMode,namesVerified:latest.namesVerified,clientId:latest.clientId,expectedVersion:latest.version})});
      assert.equal(updated.status,200,'Actual concurrent case update succeeded');
    }
    const response=await realFetch(origin+path,{...options,headers:{...options.headers,Origin:origin,Cookie:cookie}});
    requests.push({path,method:options.method||'GET',body:options.body,status:response.status});
    if (heldHistory && path===`/api/conversations/${conversation.id}`) { const gate=heldHistory; heldHistory=null; gate.received=true; await gate.promise; }
    if(dropDraftResponse && options.method==='POST' && path.endsWith('/artifacts')) {dropDraftResponse=false;const actualBody=await response.text();return new Response(actualBody.slice(0,10),{status:response.status,headers:response.headers});}
    return response;
  });
  const vite=await createServer({server:{middlewareMode:true,hmr:false,ws:false,watch:null},logLevel:'error'});
  const React=await import('react'),{createRoot}=await import('react-dom/client');
  const {SessionProvider}=await vite.ssrLoadModule('/lib/session.jsx'),{default:App}=await vite.ssrLoadModule('/App.jsx'),{draftVault}=await vite.ssrLoadModule('/lib/draft-vault.js');
  draftVault.verifyUser('owner');draftVault.write({userId:'owner',workspaceKey:'active',feature:'workspace'},{caseId:record.id,view:'chat',workspaceKey:randomUUID()});
  let root=createRoot(document.getElementById('root'));
  context.after(async()=>{if(root)await React.act(async()=>root.unmount());await vite.close();dom.window.close();for(const[key,descriptor]of originals){if(descriptor)Object.defineProperty(globalThis,key,descriptor);else delete globalThis[key];}await stop();await rm(directory,{recursive:true,force:true});});
  const flush=async()=>React.act(async()=>new Promise(resolve=>setTimeout(resolve,10)));
  const wait=async(predicate,label)=>{for(let end=Date.now()+6000;!predicate();){if(Date.now()>end)throw new Error(`${label}: ${document.body.textContent}`);await flush();}};
  const visible=node=>!node.closest('[hidden]');
  const button=(label,container=document)=>[...container.querySelectorAll('button')].find(node=>visible(node)&&(node.textContent.trim()===label||node.getAttribute('aria-label')===label));
  const click=async node=>{assert.ok(node,'Expected button');assert.equal(node.disabled,false,node.textContent);await React.act(async()=>node.click());await flush();};
  const fill=async(node,value)=>{assert.ok(node,'Expected input');await React.act(async()=>{const proto=node.tagName==='TEXTAREA'?dom.window.HTMLTextAreaElement.prototype:dom.window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(node,value);node.dispatchEvent(new dom.window.Event('input',{bubbles:true}));});await flush();};
  const labeled=label=>{const item=[...document.querySelectorAll('label')].find(node=>visible(node)&&node.textContent===label);return item&&document.getElementById(item.htmlFor);};
  const nav=async label=>click(button(label,document.querySelector('nav[aria-label="Workspace navigation"]')));
  const checkRead=async path=>{let result;await React.act(async()=>{result=await read(path);});return result;};
  await React.act(async()=>root.render(React.createElement(SessionProvider,null,React.createElement(App))));
  await wait(()=>button('Switch interface to English'),'App loaded');await click(button('Switch interface to English'));
  await wait(()=>document.querySelector('[data-testid="chat-case-workflow"]')?.textContent.includes('sender contact'),'Readiness loaded');
  const workflow=document.querySelector('[data-testid="chat-case-workflow"]');
  const questions=[...workflow.querySelectorAll('details')].find(node=>node.querySelector('summary')?.textContent.startsWith('Full questions'));
  assert.ok(questions,'Compact sidebar retains full missing questions behind a disclosure');assert.equal(questions.open,false);assert.match(questions.textContent,/sender contact/);
  assert.match(workflow.textContent,/128 Synthetic Lane/);assert.doesNotMatch(workflow.textContent,/Please provide the property/);assert.match(workflow.textContent,/sender contact/);
  await wait(()=>document.querySelectorAll('[data-testid="chat-message-actions"]').length===5,'Persisted actions loaded');
  const assistant=()=>[...document.querySelectorAll('article[aria-label="Assistant"]')].find(item=>item.textContent.includes(answer.content));
  const interrupted=[...document.querySelectorAll('article[aria-label="Assistant"]')].find(item=>item.textContent.includes('Incomplete proposal'));
  assert.equal(interrupted.querySelector('[data-testid="chat-message-actions"]'),null);
  await fill(document.querySelector('.chat-input'),'Unsent question survives the workflow');
  await nav('Materials & facts');await wait(()=>labeled('Case source text')?.value==='Original source preserved','Material loaded');
  await fill(labeled('Case source text'),'Locally edited material remains');await nav('Conversation');
  await click(button('Review for this case',assistant()));await wait(()=>button('Cancel text handoff'),'Review handoff');
  assert.equal(labeled('Case source text').value,'Locally edited material remains');
  await click(button('Cancel text handoff'));assert.equal(labeled('Case source text').value,'Locally edited material remains');
  await nav('Conversation');await click(button('Review for this case',assistant()));await click(button('Append unreviewed text'));
  assert.match(labeled('Case source text').value,/^Locally edited material remains\n\nUNREVIEWED AI RESPONSE/);
  assert.match(labeled('Case source text').value,new RegExp(answer.id));
  assert.equal(labeled('Property address').value,'128 Synthetic Lane');
  assert.equal(document.querySelector('[id$="-property-confirm"]').getAttribute('data-state'),'checked');
  assert.equal(requests.some(item=>item.method==='PATCH'),false,'Handoff never confirms any facts');
  await nav('Conversation');assert.equal(document.querySelector('.chat-input').value,'Unsent question survives the workflow');
  await click(button('Finish and preview English document'));await wait(()=>button('Save case'),'Pending material returned before generation');
  await click(button('Save case'));await wait(()=>requests.some(item=>item.method==='PUT'&&item.status===200)&&!button('Save case').disabled,'Case saved');
  const savedCase=(await checkRead(`/api/cases/${record.id}`)).case;
  assert.match(savedCase.sourceText,/UNREVIEWED AI RESPONSE/);assert.equal(savedCase.fields.find(field=>field.key==='property').value,'128 Synthetic Lane');
  await nav('Conversation');await click(button('Finish and preview English document'));await wait(()=>labeled('Sender contact')&&!button('Save answers & generate final').disabled,'Document questions loaded');
  assert.equal(document.getElementById('document-answer-property'),null,'Known confirmed property is not asked again');
  await fill(labeled('Sender contact'),'sender@example.invalid');await click(button('Save answers & generate final'));
  await wait(()=>document.getElementById('document-body')?.value.includes('128 Synthetic Lane')&&!button('Save new version').disabled,'Final generated and persisted');
  const finalText=document.getElementById('document-body').value;
  assert.doesNotMatch(finalText,/999 Unreviewed|TBD|\[insert/i);
  let artifacts=(await checkRead(`/api/cases/${record.id}/artifacts`)).artifacts;
  assert.equal(artifacts.length,1);assert.equal(artifacts[0].status,'final');
  const finalId=artifacts[0].id;
  await nav('Conversation');assert.equal(document.querySelector('.chat-input').value,'Unsent question survives the workflow');
  const save=button('Save answer as unreviewed draft',assistant());
  await React.act(async()=>{save.click();save.click();});await wait(()=>assistant().textContent.includes('Unreviewed draft saved:'),'Draft saved');
  artifacts=(await checkRead(`/api/cases/${record.id}/artifacts`)).artifacts;
  assert.equal(artifacts.length,2,'Double activation creates one draft');
  const metadata=artifacts.find(item=>item.status==='draft'),draft=(await checkRead(`/api/artifacts/${metadata.id}`)).artifact;
  assert.equal(draft.content,conversationDraft(answer));assert.equal(draft.sourceMessageId,answer.id);assert.equal(draft.sourceConversationId,conversation.id);assert.equal(draft.status,'draft');
  assert.equal((await checkRead(`/api/artifacts/${finalId}`)).artifact.content,finalText);
  assert.equal((await checkRead(`/api/cases/${record.id}`)).case.fields.find(field=>field.key==='property').value,'128 Synthetic Lane');
  await click(button('Open case document versions',assistant()));
  await wait(()=>document.querySelector(`[data-artifact-id="${draft.id}"]`),'Version list refreshed');
  await click(button('Open',document.querySelector(`[data-artifact-id="${draft.id}"]`)));
  await wait(()=>document.getElementById('document-body')?.value===draft.content,'Saved draft preview');
  await fill(document.getElementById('document-body'),draft.content+'\nUnsaved human document edit');await nav('Conversation');
  await click(button('Finish and preview English document'));await wait(()=>document.getElementById('document-body')?.value.endsWith('Unsaved human document edit'),'Pending document draft preserved');
  assert.equal(requests.filter(item=>item.path==='/api/chat'||item.path==='/api/extract').length,0,'No provider or extraction request');
  assert.equal(requests.filter(item=>item.path===`/api/cases/${record.id}/artifacts`&&item.method==='POST').length,1,'One explicit draft POST');
  await nav('Conversation');
  const articleFor = item => [...document.querySelectorAll('article[aria-label="Assistant"]')].find(node=>node.textContent.includes(item.content));
  await click(button('Save answer as unreviewed draft',articleFor(chineseAnswer)));
  await wait(()=>articleFor(chineseAnswer).textContent.includes('Keep the document body in English'),'Chinese proposal rejected before draft write');
  assert.equal(requests.filter(item=>item.path===`/api/cases/${record.id}/artifacts`&&item.method==='POST').length,1);
  dropDraftResponse=true;
  await click(button('Save answer as unreviewed draft',articleFor(uncertainAnswer)));
  await wait(()=>button('Check saved draft status',articleFor(uncertainAnswer)),'Lost response is visibly uncertain');
  assert.equal(button('Save answer as unreviewed draft',articleFor(uncertainAnswer)),undefined,'No blind POST retry offered');
  await click(button('Check saved draft status',articleFor(uncertainAnswer)));
  await wait(()=>articleFor(uncertainAnswer).textContent.includes('Unreviewed draft saved:'),'Uncertain save reconciled against actual stored version');
  assert.equal((await checkRead(`/api/cases/${record.id}/artifacts`)).artifacts.length,3);
  assert.equal(requests.filter(item=>item.path===`/api/cases/${record.id}/artifacts`&&item.method==='POST').length,2);
  const gate=()=>{let resolve;return {promise:new Promise(done=>resolve=done),resolve:()=>resolve(),received:false};};
  const cancellation=gate();heldHistory=cancellation;
  await click(button('Save answer as unreviewed draft',articleFor(cancelAnswer)));
  await wait(()=>cancellation.received,'Actual history response delayed');
  await click(button('Cancel draft action',articleFor(cancelAnswer)));await React.act(async()=>{cancellation.resolve();});
  await wait(()=>!button('Save answer as unreviewed draft',articleFor(cancelAnswer)).disabled,'Cancelled request released');
  assert.equal(requests.filter(item=>item.path===`/api/cases/${record.id}/artifacts`&&item.method==='POST').length,2,'Cancel before POST creates no artifact');
  conflictDraft=true;
  await click(button('Save answer as unreviewed draft',articleFor(cancelAnswer)));
  await wait(()=>articleFor(cancelAnswer).textContent.includes('case changed elsewhere'),'Actual version conflict shown');
  assert.equal((await checkRead(`/api/cases/${record.id}/artifacts`)).artifacts.length,3,'409 does not write another version');
  const stale=gate();heldHistory=stale;
  await click(button('Save answer as unreviewed draft',articleFor(cancelAnswer)));
  await wait(()=>stale.received,'Old case response delayed');
  await nav('Customers');await wait(()=>button('Open saved case: '+otherCase.title),'Other saved case listed');
  await click(button('Open saved case: '+otherCase.title));await React.act(async()=>{stale.resolve();});
  await wait(()=>document.querySelector('.chat-toolbar [data-slot="card-title"]')?.textContent==='Conversation' && !document.querySelector('.chat-toolbar select').value,'New case remains selected');
  assert.doesNotMatch(document.querySelector('[data-feature="chat"]').textContent,/999 Unreviewed|Cancellation and stale|Unreviewed draft saved:/);
  assert.equal((await checkRead(`/api/cases/${otherCase.id}/artifacts`)).artifacts.length,0);
  assert.equal((await checkRead(`/api/cases/${record.id}/artifacts`)).artifacts.length,3,'Late old-case response cannot save');
  await React.act(async()=>root.unmount());root=null;
  await stop();await start();await login();
  const reopened=(await checkRead(`/api/cases/${record.id}`)).case;
  assert.equal(reopened.fields.find(field=>field.key==='property').value,'128 Synthetic Lane');assert.match(reopened.sourceText,/UNREVIEWED AI RESPONSE/);
  assert.equal((await checkRead(`/api/artifacts/${draft.id}`)).artifact.content,draft.content);
  assert.equal((await checkRead(`/api/artifacts/${finalId}`)).artifact.content,finalText);
  assert.equal((await checkRead(`/api/conversations/${conversation.id}`)).messages.find(item=>item.id===answer.id).content,answer.content);
});
