export const COPY = {
  zh: {
    remember:'记住账号并保持登录 8 小时', showPassword:'显示密码', hidePassword:'隐藏密码',
    account:'账号', signedIn:'已登录', signedInHint:'继续处理自己的客户、案件和文档', ordinary:'普通账号', administrator:'管理员',
    login:'登录', register:'注册', loginTitle:'回到你的工作区', registerTitle:'创建自己的工作区',
    loginHint:'使用用户名登录，继续上次保存的工作', registerHint:'注册后只可访问自己的客户、案件、对话和文档',
    username:'用户名', usernamePlaceholder:'输入用户名', usernameHint:'3–64 个英文字母、数字、点、下划线或连字符；首位为字母或数字',
    password:'密码', passwordHint:'6–256 个字符；建议使用独立且较长的密码', confirmPassword:'确认密码',
    loginBusy:'正在登录…', registerBusy:'正在注册…', loading:'正在读取账号状态…', retry:'重新读取状态',
    authUnavailable:'暂时无法读取账号状态，请重试', setupTitle: "请设置管理员账号",
    setupHint: "请联系管理员完成账号设置后登录。",
    insecureLogin: "请通过 HTTPS 地址登录。",
    registrationUnavailable: "请使用已有账号登录。",
    signOut:'退出', signOutBusy:'正在退出…', signOutTitle:'退出当前账号？',
    signOutWarning:'请先保存未完成的修改。退出将清空当前页面中未保存的输入', cancel:'取消', confirmSignOut:'确认退出',
    settingsTitle:'服务设置', providerTitle:'DeepSeek 连接', configured: "已配置", notConfigured: "未配置", enabled: "已启用", paused: "已暂停",
    connection:'连接验证', notVerified: "待验证", verified: "上次验证",
    memoryStorage: "服务重启后需重新填写 API Key。",
    environmentStorage: "已使用服务器配置的 API Key。",
    keyLabel:'输入或替换 API Key', keyPlaceholder:'留空保留当前 Key',
    keyHint: "留空可保留现有 API Key。",
    liveLabel:'启用 AI', liveHint: "开启后可使用 AI 对话与材料提取。",
    discard:'取消修改', save:'保存设置', saving:'正在保存…', saved: "设置已保存",
    test:'验证模型权限', testing:'正在验证…', tested: "模型访问权限验证通过",
    saveBeforeTest:'有未保存的修改，请先保存再验证', secureSettingsRequired: "请通过 HTTPS 地址修改设置。",
    refreshing:'正在刷新…', refresh:'刷新状态', refreshFailed: "无法刷新状态，请重试。",
  },
  en: {
    remember:'Remember me for 8 hours', showPassword:'Show password', hidePassword:'Hide password',
    account:'Account', signedIn:'Signed in', signedInHint:'Continue with your own customers, cases, and documents', ordinary:'Ordinary account', administrator:'Administrator',
    login:'Sign in', register:'Register', loginTitle:'Return to your workspace', registerTitle:'Create your workspace',
    loginHint:'Sign in with your username to continue saved work', registerHint:'Your customers, cases, conversations, and documents stay scoped to your account',
    username:'Username', usernamePlaceholder:'Enter your username', usernameHint:'3–64 letters, numbers, dots, underscores, or hyphens; start with a letter or number',
    password:'Password', passwordHint:'6–256 characters; a unique, longer password is recommended', confirmPassword:'Confirm password',
    loginBusy:'Signing in…', registerBusy:'Registering…', loading:'Reading account status…', retry:'Retry account status',
    authUnavailable:'Account status is unavailable. Please retry', setupTitle: "Set up an administrator account",
    setupHint: "Contact your administrator to complete account setup.",
    insecureLogin: "Use the HTTPS address to sign in.",
    registrationUnavailable: "Sign in with an existing account.",
    signOut:'Sign out', signOutBusy:'Signing out…', signOutTitle:'Sign out of this account?',
    signOutWarning:'Save unfinished changes first. Signing out clears unsaved input from this page', cancel:'Cancel', confirmSignOut:'Confirm sign out',
    settingsTitle:'Service settings', providerTitle:'DeepSeek connection', configured: "Configured", notConfigured: "Not configured", enabled: "Enabled", paused: "Paused",
    connection:'Connection check', notVerified: "Not checked", verified: "Last checked",
    memoryStorage: "Re-enter the API key after a service restart.",
    environmentStorage: "Using the server API key.",
    keyLabel:'Enter or replace the API key', keyPlaceholder:'Leave blank to keep the current key',
    keyHint: "Leave blank to keep the current API key.",
    liveLabel:'Enable AI', liveHint: "Enable AI chat and material extraction.",
    discard:'Discard changes', save:'Save settings', saving:'Saving…', saved: "Settings saved",
    test:'Verify model access', testing:'Verifying…', tested: "Model access verified",
    saveBeforeTest:'Save pending changes before verifying model access', secureSettingsRequired: "Use the HTTPS address to update settings.",
    refreshing:'Refreshing…', refresh:'Refresh status', refreshFailed: "Could not refresh the status. Try again.",
  },
};
const ERRORS = {
  zh: {
    AUTH_USERNAME_REQUIRED:'请输入用户名', AUTH_USERNAME_INVALID:'用户名格式不正确，请按下方规则输入', AUTH_USERNAME_RESERVED:'该用户名不可用于注册，请选择其他用户名',
    PASSWORD_LENGTH:'密码须为 6–256 个字符', PASSWORD_CONTROL:'密码不能包含控制字符', PASSWORD_MISMATCH:'两次输入的密码不一致',
    INVALID_CREDENTIALS:'用户名或密码不正确', LOGIN_RATE_LIMITED:'登录尝试过多，请稍后再试', REGISTRATION_RATE_LIMITED:'注册尝试过多，请等待十分钟后重试',
    REGISTRATION_INVALID:'无法注册，请核对用户名和两次密码', USER_INVALID:'该用户名不可用，请重新选择', USER_EXISTS:'该用户名已被使用，请选择其他用户名', USER_LIMIT_REACHED:'当前账号名额已满，请联系管理员',
    OPERATOR_SETUP_REQUIRED:'管理员尚未完成初始化，暂时不能使用此功能', HTTPS_REQUIRED:'请通过已配置的 HTTPS 地址操作',
    AUTH_REQUIRED:'登录已失效，请重新登录', CSRF_REJECTED:'会话状态已变化，请刷新状态后重试', ORIGIN_REJECTED:'当前访问地址与服务器配置不符，请使用正确的站点地址', OWNER_REQUIRED:'此操作只允许管理员执行',
    API_KEY_REQUIRED:'开启模型请求前，请先配置 Key', API_KEY_INVALID:'Key 格式不正确，请检查后重新输入', INVALID_SETTINGS:'请检查设置内容后重试',
    SETTINGS_RATE_LIMITED:'设置操作过于频繁，请等待一分钟后重试', CONNECTION_FAILED:'连接验证失败，请检查 Key、账户权限和网络', MODEL_UNAVAILABLE:'此账号未返回 deepseek-flash 模型权限，请检查服务账户', SETTINGS_CHANGED:'验证期间设置已变化，请重新验证当前设置', BUSY:'已有操作正在进行，请稍后重试',
    NETWORK_ERROR:'网络连接失败，请检查连接后重试', INVALID_RESPONSE:'服务器响应无法读取，请稍后重试', REQUEST_FAILED:'操作未完成，请重试；请勿在错误反馈中发送密码或 Key',
  },
  en: {
    AUTH_USERNAME_REQUIRED:'Enter a username', AUTH_USERNAME_INVALID:'The username format is invalid. Follow the rules below', AUTH_USERNAME_RESERVED:'This username cannot be registered. Choose another',
    PASSWORD_LENGTH:'Use 6–256 password characters', PASSWORD_CONTROL:'Control characters are not allowed in passwords', PASSWORD_MISMATCH:'The passwords do not match',
    INVALID_CREDENTIALS:'The username or password is incorrect', LOGIN_RATE_LIMITED:'Too many sign-in attempts. Try again shortly', REGISTRATION_RATE_LIMITED:'Too many registration attempts. Wait ten minutes before retrying',
    REGISTRATION_INVALID:'Registration failed. Check the username and both passwords', USER_INVALID:'This username is unavailable. Choose another', USER_EXISTS:'This username is already in use. Choose another', USER_LIMIT_REACHED:'The account limit has been reached. Contact the administrator',
    OPERATOR_SETUP_REQUIRED:'Administrator setup must be completed before this feature is available', HTTPS_REQUIRED:'Use the configured HTTPS address',
    AUTH_REQUIRED:'Your sign-in has expired. Sign in again', CSRF_REJECTED:'Session state changed. Refresh status and retry', ORIGIN_REJECTED:'This address does not match the server configuration. Use the correct site address', OWNER_REQUIRED:'Only the administrator can perform this action',
    API_KEY_REQUIRED:'Configure a key before enabling model requests', API_KEY_INVALID:'The key format is invalid. Check it and enter it again', INVALID_SETTINGS:'Check the settings and try again',
    SETTINGS_RATE_LIMITED:'Too many settings requests. Wait a minute before retrying', CONNECTION_FAILED:'Verification failed. Check the key, account access, and connection', MODEL_UNAVAILABLE:'This account did not list deepseek-flash. Check model access with the provider', SETTINGS_CHANGED:'Settings changed during verification. Verify the current settings again', BUSY:'Another operation is in progress. Try again shortly',
    NETWORK_ERROR:'The network request failed. Check your connection and retry', INVALID_RESPONSE:'The server response could not be read. Please retry', REQUEST_FAILED:'The operation did not complete. Retry without sending passwords or keys in error reports',
  },
};
export const language = lang => lang === 'en' ? 'en' : 'zh';
export const authCopy = lang => COPY[language(lang)];
export function authErrorMessage(error, lang = 'zh') {
  const code = typeof error === 'string' ? error : error?.code;
  return ERRORS[language(lang)][code] || ERRORS[language(lang)].REQUEST_FAILED;
}
