export const COPY = {
  zh: {
    remember:'记住账号并保持登录 8 小时', showPassword:'显示密码', hidePassword:'隐藏密码',
    account:'账号', signedIn:'已登录', signedInHint:'继续处理自己的客户、案件和文档', ordinary:'普通账号', administrator:'管理员',
    login:'登录', register:'注册', loginTitle:'回到你的工作区', registerTitle:'创建自己的工作区',
    loginHint:'使用邮箱登录；已有账号也可继续使用原用户名', registerHint:'先验证邮箱，再登录自己的客户、案件、对话和文档工作区',
    username:'用户名', usernamePlaceholder:'输入用户名', usernameHint:'3–64 个英文字母、数字、点、下划线或连字符；首位为字母或数字',
    password:'密码', passwordHint:'6–256 个字符；建议使用独立且较长的密码', confirmPassword:'确认密码',
    loginBusy:'正在登录…', registerBusy:'正在注册…', loading:'正在读取账号状态…', retry:'重新读取状态',
    authUnavailable:'暂时无法读取账号状态，请重试', setupTitle: "请设置管理员账号",
    setupHint: "请联系管理员完成账号设置后登录。",
    insecureLogin: "请通过 HTTPS 地址登录。",
    registrationUnavailable: "请使用已有账号登录。",
    signOut:'退出', signOutBusy:'正在退出…', signOutTitle:'退出当前账号？',
    signOutWarning:'请先保存未完成的修改。退出将清空当前页面中未保存的输入', cancel:'取消', confirmSignOut:'确认退出',
    settingsTitle:'服务设置', providerTitle:'DeepSeek 连接', configured: "已配置", notConfigured: "未配置", enabled: "已启用", paused: "已暂停",
    connection:'连接验证', notVerified: "待验证", verified: "上次验证",
    memoryStorage: "服务重启后需重新填写 API Key。",
    environmentStorage: "已使用服务器配置的 API Key。",
    keyLabel:'输入或替换 API Key', keyPlaceholder:'留空保留当前 Key',
    keyHint: "留空可保留现有 API Key。",
    liveLabel:'启用 AI', liveHint: "开启后可使用 AI 对话与材料提取。",
    discard:'取消修改', save:'保存设置', saving:'正在保存…', saved: "设置已保存",
    test:'验证模型权限', testing:'正在验证…', tested: "模型访问权限验证通过",
    saveBeforeTest:'有未保存的修改，请先保存再验证', secureSettingsRequired: "请通过 HTTPS 地址修改设置。",
    refreshing:'正在刷新…', refresh:'刷新状态', refreshFailed: "无法刷新状态，请重试。",
  },
  en: {
    remember:'Remember me for 8 hours', showPassword:'Show password', hidePassword:'Hide password',
    account:'Account', signedIn:'Signed in', signedInHint:'Continue with your own customers, cases, and documents', ordinary:'Ordinary account', administrator:'Administrator',
    login:'Sign in', register:'Register', loginTitle:'Return to your workspace', registerTitle:'Create your workspace',
    loginHint:'Sign in with email. Existing accounts can still use their original username', registerHint:'Verify your email, then sign in to your own customers, cases, conversations, and documents',
    username:'Username', usernamePlaceholder:'Enter your username', usernameHint:'3–64 letters, numbers, dots, underscores, or hyphens; start with a letter or number',
    password:'Password', passwordHint:'6–256 characters; a unique, longer password is recommended', confirmPassword:'Confirm password',
    loginBusy:'Signing in…', registerBusy:'Registering…', loading:'Reading account status…', retry:'Retry account status',
    authUnavailable:'Account status is unavailable. Please retry', setupTitle: "Set up an administrator account",
    setupHint: "Contact your administrator to complete account setup.",
    insecureLogin: "Use the HTTPS address to sign in.",
    registrationUnavailable: "Sign in with an existing account.",
    signOut:'Sign out', signOutBusy:'Signing out…', signOutTitle:'Sign out of this account?',
    signOutWarning:'Save unfinished changes first. Signing out clears unsaved input from this page', cancel:'Cancel', confirmSignOut:'Confirm sign out',
    settingsTitle:'Service settings', providerTitle:'DeepSeek connection', configured: "Configured", notConfigured: "Not configured", enabled: "Enabled", paused: "Paused",
    connection:'Connection check', notVerified: "Not checked", verified: "Last checked",
    memoryStorage: "Re-enter the API key after a service restart.",
    environmentStorage: "Using the server API key.",
    keyLabel:'Enter or replace the API key', keyPlaceholder:'Leave blank to keep the current key',
    keyHint: "Leave blank to keep the current API key.",
    liveLabel:'Enable AI', liveHint: "Enable AI chat and material extraction.",
    discard:'Discard changes', save:'Save settings', saving:'Saving…', saved: "Settings saved",
    test:'Verify model access', testing:'Verifying…', tested: "Model access verified",
    saveBeforeTest:'Save pending changes before verifying model access', secureSettingsRequired: "Use the HTTPS address to update settings.",
    refreshing:'Refreshing…', refresh:'Refresh status', refreshFailed: "Could not refresh the status. Try again.",
  },
};
Object.assign(COPY.zh, {
  remember:'保持登录 8 小时', showPassword:'显示密码', hidePassword:'隐藏密码',
  email:'邮箱', emailPlaceholder:'name@example.com', identity:'邮箱或已有用户名', identityPlaceholder:'输入邮箱或已有用户名',
  emailHint:'使用你能收取验证邮件的邮箱；新账号须先验证邮箱', identityHint:'新用户请使用邮箱注册；原有用户名仅用于已有账号登录',
  emailUnavailable:'邮件服务尚未配置或暂不可用，注册、发送验证邮件和邮箱找回暂不能使用。请联系管理员',
  emailPrivacy:'验证链接 10 分钟内有效；重置链接 30 分钟内有效且仅可使用一次。请勿转发链接',
  acceptedTitle:'请查看邮箱（如符合条件）', acceptedHint:'如果此邮箱符合条件，系统会发送相应邮件。此提示不确认账号是否存在，也不保证邮件已送达',
  checkSpam:'请检查收件箱与垃圾邮件。验证成功后，请回到登录页登录',
  resend:'重新发送验证邮件', resendBusy:'正在请求验证邮件…', cooldown:'秒后可重新请求',
  forgot:'忘记密码？', forgotTitle:'找回密码', forgotHint:'输入账号已验证的邮箱。原用户名账号须先登录并绑定邮箱，才可使用邮箱找回',
  requestReset:'请求重置链接', requestBusy:'正在提交…', backToLogin:'返回登录', changeEmail:'修改邮箱',
  verifyTitle:'验证你的邮箱', verifyHint:'请确认要验证此邮箱。打开此页面不会自动使用链接；点击下方按钮才会提交验证',
  verify:'确认验证邮箱', verifyBusy:'正在验证…', verified:'邮箱验证成功。新账号现在可以登录；已有账号可刷新账户状态',
  resetTitle:'设置新密码', resetHint:'提交后将更改密码，并使原有登录失效。请使用新密码重新登录',
  reset:'确认重置密码', resetBusy:'正在重置…', resetDone:'密码已重置，请重新登录',
  linkUnavailable:'此链接已失效、已使用或已从当前页面清除。请重新打开邮件中的链接；如仍无效，请申请新链接',
  linkSubmitted:'链接已从当前页面清除。如结果不确定，请重新打开邮件中的链接或申请新链接',
  leaveLink:'关闭链接页面', continueAccount:'返回工作区',
  emailAccount:'邮箱与账号找回', emailVerified:'邮箱已验证', emailNotBound:'尚未绑定已验证邮箱',
  bindingHint:'已有用户名账号可保留原用户名。绑定邮箱需要当前密码，并在邮件中完成验证',
  bind:'绑定邮箱', bindBusy:'正在请求绑定…', currentPassword:'当前密码',
  bindingPending:'如果此邮箱符合条件，会发送验证邮件。绑定尚未完成；请验证后刷新此页面',
  emailRecovery:'此账号可通过已验证邮箱找回密码',
  bootstrapRecovery:'管理员密码由服务器私有配置管理，本版本不支持管理员邮箱重置。需要找回时，请由管理员本人在私有服务器终端完成恢复；不要在聊天中发送密码',
});
Object.assign(COPY.en, {
  remember:'Remember me for 8 hours', showPassword:'Show password', hidePassword:'Hide password',
  email:'Email', emailPlaceholder:'name@example.com', identity:'Email or existing username', identityPlaceholder:'Enter email or an existing username',
  emailHint:'Use an inbox you can access. New accounts require email verification', identityHint:'New accounts register with email. Original usernames are for existing-account sign-in only',
  emailUnavailable:'Email delivery is not configured or is unavailable. Registration, verification requests, and email recovery are unavailable. Contact the administrator',
  emailPrivacy:'Verification links expire in 10 minutes. Reset links expire in 30 minutes and can be used once. Do not forward links',
  acceptedTitle:'Check your inbox if eligible', acceptedHint:'If this email is eligible, the service will send the relevant email. This does not confirm an account exists or that delivery succeeded',
  checkSpam:'Check your inbox and spam folder. After verification, return to sign in',
  resend:'Resend verification email', resendBusy:'Requesting verification…', cooldown:'seconds until another request',
  forgot:'Forgot password?', forgotTitle:'Recover your password', forgotHint:'Enter your account’s verified email. Existing username accounts must sign in and bind an email before email recovery is available',
  requestReset:'Request reset link', requestBusy:'Submitting…', backToLogin:'Return to sign in', changeEmail:'Change email',
  verifyTitle:'Verify your email', verifyHint:'Confirm that you want to verify this email. Opening this page does not use the link. Only the button below submits verification',
  verify:'Confirm email verification', verifyBusy:'Verifying…', verified:'Email verified. New accounts can now sign in; existing accounts can refresh their account status',
  resetTitle:'Set a new password', resetHint:'Submitting changes your password and invalidates previous sign-ins. Sign in again with the new password',
  reset:'Confirm password reset', resetBusy:'Resetting…', resetDone:'Password reset. Sign in again',
  linkUnavailable:'This link expired, was used, or was cleared from this page. Reopen the email link. If it still fails, request a new link',
  linkSubmitted:'The link has been cleared from this page. If the result is uncertain, reopen the email link or request a new one',
  leaveLink:'Close link page', continueAccount:'Return to workspace',
  emailAccount:'Email and account recovery', emailVerified:'Email verified', emailNotBound:'No verified email bound',
  bindingHint:'Existing accounts keep their original username. Binding needs your current password and verification through your inbox',
  bind:'Bind email', bindBusy:'Requesting binding…', currentPassword:'Current password',
  bindingPending:'If this email is eligible, a verification email will be sent. Binding is not complete. Verify, then refresh this page',
  emailRecovery:'This account can recover its password through its verified email',
  bootstrapRecovery:'The administrator password is managed by private server configuration. Email password reset is unavailable for administrators in this release. The administrator must complete recovery personally in the private server terminal. Never send passwords through chat',
});
const ERRORS = {
  zh: {
    AUTH_USERNAME_REQUIRED:'请输入用户名', AUTH_USERNAME_INVALID:'用户名格式不正确，请按下方规则输入', AUTH_USERNAME_RESERVED:'该用户名不可用于注册，请选择其他用户名',
    PASSWORD_LENGTH:'密码须为 6–256 个字符', PASSWORD_CONTROL:'密码不能包含控制字符', PASSWORD_MISMATCH:'两次输入的密码不一致',
    INVALID_CREDENTIALS:'邮箱、用户名或密码不正确', LOGIN_RATE_LIMITED:'登录尝试过多，请稍后再试', REGISTRATION_RATE_LIMITED:'注册尝试过多，请等待十分钟后重试',
    REGISTRATION_INVALID:'无法注册，请核对邮箱和两次密码', USER_INVALID:'该用户名不可用，请重新选择', USER_EXISTS:'该用户名已被使用，请选择其他用户名', USER_LIMIT_REACHED:'当前账号名额已满，请联系管理员',
    OPERATOR_SETUP_REQUIRED:'管理员尚未完成初始化，暂时不能使用此功能', HTTPS_REQUIRED:'请通过已配置的 HTTPS 地址操作',
    AUTH_REQUIRED:'登录已失效，请重新登录', CSRF_REJECTED:'会话状态已变化，请刷新状态后重试', ORIGIN_REJECTED:'当前访问地址与服务器配置不符，请使用正确的站点地址', OWNER_REQUIRED:'此操作只允许管理员执行',
    API_KEY_REQUIRED:'开启模型请求前，请先配置 Key', API_KEY_INVALID:'Key 格式不正确，请检查后重新输入', INVALID_SETTINGS:'请检查设置内容后重试',
    SETTINGS_RATE_LIMITED:'设置操作过于频繁，请等待一分钟后重试', CONNECTION_FAILED:'连接验证失败，请检查 Key、账户权限和网络', MODEL_UNAVAILABLE:'此账号未返回 deepseek-flash 模型权限，请检查服务账户', SETTINGS_CHANGED:'验证期间设置已变化，请重新验证当前设置', BUSY:'已有操作正在进行，请稍后重试',
    NETWORK_ERROR:'网络连接失败，请检查连接后重试', INVALID_RESPONSE:'服务器响应无法读取，请稍后重试', REQUEST_FAILED:'操作未完成，请重试；请勿在错误反馈中发送密码或 Key',
  },
  en: {
    AUTH_USERNAME_REQUIRED:'Enter a username', AUTH_USERNAME_INVALID:'The username format is invalid. Follow the rules below', AUTH_USERNAME_RESERVED:'This username cannot be registered. Choose another',
    PASSWORD_LENGTH:'Use 6–256 password characters', PASSWORD_CONTROL:'Control characters are not allowed in passwords', PASSWORD_MISMATCH:'The passwords do not match',
    INVALID_CREDENTIALS:'The email, username, or password is incorrect', LOGIN_RATE_LIMITED:'Too many sign-in attempts. Try again shortly', REGISTRATION_RATE_LIMITED:'Too many registration attempts. Wait ten minutes before retrying',
    REGISTRATION_INVALID:'Registration failed. Check the email and both passwords', USER_INVALID:'This username is unavailable. Choose another', USER_EXISTS:'This username is already in use. Choose another', USER_LIMIT_REACHED:'The account limit has been reached. Contact the administrator',
    OPERATOR_SETUP_REQUIRED:'Administrator setup must be completed before this feature is available', HTTPS_REQUIRED:'Use the configured HTTPS address',
    AUTH_REQUIRED:'Your sign-in has expired. Sign in again', CSRF_REJECTED:'Session state changed. Refresh status and retry', ORIGIN_REJECTED:'This address does not match the server configuration. Use the correct site address', OWNER_REQUIRED:'Only the administrator can perform this action',
    API_KEY_REQUIRED:'Configure a key before enabling model requests', API_KEY_INVALID:'The key format is invalid. Check it and enter it again', INVALID_SETTINGS:'Check the settings and try again',
    SETTINGS_RATE_LIMITED:'Too many settings requests. Wait a minute before retrying', CONNECTION_FAILED:'Verification failed. Check the key, account access, and connection', MODEL_UNAVAILABLE:'This account did not list deepseek-flash. Check model access with the provider', SETTINGS_CHANGED:'Settings changed during verification. Verify the current settings again', BUSY:'Another operation is in progress. Try again shortly',
    NETWORK_ERROR:'The network request failed. Check your connection and retry', INVALID_RESPONSE:'The server response could not be read. Please retry', REQUEST_FAILED:'The operation did not complete. Retry without sending passwords or keys in error reports',
  },
};
Object.assign(ERRORS.zh, {
  AUTH_EMAIL_REQUIRED:'请输入邮箱', AUTH_EMAIL_INVALID:'请输入有效的邮箱地址', AUTH_IDENTITY_REQUIRED:'请输入邮箱或已有用户名', AUTH_IDENTITY_INVALID:'请输入有效邮箱或原有用户名',
  EMAIL_DELIVERY_UNAVAILABLE:'邮件服务尚未配置或暂不可用，请联系管理员后再试', EMAIL_AUTH_INVALID:'请核对邮箱和输入内容后重试', EMAIL_TOKEN_INVALID:'此链接无效、已过期或已使用，请申请新链接',
  EMAIL_AUTH_RATE_LIMITED:'请求过于频繁，请至少等待 60 秒；每个邮箱每小时最多 5 次', EMAIL_ALREADY_BOUND:'此账号已经绑定邮箱，请刷新查看当前状态',
});
Object.assign(ERRORS.en, {
  AUTH_EMAIL_REQUIRED:'Enter your email', AUTH_EMAIL_INVALID:'Enter a valid email address', AUTH_IDENTITY_REQUIRED:'Enter email or an existing username', AUTH_IDENTITY_INVALID:'Enter a valid email or original username',
  EMAIL_DELIVERY_UNAVAILABLE:'Email delivery is not configured or is unavailable. Contact the administrator and retry later', EMAIL_AUTH_INVALID:'Check the email and form values, then retry', EMAIL_TOKEN_INVALID:'This link is invalid, expired, or already used. Request a new link',
  EMAIL_AUTH_RATE_LIMITED:'Too many requests. Wait at least 60 seconds; each email is limited to 5 requests per hour', EMAIL_ALREADY_BOUND:'This account already has a bound email. Refresh to see its status',
});
export const language = lang => lang === 'en' ? 'en' : 'zh';
export const authCopy = lang => COPY[language(lang)];
export function authErrorMessage(error, lang = 'zh') {
  const code = typeof error === 'string' ? error : error?.code;
  return ERRORS[language(lang)][code] || ERRORS[language(lang)].REQUEST_FAILED;
}
