export const intakeCopy = {
  zh: {
    recovered: '已恢复本标签页内尚未保存的文本修改。请先核对当前保存版本；原始文件需重新选择。',
    cacheUnavailable: '当前修改超出临时恢复容量。请尽快保存案例，刷新或会话过期可能丢失未保存修改。',
    eyebrow: '01 / 材料与事实',
    title: '让每个事实，都有出处',
    intro: '保留原始材料，核对五项关键事实，再继续准备英文文书。',
    signIn: '请先登录，再处理自己的案例材料。',
    loading: '正在读取案例…',
    retry: '重新读取',
    untitled: '未命名案例',
    caseTitle: '案例名称',
    caseSaved: '已保存',
    unsaved: '有未保存的修改',
    notSaved: '尚未保存案例',
    version: '版本',
    materialTitle: '整理材料',
    materialHelp: '原始文件仅对当前账户可见。保存到服务器私有档案后，本服务会解析可读文本；此步骤不会发送给 AI。',
    safeOnly: '当前仅接受合成或彻底去标识化的材料。不要上传真实身份、税务、银行资料或秘密。',
    chooseFiles: '选择材料',
    formats: 'TXT / CSV / PDF / XLSX / XLS / PNG / JPEG · 每个文件不超过 5 MiB',
    queue: '待处理文件',
    queueEmpty: '选择文件，或在下方粘贴原文。',
    remove: '移除',
    saveFiles: '保存到私有档案并处理',
    processing: '正在保存并处理…',
    cancel: '取消处理',
    cancelNote: '处理已停止。已经确认保存的原件仍保留；若请求中断，可能已有文件保存，请先查看私有档案再重试。',
    savedAsset: '原件已保存',
    unavailable: '原件已保存，没有可用文本。图片与扫描 PDF 暂无 OCR；请核对原件并补充去标识化文本。',
    truncated: '原件已保存，但索引文本被截短。未把不完整文本加入案例；请自行选取完整相关片段。',
    savedParseError: '原件已保存，但未能加入案例文本。可查看原件；修正后再处理。',
    uploadError: '文件保存未确认。网络中断时，请先查看私有档案，避免重复上传。',
    assets: '本案例原始材料',
    noAssets: '还没有关联的原始材料',
    standalone: '保存案例后，会将本次原件关联到案例。',
    preview: '查看原件',
    download: '下载原件',
    archiveLink: '关联到已保存案例',
    linkFailed: '案例已保存，但部分原件关联未完成。原件仍在私有档案，可重试关联。',
    linkSuccess: '原件已关联到当前案例。',
    sourceTitle: '案例原文',
    sourceHelp: '新文件文本会追加到这里。已有事实和出处会保留；新证据有矛盾时需重新核对。',
    sourcePlaceholder: '粘贴合成或已彻底去标识化的材料…',
    chars: '字符',
    sourceTooLong: '原文超过 50,000 字符。请手动精简，内容不会被静默截断。',
    textAdded: '已追加可用文本。下一步请选择明确标签整理或 AI 提取，并核对结果。',
    manual: '整理明确标签',
    manualHelp: '仅识别 Property:、Owner:、PHA:、Case reference:、Proposed rent: 明确标签，不调用模型。',
    aiTitle: 'AI 提取 · deepseek-flash',
    aiHelp: '仅将上方案例原文发送给 DeepSeek 提取五项事实。原件不会随此请求发送；请先确认使用权限与数据边界。',
    aiConsent: '我确认材料已去标识化，并同意将上方原文发送给 DeepSeek',
    aiExtract: '使用 AI 提取',
    extracting: '正在提取…',
    aiUnavailable: 'AI 尚未配置或启用。请联系管理员；可继续手动核对，失败不会改用模拟结果。',
    consentRequired: '请先明确同意发送当前原文。',
    extracted: '建议已整理，请逐项核对。已有不同值保留为冲突，不会被直接覆盖。',
    factsTitle: '核对关键事实',
    factsHelp: '“已核对”仅表示操作员核对，不代表机构批准。空值可以明确标记为已核对的未知项。',
    fieldLabels: {
      property: '物业地址',
      owner: '业主',
      pha: '住房机构',
      caseReference: '案例编号',
      rent: '拟申请租金'
    },
    factValue: '内容',
    unknown: '未提供 / 待确认',
    reviewed: '已核对',
    needsReview: '待核对',
    conflict: '证据有冲突',
    fieldSource: '来源 / 摘录',
    sourceNone: '尚无来源。直接填写时，请补充资料出处或说明。',
    confirm: '我已核对这项事实或未知状态',
    resolve: '保留当前填写值并确认已解决冲突',
    conflictHelp: '比对下方不同出处，必要时修改内容；明确解决冲突后才能确认。',
    edited: '人工修改',
    rentNote: '拟申请租金不等于已批准租金。',
    save: '保存案例',
    saving: '正在保存…',
    saved: '案例已保存。',
    documents: '继续准备文书',
    saveDocuments: '保存并继续准备文书',
    draftNotice: '本次事实变更会先保留旧草稿为历史版本。已保存的文书保持历史记录，新版本需重新生成。',
    archiveFailed: '旧草稿未能归档，已停止保存，当前修改仍在。',
    archived: '旧草稿已保留为历史版本。',
    changedElsewhere: '保存版本已变化，当前修改没有被覆盖。读取最新版本后再核对合并。',
    readLatest: '读取最新版本以比较',
    latest: '最新保存版本',
    compareHelp: '合并会保留你的改动，采用未被你修改的远端内容；双方修改的事实会标出冲突，双方原文都会保留。',
    reconcile: '合并并继续核对',
    replaceLatest: '放弃本地修改，使用最新版本',
    replaceAsk: '放弃当前未保存的材料文本与事实修改，使用最新保存版本？',
    reconcileDone: '已合并到最新版本基础上，请核对冲突并再次保存。',
    remoteSource: '最新保存原文',
    workbookTitle: '选择一张工作表的一行',
    workbookHelp: '只导入你选择的一行。公式、超链接、隐藏与合并单元格不可选；宏和外部链接不会运行。',
    sheet: '工作表',
    row: '数据行',
    mapColumn: '对应列',
    unmapped: '不映射 / 未知',
    blocked: '不可导入',
    truncatedSheet: '这是有界预览；仅显示前 200 行、50 列。',
    mapApply: '追加此行并核对事实',
    mapCancel: '关闭映射（原件保留）',
    mappingDone: '已追加所选行。字段保留单元格出处，请逐项核对。',
    errors: {
      LEGACY_ARCHIVE_REQUIRED: '旧草稿需要先作为历史版本保留，当前保存已停止，修改仍在。',
      CONSENT_REQUIRED: '请先同意发送当前原文。',
      NETWORK_ERROR: '目前无法连接。当前编辑仍保留，请稍后重试。',
      REQUEST_FAILED: '请求未完成。当前编辑仍保留，请重试。',
      AUTH_REQUIRED: '登录已过期，请重新登录。',
      CSRF_REJECTED: '会话已变化，请重新登录后重试。',
      ORIGIN_REJECTED: '请求来源未通过验证。请使用本服务页面。',
      CASE_NOT_FOUND: '案例不存在或当前账户无权访问。',
      CASE_CONFLICT: '案例已在别处修改。请读取最新版本以比较。',
      CASE_INVALID: '案例内容无效，请核对文本与字段。',
      CASE_TOO_LARGE: '案例内容超出限额，请精简原文或字段，不会自动截断。',
      TEXT_TOO_LARGE: '加入后原文将超过 50,000 字符，未追加。请先精简原文或选取相关内容。',
      SOURCE_EMPTY: '请先提供可用的案例原文。',
      ASSET_TYPE_UNSUPPORTED: '不支持这个文件类型。请选择所列支持格式。',
      ASSET_TOO_LARGE: '文件超过 5 MiB，请选择较小文件。',
      ASSET_EMPTY: '文件为空，未保存。',
      ASSET_QUOTA_EXCEEDED: '私有档案已达 200 个文件或 256 MiB 上限。',
      ASSET_FILENAME_INVALID: '文件名包含不允许的字符，请重命名后重试。',
      ASSET_TEXT_INVALID: '文本不是有效 UTF-8，未保存。',
      ASSET_CSV_INVALID: 'CSV 无效，未保存。',
      CSV_INVALID: 'CSV 需使用 property,owner,pha,caseReference,rent 表头且只有一行案例。原件已保留。',
      ASSET_IMAGE_INVALID: '图片内容无效，未保存。',
      INVALID_PDF: 'PDF 损坏或无效，未保存。',
      PDF_ENCRYPTED: '不支持加密 PDF，请提供去标识化、未加密的副本。',
      PDF_UNAVAILABLE: '服务器 PDF 解析暂不可用，请稍后重试。',
      INVALID_WORKBOOK: 'Excel 文件无法解析或没有可选工作表。',
      WORKBOOK_ENCRYPTED: '不支持加密 Excel。请提供去标识化、纯值副本。',
      WORKBOOK_TOO_COMPLEX: 'Excel 超出安全预览限额，请提供较小的纯值副本。',
      WORKBOOK_UNAVAILABLE: '服务器 Excel 解析暂不可用。',
      MAPPING_INVALID: '请为至少一个字段选择不同的有效列，不要选择受限单元格。',
      ASSET_CONFLICT: '原件关联版本已变化，请刷新后重试。',
      BUSY: '服务正在处理其他请求，请稍后重试。',
      LIVE_DISABLED: 'AI 提取未启用，请联系管理员。',
      PROVIDER_ERROR: 'DeepSeek 请求失败，当前事实没有改动，未使用替代结果。',
      EXTRACTION_FAILED: 'AI 提取失败，当前事实没有改动，未使用替代结果。',
      SENSITIVE_DATA: '检测到疑似敏感标识，未发送给模型。请移除后重试。',
      TRIAL_LIMIT_REACHED: '当前账户的提取额度已用完，请稍后再试。',
      INVALID_RESPONSE: '服务返回的数据无法验证，未替换当前内容。',
      CAPACITY_REACHED: '已达保存容量上限，当前修改仍保留。',
      QUEUE_FULL: '一次最多处理 10 个文件，请分批选择。'
    }
  },
  en: {
    recovered: 'Recovered unsaved text edits from this tab. Review them against the saved version. Select original files again if needed.',
    cacheUnavailable: 'These edits exceed temporary recovery capacity. Save the case soon; refreshing or session expiry may lose unsaved edits.',
    eyebrow: '01 / MATERIALS & FACTS',
    title: 'Give every fact a source',
    intro: 'Keep original materials, review five key facts, then prepare English documents.',
    signIn: 'Sign in to work with your own case materials.',
    loading: 'Loading case…',
    retry: 'Read again',
    untitled: 'Untitled case',
    caseTitle: 'Case name',
    caseSaved: 'Saved',
    unsaved: 'Unsaved changes',
    notSaved: 'Case not saved yet',
    version: 'Version',
    materialTitle: 'Organize materials',
    materialHelp: 'Originals are private to this account. Saving stores the original on this service and parses readable text. This step does not send anything to AI.',
    safeOnly: 'Synthetic or thoroughly de-identified materials only. Do not upload real identity, tax, banking records, or secrets.',
    chooseFiles: 'Choose materials',
    formats: 'TXT / CSV / PDF / XLSX / XLS / PNG / JPEG · Up to 5 MiB per file',
    queue: 'Files to process',
    queueEmpty: 'Choose a file or paste source text below.',
    remove: 'Remove',
    saveFiles: 'Save privately and process',
    processing: 'Saving and processing…',
    cancel: 'Cancel processing',
    cancelNote: 'Processing stopped. Confirmed saved originals remain private. An interrupted request may already have saved a file; check the archive before retrying.',
    savedAsset: 'Original saved',
    unavailable: 'Original saved, but no usable text. Images and scanned PDFs have no OCR. Review the original and add de-identified text yourself.',
    truncated: 'Original saved, but indexed text is truncated. Incomplete text was not added to this case. Select complete relevant passages yourself.',
    savedParseError: 'Original saved, but text was not added to the case. You can view the original and resolve the processing issue.',
    uploadError: 'File save was not confirmed. After a network interruption, check the private archive before uploading again.',
    assets: 'Original case materials',
    noAssets: 'No original materials linked yet',
    standalone: 'Saving this case will link the originals saved in this session.',
    preview: 'View original',
    download: 'Download original',
    archiveLink: 'Link to saved case',
    linkFailed: 'Case saved, but some originals were not linked. They remain in the private archive; retry linking.',
    linkSuccess: 'Originals linked to this case.',
    sourceTitle: 'Case source text',
    sourceHelp: 'New file text is appended here. Existing facts and evidence stay intact; contradictory new evidence requires review.',
    sourcePlaceholder: 'Paste synthetic or thoroughly de-identified material…',
    chars: 'characters',
    sourceTooLong: 'Source exceeds 50,000 characters. Shorten it manually; text is never silently truncated.',
    textAdded: 'Readable text appended. Choose explicit-label organization or AI extraction, then review the results.',
    manual: 'Organize explicit labels',
    manualHelp: 'Reads only Property:, Owner:, PHA:, Case reference:, and Proposed rent: labels. No model call.',
    aiTitle: 'AI extraction · deepseek-flash',
    aiHelp: 'Sends only the case source text above to DeepSeek to extract five facts. Originals are not attached to this request. Confirm your authorization and data boundaries first.',
    aiConsent: 'This text is de-identified, and I agree to send it to DeepSeek',
    aiExtract: 'Extract with AI',
    extracting: 'Extracting…',
    aiUnavailable: 'AI is not configured or enabled. Contact your administrator. Manual review remains available; failure never switches to simulated results.',
    consentRequired: 'Explicitly consent to sending the current source text first.',
    extracted: 'Suggestions ready for review. Different existing values are retained as conflicts, never silently overwritten.',
    factsTitle: 'Review key facts',
    factsHelp: 'Reviewed means operator-reviewed, not agency-approved. A missing value can be explicitly reviewed as unknown.',
    fieldLabels: {
      property: 'Property address',
      owner: 'Owner',
      pha: 'Housing authority',
      caseReference: 'Case reference',
      rent: 'Proposed rent'
    },
    factValue: 'Value',
    unknown: 'Not provided / to confirm',
    reviewed: 'Reviewed',
    needsReview: 'Needs review',
    conflict: 'Conflicting evidence',
    fieldSource: 'Source / excerpt',
    sourceNone: 'No source yet. Add an excerpt or explain a direct manual entry.',
    confirm: 'I reviewed this fact or its unknown status',
    resolve: 'Keep the entered value and confirm this conflict is resolved',
    conflictHelp: 'Compare the sources below and edit the value if needed. Resolve the conflict explicitly before confirming.',
    edited: 'Manually edited',
    rentNote: 'Proposed rent is not approved rent.',
    save: 'Save case',
    saving: 'Saving…',
    saved: 'Case saved.',
    documents: 'Continue to documents',
    saveDocuments: 'Save and continue to documents',
    draftNotice: 'Changing facts first preserves the previous draft as a historical version. Saved documents stay in history; generate a new version after changes.',
    archiveFailed: 'The previous draft could not be archived. Saving stopped; your edits remain.',
    archived: 'The previous draft was preserved as a historical version.',
    changedElsewhere: 'The saved version changed. Your edits were not overwritten. Read the latest version and reconcile before saving.',
    readLatest: 'Read latest to compare',
    latest: 'Latest saved version',
    compareHelp: 'Reconciliation keeps your edits and adopts remote content you did not change. Overlapping fact changes become conflicts; both source texts are retained.',
    reconcile: 'Reconcile and review',
    replaceLatest: 'Discard local edits and use latest',
    replaceAsk: 'Discard unsaved source and fact edits and use the latest saved version?',
    reconcileDone: 'Reconciled against the latest version. Review conflicts and save again.',
    remoteSource: 'Latest saved source',
    workbookTitle: 'Choose one worksheet and row',
    workbookHelp: 'Import only the selected row. Formula, hyperlink, hidden, and merged cells are blocked. Macros and external links never run.',
    sheet: 'Worksheet',
    row: 'Data row',
    mapColumn: 'Mapped column',
    unmapped: 'Not mapped / unknown',
    blocked: 'Blocked',
    truncatedSheet: 'Bounded preview: only the first 200 rows and 50 columns are available.',
    mapApply: 'Append this row and review facts',
    mapCancel: 'Close mapping (keep original)',
    mappingDone: 'Selected row appended with cell-level evidence. Review each field.',
    errors: {
      LEGACY_ARCHIVE_REQUIRED: 'The prior draft must be archived before saving revised facts. Your edits remain.',
      CONSENT_REQUIRED: 'Consent to sending the current source text first.',
      NETWORK_ERROR: 'Cannot connect right now. Your edits remain; try again later.',
      REQUEST_FAILED: 'The request did not finish. Your edits remain; try again.',
      AUTH_REQUIRED: 'Your session expired. Sign in again.',
      CSRF_REJECTED: 'The session changed. Sign in again before retrying.',
      ORIGIN_REJECTED: 'The request origin was not accepted. Use this service’s own page.',
      CASE_NOT_FOUND: 'This case is unavailable to the current account.',
      CASE_CONFLICT: 'The case changed elsewhere. Read the latest version to compare.',
      CASE_INVALID: 'Invalid case content. Check the source and fields.',
      CASE_TOO_LARGE: 'Case content exceeds the limits. Shorten source or fields; nothing is automatically truncated.',
      TEXT_TOO_LARGE: 'Appending would exceed 50,000 characters. Nothing was added. Shorten the source or select relevant passages.',
      SOURCE_EMPTY: 'Provide usable case source text first.',
      ASSET_TYPE_UNSUPPORTED: 'Unsupported file type. Choose one of the listed formats.',
      ASSET_TOO_LARGE: 'The file exceeds 5 MiB. Choose a smaller file.',
      ASSET_EMPTY: 'The file is empty and was not saved.',
      ASSET_QUOTA_EXCEEDED: 'The private archive reached 200 files or 256 MiB.',
      ASSET_FILENAME_INVALID: 'The filename contains unsupported characters. Rename it and retry.',
      ASSET_TEXT_INVALID: 'The text is not valid UTF-8 and was not saved.',
      ASSET_CSV_INVALID: 'The CSV is invalid and was not saved.',
      CSV_INVALID: 'CSV requires the property,owner,pha,caseReference,rent header and exactly one case row. The original remains saved.',
      ASSET_IMAGE_INVALID: 'The image is invalid and was not saved.',
      INVALID_PDF: 'The PDF is damaged or invalid and was not saved.',
      PDF_ENCRYPTED: 'Encrypted PDFs are unsupported. Use a de-identified, unencrypted copy.',
      PDF_UNAVAILABLE: 'Server PDF parsing is unavailable. Try again later.',
      INVALID_WORKBOOK: 'The Excel file cannot be parsed or has no selectable worksheet.',
      WORKBOOK_ENCRYPTED: 'Encrypted Excel files are unsupported. Use a de-identified values-only copy.',
      WORKBOOK_TOO_COMPLEX: 'The workbook exceeds safe preview limits. Use a smaller values-only copy.',
      WORKBOOK_UNAVAILABLE: 'Server Excel parsing is unavailable.',
      MAPPING_INVALID: 'Map at least one field to distinct valid columns; avoid blocked cells.',
      ASSET_CONFLICT: 'The original’s association changed. Refresh before retrying.',
      BUSY: 'The service is busy. Try again shortly.',
      LIVE_DISABLED: 'AI extraction is disabled. Contact your administrator.',
      PROVIDER_ERROR: 'The DeepSeek request failed. Current facts were unchanged; no substitute results were used.',
      EXTRACTION_FAILED: 'AI extraction failed. Current facts were unchanged; no substitute results were used.',
      SENSITIVE_DATA: 'Potential sensitive identifiers were detected and not sent to the model. Remove them and retry.',
      TRIAL_LIMIT_REACHED: 'This account’s extraction allowance has been reached. Try again later.',
      INVALID_RESPONSE: 'The response could not be verified. Current content was not replaced.',
      CAPACITY_REACHED: 'The save capacity limit was reached. Your edits remain.',
      QUEUE_FULL: 'Process at most 10 files at a time. Choose files in smaller batches.'
    }
  }
};
export const wordsFor = lang => intakeCopy[lang] || intakeCopy.zh;
export function errorText(error, words) {
  return words.errors[error?.code] || words.errors.REQUEST_FAILED;
}
