export const intakeCopy = {
  zh: {
    chatTextAdded: '对话文字已加入本页，仍待核实。\n请核对信息，再保存事项。',
    recovered: "已恢复未保存的文字，请重新选择文件。",
    cacheUnavailable: '临时保存空间不足，请尽快保存事项。\n刷新或登录过期可能丢失未保存修改。',
    eyebrow: '材料',
    title: '材料',
    intro: "导入材料，核对后准备文档。",
    signIn: '请先登录，再处理自己的事项材料。',
    loading: '正在读取事项…',
    retry: '重新读取',
    untitled: '未命名',
    caseTitle: '事项名称',
    caseSaved: '已保存',
    unsaved: '尚未保存',
    notSaved: '事项未保存',
    version: '版本',
    materialTitle: '整理材料',
    chooseFiles: '添加文件',
    formats: 'TXT\nCSV\nPDF\nXLSX\nXLS\nPNG\nJPEG\n每个文件不超过5MiB',
    queue: '文件列表',
    queueEmpty: '添加文件，或粘贴材料原文。',
    remove: '移除',
    saveFiles: '保存原件',
    saveFilesHelp: '保存后会读取文字。\n原件仅当前账号可见。',
    processing: '正在保存并读取…',
    cancel: '停止处理',
    cancelNote: '处理已停止，已保存的原件仍保留。\n中断前可能已有文件保存。\n请先检查原件列表，再重试。',
    savedAsset: '原件已保存',
    unavailable: "原件已保存，未读到文字。\n请在下方补充。",
    truncated: "原件已保存，文字过长。\n请选择需要的段落加入事项。",
    savedParseError: '原件已保存，文字未加入事项。\n请查看原件，修正后重试。',
    uploadError: '尚未确认文件是否保存。\n请先检查原件列表，避免重复上传。',
    assets: '事项原件',
    noAssets: '暂无关联原件',
    standalone: '保存事项后，会关联本次原件。',
    preview: '查看原件',
    download: '下载原件',
    archiveLink: '关联事项',
    linkFailed: '事项已保存，部分原件尚未关联。\n原件仍保留，可重试关联。',
    linkSuccess: '原件已关联当前事项。',
    sourceTitle: '材料原文',
    sourceHelp: "可直接修改或补充文字。",
    sourcePlaceholder: "粘贴材料原文…",
    chars: '字符',
    sourceTooLong: "原文超过5万字符，请缩短后重试。",
    textAdded: "文字已添加，请继续核对信息。",
    manual: '按项读取',
    manualHelp: '仅识别这些英文标签：\nProperty:\nOwner:\nPHA:\nCase reference:\nProposed rent:',
    aiTitle: "提取信息",
    aiProvider: '由DeepSeek读取材料。',
    aiExtract: "开始提取",
    extracting: '正在提取…',
    aiUnavailable: "请先连接DeepSeek。\n也可以继续手动填写。",
    consentRequired: '请先明确同意发送当前原文。',
    extracted: "提取完成，请逐项核对。",
    factsTitle: '核对信息',
    factsHelp: "核对内容和出处，再确认保存。",
    fieldLabels: {
      property: '房屋地址',
      owner: '业主',
      pha: '住房机构',
      caseReference: '事项编号',
      rent: '申请租金'
    },
    factValue: '内容',
    unknown: '待确认',
    reviewed: '已核对',
    needsReview: '待核对',
    conflict: '信息不一',
    fieldSource: '资料出处',
    sourceNone: "填写出处或原文片段",
    confirm: '我已核对内容或待确认状态',
    resolve: '保留此值',
    conflictHelp: '请对照不同出处，修改有误内容。\n解决差异后才能确认。',
    edited: '手动修改',
    save: '保存事项',
    saving: '正在保存…',
    saved: '事项已保存。',
    documents: '准备文档',
    saveDocuments: '保存继续',
    draftNotice: "修改资料后，请重新生成文档。",
    archiveFailed: '旧草稿未能留存，保存已停止。\n当前修改仍保留。',
    archived: '事项已保存，旧草稿保留为历史版本。',
    savedNewerEdits: '刚才提交的版本已保存。\n之后的修改仍在本页，尚未保存。',
    archivedNewerEdits: '刚才提交的版本已保存。\n旧草稿已保留为历史版本。\n之后的修改尚未保存。',
    changedElsewhere: '已存版本有更新，当前修改仍保留。\n请读取最新版本，核对后合并。',
    readLatest: '查看新版',
    latest: '最新版本',
    compareHelp: '合并会保留你改过的内容。\n其余内容采用最新保存版本。\n双方都改过的信息会标出差异。\n双方的材料原文都会保留。',
    reconcile: '合并核对',
    replaceLatest: '放弃修改',
    replaceAsk: '将放弃未保存的材料和信息修改。\n改用最新保存的版本。\n要继续吗？',
    reconcileDone: '已合并最新版本。\n请核对差异，再次保存。',
    remoteSource: '最新原文',
    workbookTitle: '选择数据',
    workbookHelp: "选择工作表、数据行和对应列。",
    sheet: '工作表',
    row: '数据行',
    mapColumn: '对应列',
    unmapped: '暂不选列',
    blocked: '无法导入',
    truncatedSheet: '预览前 200 行、50 列。',
    mapApply: '加入此行',
    mapCancel: '取消选择',
    mappingDone: '已加入所选行，请逐项核对。\n每项信息均保留单元格出处。',
    errors: {
      LEGACY_ARCHIVE_REQUIRED: '需先保留旧草稿，保存已停止。\n当前修改仍保留。',
      CONSENT_REQUIRED: '请先同意发送当前原文。',
      NETWORK_ERROR: '暂时无法连接，当前修改仍保留。\n请稍后重试。',
      REQUEST_FAILED: '请求未完成。当前编辑仍保留，请重试。',
      SESSION_REFRESHED:'连接已恢复，操作未自动重试。\n请核对后再试。', AUTH_REQUIRED: '登录已过期，请重新登录。',
      CSRF_REJECTED: '登录状态已变化，请重新登录后重试。',
      ORIGIN_REJECTED: '访问地址未通过检查，请使用本站页面。',
      CASE_NOT_FOUND: '事项不存在或当前账号无权访问。',
      CASE_CONFLICT: '事项已在别处修改。\n请读取最新版本进行对照。',
      CASE_INVALID: '事项内容无效，请核对文字和填写内容。',
      CASE_TOO_LARGE: '事项内容过长，不会自动删减。\n请缩短原文或填写内容。',
      TEXT_TOO_LARGE: '加入后将超过5万字符，本次未加入。\n请缩短原文或选取相关内容。',
      SOURCE_EMPTY: '请先提供可用的事项原文。',
      ASSET_TYPE_UNSUPPORTED: '不支持这个文件类型。请选择所列支持格式。',
      ASSET_TOO_LARGE: '文件超过 5 MiB，请选择较小文件。',
      ASSET_EMPTY: '文件为空，未保存。',
      ASSET_QUOTA_EXCEEDED: '原件空间已满。\n最多200个文件，总计256MiB。',
      ASSET_FILENAME_INVALID: '文件名包含不允许的字符，请重命名后重试。',
      ASSET_TEXT_INVALID: '文字不是有效 UTF-8，未保存。',
      ASSET_CSV_INVALID: 'CSV 无效，未保存。',
      CSV_INVALID: '原件已保留。\nCSV只可包含一行事项数据。\n表头必须为以下五项：\nproperty\nowner\npha\ncaseReference\nrent',
      ASSET_IMAGE_INVALID: '图片内容无效，未保存。',
      INVALID_PDF: 'PDF 损坏或无效，未保存。',
      PDF_ENCRYPTED: '请提供未加密的PDF副本。\n请先去除材料中的身份信息。',
      PDF_UNAVAILABLE: '暂时无法读取PDF，请稍后重试。',
      INVALID_WORKBOOK: 'Excel无法读取，或无可选工作表。',
      WORKBOOK_ENCRYPTED: '不支持加密Excel。\n请提供去除身份信息的副本。\n仅保留数值或文字，不含公式。',
      WORKBOOK_TOO_COMPLEX: 'Excel超出预览限制。\n请提供较小的副本，不含公式。',
      WORKBOOK_UNAVAILABLE: '暂时无法读取Excel。',
      MAPPING_INVALID: '请至少为一项信息选择有效列。\n不同信息不能选同一列。\n不能选择受限单元格。',
      ASSET_CONFLICT: '原件关联版本已变化，请刷新后重试。',
      BUSY: '服务正在处理其他请求，请稍后重试。',
      LIVE_DISABLED: 'AI 提取未启用，请联系管理员。',
      PROVIDER_ERROR: "提取失败，请重试。",
      EXTRACTION_FAILED: "提取失败，请重试。",
      SENSITIVE_DATA: '疑似含敏感身份信息，尚未发送。\n请去除后重试。',
      TRIAL_LIMIT_REACHED: '本账号提取额度已用完，请稍后再试。',
      INVALID_RESPONSE: '返回结果无法核实，当前内容未改变。',
      CAPACITY_REACHED: '已达保存容量上限，当前修改仍保留。',
      QUEUE_FULL: '一次最多处理10个文件，请分批添加。'
    }
  },
  en: {
    chatTextAdded: 'Unreviewed conversation text appended locally. Review the facts, then save the case.',
    recovered: "Unsaved text restored. Select your files again.",
    cacheUnavailable: 'These edits exceed temporary recovery capacity. Save the case soon; refreshing or session expiry may lose unsaved edits.',
    eyebrow: '01 / MATERIALS & FACTS',
    title: 'Materials & facts',
    intro: "Import materials, review details, and prepare documents.",
    signIn: 'Sign in to work with your own case materials.',
    loading: 'Loading case…',
    retry: 'Read again',
    untitled: 'Untitled case',
    caseTitle: 'Case name',
    caseSaved: 'Saved',
    unsaved: 'Unsaved changes',
    notSaved: 'Case not saved yet',
    version: 'Version',
    materialTitle: 'Organize materials',
    chooseFiles: 'Choose materials',
    formats: 'TXT / CSV / PDF / XLSX / XLS / PNG / JPEG · Up to 5 MiB per file',
    queue: 'Files to process',
    queueEmpty: 'Choose a file or paste source text below.',
    remove: 'Remove',
    saveFiles: 'Save privately and process',
    saveFilesHelp: 'Saved originals are readable only by this account; text is read after saving.',
    processing: 'Saving and processing…',
    cancel: 'Cancel processing',
    cancelNote: 'Processing stopped. Confirmed saved originals remain private. An interrupted request may already have saved a file; check the archive before retrying.',
    savedAsset: 'Original saved',
    unavailable: "Original saved. No text was extracted; add it below.",
    truncated: "Original saved. Select the relevant passages to add to the case.",
    savedParseError: 'Original saved, but text was not added to the case. You can view the original and resolve the processing issue.',
    uploadError: 'File save was not confirmed. After a network interruption, check the private archive before uploading again.',
    assets: 'Original case materials',
    noAssets: 'No original materials linked yet',
    standalone: 'Saving this case will link the originals saved in this session.',
    preview: 'View original',
    download: 'Download original',
    archiveLink: 'Link to saved case',
    linkFailed: 'Case saved, but some originals were not linked. They remain in the private archive; retry linking.',
    linkSuccess: 'Originals linked to this case.',
    sourceTitle: 'Case source text',
    sourceHelp: "Edit or add to the material text.",
    sourcePlaceholder: "Paste material text…",
    chars: 'characters',
    sourceTooLong: "Text exceeds 50,000 characters. Shorten it and try again.",
    textAdded: "Text added. Review the details to continue.",
    manual: 'Organize explicit labels',
    manualHelp: 'Reads only Property:, Owner:, PHA:, Case reference:, and Proposed rent: labels.',
    aiTitle: "AI extraction",
    aiProvider: 'DeepSeek reads the material for extraction.',
    aiExtract: "Extract with DeepSeek",
    extracting: 'Extracting…',
    aiUnavailable: "Connect DeepSeek in Settings, or enter the details manually.",
    consentRequired: 'Explicitly consent to sending the current source text first.',
    extracted: "Extraction complete. Review each detail.",
    factsTitle: 'Review key facts',
    factsHelp: "Review each value and its source, then save.",
    fieldLabels: {
      property: 'Property address',
      owner: 'Owner',
      pha: 'Housing authority',
      caseReference: 'Case reference',
      rent: 'Proposed rent'
    },
    factValue: 'Value',
    unknown: 'Not provided / to confirm',
    reviewed: 'Reviewed',
    needsReview: 'Needs review',
    conflict: 'Conflicting evidence',
    fieldSource: 'Source / excerpt',
    sourceNone: "Enter a source or excerpt",
    confirm: 'I reviewed this fact or its unknown status',
    resolve: 'Keep the entered value and confirm this conflict is resolved',
    conflictHelp: 'Compare the sources below and edit the value if needed. Resolve the conflict explicitly before confirming.',
    edited: 'Manually edited',
    save: 'Save case',
    saving: 'Saving…',
    saved: 'Case saved.',
    documents: 'Continue to documents',
    saveDocuments: 'Save and continue to documents',
    draftNotice: "Regenerate the document after changing its details.",
    archiveFailed: 'The previous draft could not be archived. Saving stopped; your edits remain.',
    archived: 'Case saved. The previous draft was preserved as a historical version.',
    savedNewerEdits: 'The submitted version was saved. Your newer edits remain on this page and are not saved yet.',
    archivedNewerEdits: 'The submitted version was saved and the previous draft preserved in history. Your newer edits are not saved yet.',
    changedElsewhere: 'The saved version changed. Your edits were not overwritten. Read the latest version and reconcile before saving.',
    readLatest: 'Read latest to compare',
    latest: 'Latest saved version',
    compareHelp: 'Reconciliation keeps your edits and adopts remote content you did not change. Overlapping fact changes become conflicts; both source texts are retained.',
    reconcile: 'Reconcile and review',
    replaceLatest: 'Discard local edits and use latest',
    replaceAsk: 'Discard unsaved source and fact edits and use the latest saved version?',
    reconcileDone: 'Reconciled against the latest version. Review conflicts and save again.',
    remoteSource: 'Latest saved source',
    workbookTitle: 'Choose one worksheet and row',
    workbookHelp: "Choose the sheet, row, and columns to import.",
    sheet: 'Worksheet',
    row: 'Data row',
    mapColumn: 'Mapped column',
    unmapped: 'Not mapped / unknown',
    blocked: 'Blocked',
    truncatedSheet: 'Previewing the first 200 rows and 50 columns.',
    mapApply: 'Append this row and review facts',
    mapCancel: 'Close mapping (keep original)',
    mappingDone: 'Selected row appended with cell-level evidence. Review each field.',
    errors: {
      LEGACY_ARCHIVE_REQUIRED: 'The prior draft must be archived before saving revised facts. Your edits remain.',
      CONSENT_REQUIRED: 'Consent to sending the current source text first.',
      NETWORK_ERROR: 'Cannot connect right now. Your edits remain; try again later.',
      REQUEST_FAILED: 'The request did not finish. Your edits remain; try again.',
      SESSION_REFRESHED:'Connection restored. Your action was not retried. Review and try again.', AUTH_REQUIRED: 'Your session expired. Sign in again.',
      CSRF_REJECTED: 'The session changed. Sign in again before retrying.',
      ORIGIN_REJECTED: 'The request origin was not accepted. Use this service’s own page.',
      CASE_NOT_FOUND: 'This case is unavailable to the current account.',
      CASE_CONFLICT: 'The case changed elsewhere. Read the latest version to compare.',
      CASE_INVALID: 'Invalid case content. Check the source and fields.',
      CASE_TOO_LARGE: 'Case content exceeds the limits. Shorten source or fields; nothing is automatically truncated.',
      TEXT_TOO_LARGE: 'Appending would exceed 50,000 characters. Nothing was added. Shorten the source or select relevant passages.',
      SOURCE_EMPTY: 'Provide usable case source text first.',
      ASSET_TYPE_UNSUPPORTED: 'Unsupported file type. Choose one of the listed formats.',
      ASSET_TOO_LARGE: 'The file exceeds 5 MiB. Choose a smaller file.',
      ASSET_EMPTY: 'The file is empty and was not saved.',
      ASSET_QUOTA_EXCEEDED: 'The private archive reached 200 files or 256 MiB.',
      ASSET_FILENAME_INVALID: 'The filename contains unsupported characters. Rename it and retry.',
      ASSET_TEXT_INVALID: 'The text is not valid UTF-8 and was not saved.',
      ASSET_CSV_INVALID: 'The CSV is invalid and was not saved.',
      CSV_INVALID: 'CSV requires the property,owner,pha,caseReference,rent header and exactly one case row. The original remains saved.',
      ASSET_IMAGE_INVALID: 'The image is invalid and was not saved.',
      INVALID_PDF: 'The PDF is damaged or invalid and was not saved.',
      PDF_ENCRYPTED: 'Encrypted PDFs are unsupported. Use a de-identified, unencrypted copy.',
      PDF_UNAVAILABLE: 'Server PDF parsing is unavailable. Try again later.',
      INVALID_WORKBOOK: 'The Excel file cannot be parsed or has no selectable worksheet.',
      WORKBOOK_ENCRYPTED: 'Encrypted Excel files are unsupported. Use a de-identified values-only copy.',
      WORKBOOK_TOO_COMPLEX: 'The workbook exceeds safe preview limits. Use a smaller values-only copy.',
      WORKBOOK_UNAVAILABLE: 'Server Excel parsing is unavailable.',
      MAPPING_INVALID: 'Map at least one field to distinct valid columns; avoid blocked cells.',
      ASSET_CONFLICT: 'The original’s association changed. Refresh before retrying.',
      BUSY: 'The service is busy. Try again shortly.',
      LIVE_DISABLED: 'AI extraction is disabled. Contact your administrator.',
      PROVIDER_ERROR: "Extraction failed. Please try again.",
      EXTRACTION_FAILED: "Extraction failed. Please try again.",
      SENSITIVE_DATA: 'Potential sensitive identifiers were detected and not sent to the model. Remove them and retry.',
      TRIAL_LIMIT_REACHED: 'This account’s extraction allowance has been reached. Try again later.',
      INVALID_RESPONSE: 'The response could not be verified. Current content was not replaced.',
      CAPACITY_REACHED: 'The save capacity limit was reached. Your edits remain.',
      QUEUE_FULL: 'Process at most 10 files at a time. Choose files in smaller batches.'
    }
  }
};
export const wordsFor = lang => intakeCopy[lang] || intakeCopy.zh;
export function errorText(error, words) {
  return words.errors[error?.code] || words.errors.REQUEST_FAILED;
}
