export const assetCopy = {
  zh: {
    warnings: count => `提取说明（${count}）`,
    allTitle: '全部原件', allIntro: '当前账户保存的所有原件，包括尚未关联客户或事项的资料。', allScopes: '全部原件（含未关联）', unassignedOriginal: '未关联客户或事项',
    title: '原始资料', intro: '按事项查找这位客户保存的原件。原件、对话与生成文档分别保留。',
    search: '搜索原始资料', searchPlaceholder: '搜索文件名或可搜索的提取文本',
    searchHint: '仅搜索已保存的文件名和可用提取文本；未做 OCR 的图片文字不会被搜索。',
    caseFilter: '按事项筛选', allCases: '所有事项与客户资料', customerOnly: '客户资料',
    caseLabel: '所属事项', unknownCase: '事项', clear: '清空资料搜索',
    loading: '正在加载原始资料…', refresh: '刷新原始资料', retry: '重新加载原始资料',
    empty: '还没有已保存的原件', emptyHint: '已私有保存并关联这位客户的资料会显示在这里。',
    noMatches: '没有找到匹配的原始资料', noMatchesHint: '试试其他关键词或切换事项。没有可搜索文本的文件仍可按文件名查找。',
    unavailable: '原始资料功能尚未就绪', unavailableHint: '当前服务还不支持原件目录。你仍可使用本页的事项和已保存文档目录。',
    unavailableStorage: '原件存储暂时不可用，请稍后重试。现有事项与文档仍可使用。',
    loadError: '无法加载原始资料，请重试。', sessionExpired: '登录已失效，请重新登录后查看原件。',
    notFound: '原件已不存在，或当前账户无权访问。请刷新目录。',
    invalid: '资料筛选条件无效，请检查后重试。',
    preview: '预览原件', previewNewTab: '预览原件（新标签页）', textPreview: '文本预览',
    download: '下载原件', fileSize: '文件大小', saved: '保存于', recordId: '资料编号', match: '匹配片段',
    textReady: '文本可搜索', textUnavailable: '无可搜索文本', textPending: '文本尚不可用',
    textUnavailableHint: '原件仍可预览或下载。当前没有可供搜索或预览的提取文本。',
    truncated: '文本索引有截断', previous: '上一页资料', next: '下一页资料',
    page: (page, count, total) => `第 ${page} 页 · 本页 ${count} 个，共 ${total} 个`,
    closeText: '关闭文本预览', textLoading: '正在读取提取文本…', textError: '无法读取提取文本，请重试或查看原件。',
    retryText: '重新读取文本', textNote: '这是提取的文本，表格布局或阅读顺序可能与原件不同。请以原件核对。',
    emptyText: '此文件没有可显示的提取文本。', extractionLimited: '这里只显示已保存的有限文本索引；原文件保持完整。',
    externalNote: '预览在同源鉴权的新标签页打开；不会创建公开分享链接。'
  },
  en: {
    warnings: count => `Extraction notes (${count})`,
    allTitle: 'All originals', allIntro: 'Every original saved in this account, including files not yet linked to a customer or case.', allScopes: 'All originals, including unassigned', unassignedOriginal: 'No customer or case linked',
    title: 'Original materials', intro: 'Find this customer’s saved originals by case. Originals, conversations, and generated documents remain separate records.',
    search: 'Search original materials', searchPlaceholder: 'Search filenames or available extracted text',
    searchHint: 'Search covers saved filenames and available extracted text. Image text without OCR is not searchable.',
    caseFilter: 'Filter by case', allCases: 'All cases and customer materials', customerOnly: 'Customer materials',
    caseLabel: 'Case', unknownCase: 'Case', clear: 'Clear material search',
    loading: 'Loading original materials…', refresh: 'Refresh original materials', retry: 'Reload original materials',
    empty: 'No saved originals yet', emptyHint: 'Privately saved files linked to this customer will appear here.',
    noMatches: 'No matching original materials', noMatchesHint: 'Try another keyword or case. Files without searchable text can still be found by filename.',
    unavailable: 'Original materials are not available yet', unavailableHint: 'This server does not yet support the originals directory. You can still use the case and saved-document directories on this page.',
    unavailableStorage: 'Original-file storage is temporarily unavailable. Try again later. Existing cases and documents remain available.',
    loadError: 'Original materials could not be loaded. Please retry.', sessionExpired: 'Your session has expired. Sign in again to view originals.',
    notFound: 'The original no longer exists or is not available to this account. Refresh the directory.',
    invalid: 'The material filters are invalid. Check them and retry.',
    preview: 'Preview original', previewNewTab: 'Preview original (new tab)', textPreview: 'Text preview',
    download: 'Download original', fileSize: 'File size', saved: 'Saved', recordId: 'Material ID', match: 'Matching excerpt',
    textReady: 'Searchable text', textUnavailable: 'No searchable text', textPending: 'Text not available yet',
    textUnavailableHint: 'The original can still be previewed or downloaded. No extracted text is currently available for search or preview.',
    truncated: 'Text index truncated', previous: 'Previous materials page', next: 'Next materials page',
    page: (page, count, total) => `Page ${page} · ${count} shown, ${total} total`,
    closeText: 'Close text preview', textLoading: 'Loading extracted text…', textError: 'Extracted text could not be read. Retry or view the original.',
    retryText: 'Reload text', textNote: 'This is extracted text. Table layout or reading order may differ from the original. Check against the original file.',
    emptyText: 'This file has no extracted text to display.', extractionLimited: 'Only the saved, bounded text index is shown here. The original file is preserved in full.',
    externalNote: 'Previews open in an authenticated, same-origin tab. No public sharing link is created.'
  }
};
export const originalCopy = lang => assetCopy[lang === 'en' ? 'en' : 'zh'];
