export const assetCopy = {
  zh: {
    warnings: count => `提取说明（${count}）`,
    allTitle: '全部原件', allIntro: "查找已保存的文件。", allScopes: '全部原件（含未关联）', unassignedOriginal: '未关联客户或事项',
    title: '原始资料', intro: "查看客户的原件。",
    search: '搜索原始资料', searchPlaceholder: "搜索文件名或文字",
    searchHint: "按文件名或已提取的文字搜索。",
    caseFilter: '按事项筛选', allCases: '所有事项与客户资料', customerOnly: '客户资料',
    caseLabel: '所属事项', unknownCase: '事项', clear: '清空资料搜索',
    loading: '正在加载原始资料…', refresh: '刷新原始资料', retry: '重新加载原始资料',
    empty: '还没有已保存的原件', emptyHint: '已私有保存并关联这位客户的资料会显示在这里。',
    noMatches: '没有找到匹配的原始资料', noMatchesHint: "换个关键词或筛选条件试试。",
    unavailable: "无法加载原件列表", unavailableHint: "请刷新重试。",
    unavailableStorage: "无法读取原件，请稍后重试。",
    loadError: '无法加载原始资料，请重试。', sessionExpired: '登录已失效，请重新登录后查看原件。',
    notFound: '原件已不存在，或当前账户无权访问。请刷新目录。',
    invalid: '资料筛选条件无效，请检查后重试。',
    preview: '预览原件', previewNewTab: '预览原件（新标签页）', textPreview: '文本预览',
    download: '下载原件', fileSize: '文件大小', saved: '保存于', recordId: '资料编号', match: '匹配片段',
    textReady: '文本可搜索', textUnavailable: '无可搜索文本', textPending: '文本尚不可用',
    textUnavailableHint: "可预览或下载原件。",
    truncated: '文本索引有截断', previous: '上一页资料', next: '下一页资料',
    page: (page, count, total) => `第 ${page} 页 · 本页 ${count} 个，共 ${total} 个`,
    closeText: '关闭文本预览', textLoading: '正在读取提取文本…', textError: '无法读取提取文本，请重试或查看原件。',
    retryText: '重新读取文本', textNote: "请对照原件核对文本。",
    emptyText: '此文件没有可显示的提取文本。', extractionLimited: "部分文本，请下载原件查看完整内容。",
    },
  en: {
    warnings: count => `Extraction notes (${count})`,
    allTitle: 'All originals', allIntro: "Find your saved files.", allScopes: 'All originals, including unassigned', unassignedOriginal: 'No customer or case linked',
    title: 'Original materials', intro: "View this customer’s original files.",
    search: 'Search original materials', searchPlaceholder: "Search filenames or text",
    searchHint: "Search filenames or extracted text.",
    caseFilter: 'Filter by case', allCases: 'All cases and customer materials', customerOnly: 'Customer materials',
    caseLabel: 'Case', unknownCase: 'Case', clear: 'Clear material search',
    loading: 'Loading original materials…', refresh: 'Refresh original materials', retry: 'Reload original materials',
    empty: 'No saved originals yet', emptyHint: 'Privately saved files linked to this customer will appear here.',
    noMatches: 'No matching original materials', noMatchesHint: "Try another keyword or filter.",
    unavailable: "Could not load original files", unavailableHint: "Refresh and try again.",
    unavailableStorage: "Could not read original files. Try again later.",
    loadError: 'Original materials could not be loaded. Please retry.', sessionExpired: 'Your session has expired. Sign in again to view originals.',
    notFound: 'The original no longer exists or is not available to this account. Refresh the directory.',
    invalid: 'The material filters are invalid. Check them and retry.',
    preview: 'Preview original', previewNewTab: 'Preview original (new tab)', textPreview: 'Text preview',
    download: 'Download original', fileSize: 'File size', saved: 'Saved', recordId: 'Material ID', match: 'Matching excerpt',
    textReady: 'Searchable text', textUnavailable: 'No searchable text', textPending: 'Text not available yet',
    textUnavailableHint: "Preview or download the original file.",
    truncated: 'Text index truncated', previous: 'Previous materials page', next: 'Next materials page',
    page: (page, count, total) => `Page ${page} · ${count} shown, ${total} total`,
    closeText: 'Close text preview', textLoading: 'Loading extracted text…', textError: 'Extracted text could not be read. Retry or view the original.',
    retryText: 'Reload text', textNote: "Check the text against the original.",
    emptyText: 'This file has no extracted text to display.', extractionLimited: "Partial text. Download the original for the full content.",
    }
};
export const originalCopy = lang => assetCopy[lang === 'en' ? 'en' : 'zh'];
