import {useEffect,useRef,useState} from 'react';
import {useSession} from '@/lib/session';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card';
const words={zh:{title:'服务与使用额度',manual:'服务由所有者人工配置；这里不代表付款、订阅或自动扣费。暂停或到期不影响查看和导出已有资料。',available:'可使用',quota:'本时段额度已用完',paused:'已暂停',expired:'已到期',owner:'所有者',defaults:'默认额度',remaining:'近一小时剩余',used:'已使用',until:'有效期',never:'未设截止日期',refresh:'刷新状态',manage:'配置普通账号的 AI 服务',select:'选择账号',enabled:'允许新 AI 请求',limit:'每小时请求上限（1–30）',expiry:'截止时间（UTC，可留空）',review:'检查变更',confirm:'确认服务变更',cancel:'取消',saving:'正在保存…',saved:'服务配置已保存',error:'服务状态读取或保存失败，请刷新后重试。',conflict:'配置已被修改；已保留输入，请刷新并检查最新状态。',loading:'正在读取服务状态…',usage:'一次聊天或提取计一次，工具轮次包含其中，自动标题另计一次；不是金额上限。普通账号合计每小时最多 30 次。'},en:{title:'Service and usage',manual:'Service is configured manually by the owner. This is not payment, a subscription, or automatic billing. Paused or expired service keeps access to existing records and exports.',available:'Available',quota:'Hourly allowance exhausted',paused:'Paused',expired:'Expired',owner:'Owner',defaults:'Default allowance',remaining:'Remaining in the last hour',used:'Used',until:'Expires',never:'No expiry',refresh:'Refresh status',manage:'Configure AI service for an ordinary account',select:'Choose an account',enabled:'Allow new AI requests',limit:'Requests per hour (1–30)',expiry:'Expiry (UTC, optional)',review:'Review change',confirm:'Confirm service change',cancel:'Cancel',saving:'Saving…',saved:'Service configuration saved',error:'Service status or save failed. Refresh before retrying.',conflict:'The configuration changed elsewhere. Your input was kept; refresh and review the latest status.',loading:'Reading service status…',usage:'A chat/extraction attempt is one unit including tool rounds; an automatic title uses another. This is not a spending cap. Ordinary accounts share 30 per hour.'}};
export function validService(value){return !!value&&typeof value.userId==='string'&&typeof value.enabled==='boolean'&&['available','paused','expired'].includes(value.status)&&['owner','manual','default'].includes(value.mode)&&Number.isSafeInteger(value.version)&&value.version>=0&&Number.isSafeInteger(value.used)&&value.used>=0&&(value.requestsPerHour===null||Number.isInteger(value.requestsPerHour)&&value.requestsPerHour>=1&&value.requestsPerHour<=30)&&(value.expiresAt===null||typeof value.expiresAt==='string'&&Number.isFinite(Date.parse(value.expiresAt)));}
export function ServiceAccessPanel({lang,session,owner}){
 const t=words[lang==='en'?'en':'zh'],{api,status}=session;
 const [service,setService]=useState(null),[accounts,setAccounts]=useState([]),[selected,setSelected]=useState(''),[enabled,setEnabled]=useState(true),[limit,setLimit]=useState('10'),[expiry,setExpiry]=useState(''),[pending,setPending]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const task=useRef(null),generation=useRef(0),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;load();return()=>{mounted.current=false;generation.current++;task.current?.abort();};},[api,status.userId,owner]);
 async function load(){const gen=++generation.current;task.current?.abort();const controller=new AbortController();task.current=controller;setBusy(true);setPending(null);setNotice('');try{const current=await api.get('/api/service',{signal:controller.signal});if(!validService(current.service)||current.service.userId!==status.userId)throw Error('Invalid service');const roster=owner?await api.get('/api/admin/services',{signal:controller.signal}):null;if(roster&&(!Array.isArray(roster.accounts)||roster.accounts.length>101||roster.accounts.some(row=>typeof row.id!=='string'||typeof row.username!=='string'||!validService(row.service)||row.service.userId!==row.id)))throw Error('Invalid roster');if(!mounted.current||gen!==generation.current)return;setService(current.service);if(roster)setAccounts(roster.accounts);await session.refresh?.({signal:controller.signal});}catch(error){if(mounted.current&&gen===generation.current&&error.name!=='AbortError')setNotice(t.error);}finally{if(mounted.current&&gen===generation.current)setBusy(false);}}
 function choose(id){setSelected(id);setPending(null);setNotice('');const value=accounts.find(row=>row.id===id)?.service;if(value){setEnabled(value.enabled);setLimit(String(value.requestsPerHour));setExpiry(value.expiresAt?value.expiresAt.slice(0,16):'');}}
 function review(event){event.preventDefault();const account=accounts.find(row=>row.id===selected);if(!account||selected==='owner')return;let expiresAt=null;if(expiry){const date=new Date(expiry+'Z');if(!Number.isFinite(date.getTime())){setNotice(t.error);return;}expiresAt=date.toISOString();}const requestsPerHour=Number(limit);if(!Number.isInteger(requestsPerHour)||requestsPerHour<1||requestsPerHour>30){setNotice(t.error);return;}setPending({account,body:{enabled,expiresAt,requestsPerHour,expectedVersion:account.service.version}});setNotice('');}
 async function save(){if(!pending||busy)return;const change=pending,gen=++generation.current;task.current?.abort();const controller=new AbortController();task.current=controller;setBusy(true);try{const result=await api.put(`/api/admin/accounts/${encodeURIComponent(change.account.id)}/service`,change.body,{signal:controller.signal});if(!validService(result.service)||result.service.userId!==change.account.id||typeof result.changed!=='boolean'||result.service.enabled!==change.body.enabled||result.service.expiresAt!==change.body.expiresAt||result.service.requestsPerHour!==change.body.requestsPerHour||![change.body.expectedVersion,change.body.expectedVersion+1].includes(result.service.version))throw Error('Invalid result');if(!mounted.current||gen!==generation.current)return;setAccounts(rows=>rows.map(row=>row.id===change.account.id?{...row,service:result.service}:row));setPending(null);setNotice(t.saved);}catch(error){if(mounted.current&&gen===generation.current&&error.name!=='AbortError'){setPending(null);setNotice(error.code==='SERVICE_CONFLICT'?t.conflict:t.error);}}finally{if(mounted.current&&gen===generation.current)setBusy(false);}}
 return <Card><CardHeader><CardTitle>{t.title}</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">{t.manual}</p>{service?<div className="space-y-1 text-sm"><p>{t[service.status==='available'&&service.remaining===0?'quota':service.status]} · {service.mode==='owner'?t.owner:service.mode==='default'?t.defaults:''}</p>{service.mode!=='owner'&&<p>{t.used}: {service.used} · {t.remaining}: {service.remaining} / {service.requestsPerHour}</p>}<p>{t.until}: {service.expiresAt||t.never}</p></div>:<p role="status">{busy?t.loading:t.error}</p>}<p className="text-xs text-muted-foreground">{t.usage}</p><Button type="button" variant="outline" disabled={busy} onClick={load}>{t.refresh}</Button>
 {owner&&<form onSubmit={review} className="space-y-3 border-t pt-4" aria-label={t.manage}><h3 className="font-medium">{t.manage}</h3><Label htmlFor="service-account">{t.select}</Label><select id="service-account" className="w-full rounded border p-2" value={selected} disabled={busy} onChange={e=>choose(e.target.value)}><option value="">{t.select}</option>{accounts.filter(row=>row.id!=='owner').map(row=><option key={row.id} value={row.id}>{row.username} · {t[row.service.status]}</option>)}</select>{selected&&<><label className="flex items-center gap-2"><input type="checkbox" checked={enabled} disabled={busy} onChange={e=>{setEnabled(e.target.checked);setPending(null);}}/>{t.enabled}</label><Label htmlFor="service-limit">{t.limit}</Label><Input id="service-limit" type="number" min="1" max="30" value={limit} disabled={busy} onChange={e=>{setLimit(e.target.value);setPending(null);}}/><Label htmlFor="service-expiry">{t.expiry}</Label><Input id="service-expiry" type="datetime-local" value={expiry} disabled={busy} onChange={e=>{setExpiry(e.target.value);setPending(null);}}/><Button type="submit" disabled={busy}>{t.review}</Button></>}{pending&&<div className="space-y-2 rounded border p-3"><p>{pending.account.username}: {t[!pending.body.enabled?'paused':pending.body.expiresAt&&Date.parse(pending.body.expiresAt)<=Date.now()?'expired':'available']} · {pending.body.requestsPerHour}/h · {pending.body.expiresAt||t.never}</p><Button type="button" disabled={busy} onClick={save}>{busy?t.saving:t.confirm}</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setPending(null)}>{t.cancel}</Button></div>}</form>}{notice&&<p role="status" className="text-sm">{notice}</p>}</CardContent></Card>;
}
export function ServiceAccess({lang='zh',active=true}){const session=useSession(),status=session.status;if(!active||status?.authenticated!==true||!status.userId)return null;const owner=status.userId==='owner'&&status.role==='owner'&&status.canManageAccounts===true;return <ServiceAccessPanel key={`${status.userId}:${status.csrfToken}:${owner}`} session={session} lang={lang} owner={owner}/>;}
