// React/DOM-only authored API fixtures; separate from real HTTP/browser acceptance.
import {before,after,beforeEach,afterEach,test} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {createServer} from 'vite';
let dom,vite,React,createRoot,Panel,root,host;
const state=(userId='synthetic-user',extra={})=>({userId,enabled:true,expiresAt:null,requestsPerHour:10,version:0,updatedAt:null,mode:'default',status:'available',aiAllowed:true,used:0,remaining:10,paymentManaged:false,...extra});
const button=name=>[...host.querySelectorAll('button')].find(b=>b.textContent===name);
const click=async value=>{assert.ok(value);await React.act(async()=>value.click());};
const render=async(api,userId='owner',owner=true)=>React.act(async()=>root.render(React.createElement(Panel,{key:userId,lang:'en',owner,session:{api,status:{userId,csrfToken:'synthetic'}}})));
function fixture(){const calls=[];return{calls,get:async path=>{calls.push({path,method:'GET'});return path==='/api/service'?{service:state('owner',{mode:'owner',requestsPerHour:null,remaining:null})}:{accounts:[{id:'synthetic-user',username:'Synthetic private label',service:state()}]};},put:async(path,body)=>{calls.push({path,body,method:'PUT'});return{changed:true,service:state('synthetic-user',{...body,mode:'manual',version:body.expectedVersion+1,status:body.enabled?'available':'paused'})};}};}
before(async()=>{dom=new JSDOM('<!doctype html><body></body>',{url:'https://synthetic.invalid/',pretendToBeVisual:true});for(const key of ['window','document','navigator','HTMLElement','Element','Node','MutationObserver','Event'])Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true;React=await import('react');({createRoot}=await import('react-dom/client'));vite=await createServer({configFile:'vite.config.js',server:{middlewareMode:true,hmr:false,watch:null,ws:false},appType:'custom'});({ServiceAccessPanel:Panel}=await vite.ssrLoadModule('/features/service-access/index.jsx'));});
beforeEach(()=>{host=document.createElement('div');document.body.append(host);root=createRoot(host);});afterEach(async()=>{await React.act(async()=>root.unmount());host.remove();});after(async()=>{await vite.close();dom.window.close();});
test('ordinary service panel reads only own status and never mounts an admin form',async()=>{const api=fixture();api.get=async path=>{api.calls.push({path});return{service:state()};};await render(api,'synthetic-user',false);assert.deepEqual(api.calls,[{path:'/api/service'}]);assert.equal(host.querySelector('form'),null);assert.ok(host.textContent.includes('Remaining in the last hour: 10'));});
test('owner preview/cancel writes nothing; only explicit confirmation sends a version-bound service change',async()=>{const api=fixture();await render(api);const select=host.querySelector('select');await React.act(async()=>{select.value='synthetic-user';select.dispatchEvent(new Event('change',{bubbles:true}));});await click(host.querySelector('input[type=checkbox]'));await click(button('Review change'));assert.equal(api.calls.filter(x=>x.method==='PUT').length,0);await click(button('Cancel'));assert.equal(api.calls.filter(x=>x.method==='PUT').length,0);await click(button('Review change'));await click(button('Confirm service change'));assert.deepEqual(api.calls.find(x=>x.method==='PUT').body,{enabled:false,expiresAt:null,requestsPerHour:10,expectedVersion:0});assert.ok(host.textContent.includes('Service configuration saved'));});
test('account replacement discards a late owner roster and keeps the new ordinary scope',async()=>{const old=fixture();let resolve;const late=new Promise(done=>resolve=done);old.get=async path=>path==='/api/service'?{service:state('owner',{mode:'owner',requestsPerHour:null,remaining:null})}:late;await render(old);const ordinary=fixture();ordinary.get=async()=>({service:state()});await render(ordinary,'synthetic-user',false);await React.act(async()=>resolve({accounts:[{id:'synthetic-user',username:'Synthetic private label',service:state()}]}));assert.equal(host.querySelector('form'),null);assert.equal(host.textContent.includes('Synthetic private label'),false);});
