const en = {
  draftRestored: "Unsaved document edits restored.",
  cacheUnavailable: "Copy your edits to keep them.",
  title: 'Documents', eyebrow: 'WORKING PAPER / DOCUMENTS', subtitle: "Complete the details, then generate and save a document.",
  signIn: 'Sign in to view your case documents.', selectCase: "Open a case from Customers, or create one in Materials & facts.",
  loading: 'Loading case documents…', retry: 'Try again', reload: 'Reload saved version, keep my edits', reloadNotice: 'The latest saved case is loaded. Your unsaved input is still here; compare it before saving.',
  missingTitle: 'A few details to finish', missingHint: "Complete the required details. Optional fields may stay blank.",
  answer: 'Your answer', savedValue: 'Saved value', confirm: 'Save answers', confirmContinue: 'Save answers & generate final', ready: 'The essential details are ready.',
  kind: 'Document type', kinds: ['Lease-up follow-up', 'Information request', 'Case status summary'], generate: 'Generate final document',
  confirmedDetails: 'Saved facts and document details', source: 'Source', confirmedAt: 'Confirmed', notApplicable: 'Not applicable / explicitly none', notApplicableHelp: 'Not applicable, or explicitly confirmed as none.', pending: 'Needs review', reviewed: 'Confirmed',
  editDetails: 'Edit or add a detail', detail: 'Detail', addAnswer: 'Add to answers', namesVerified: 'Preserve the exact verified names, organizations, addresses and references where needed; the document body is English.',
  issues: 'Case questions', issuesHint: "Track questions and progress.",
  addIssue: 'Add a question', edit: 'Edit', question: 'Question', resolution: 'Answer / resolution', issueStatus: 'Status', statuses: ['Pending', 'Confirmed', 'Resolved'],
  saveIssue: 'Save question', cancel: 'Cancel', noIssues: 'No saved questions for this case.', sourceMessage: 'Conversation source (optional)', chooseConversation: 'Choose a conversation', chooseMessage: 'Choose a message', noSource: 'No message reference',
  user: 'You', assistant: 'Assistant', interrupted: 'Incomplete', versions: 'Document versions', noVersions: 'No saved document versions yet.', open: 'Open', created: 'Created', version: 'Version', draft: 'Draft', final: 'Final', historical: 'Historical',
  stale: 'This version uses earlier case information. It remains readable; generate a fresh final before downloading or printing.',
  preview: 'Document preview', previewHint: "Save your edits as a new version.",
  noPreview: 'Generate a document or open a saved version to preview it.', content: 'English document body', artifactTitle: 'Version title', saveVersion: 'Save new version', saveStatus: 'New version status',
  edited: 'Unsaved edits', copy: 'Copy text', download: 'Download TXT', downloadPdf: 'Download PDF', print: 'Print / Save PDF', copied: 'Copied the displayed text.', saved: 'Saved.', generated: 'Final document saved.',
  archived: 'The earlier case draft has been preserved in document versions.', saveBeforeExport: 'Save this edited version before downloading or printing.',
  material: 'Case material', materialHint: "Import or edit case material.",
  materialText: 'Material text', materialSaved: 'Case material saved.', saveMaterial: 'Save material', materialDirty: 'Save the changed material before generating a document.',
  importFile: 'Import TXT / CSV / PDF / Excel', importConsent: 'I confirm the material is synthetic or de-identified and may be uploaded to this application for parsing.',
  extract: 'Extract with DeepSeek Flash', aiConsent: 'I have checked the processing terms and consent to sending this material to DeepSeek for extraction.',
  extracted: "Extraction complete. Review the results.", extractionHint: "Review and save.",
  facts: 'Review extracted facts', confirmFacts: 'Confirm these facts & save', originalSource: 'Source evidence',
  workbook: 'Choose a sheet, row and column mapping', sheet: 'Sheet', row: 'Row', skip: 'Skip this field', applyMapping: 'Use this reviewed mapping',
  newFileWarning: 'Importing a file replaces only the unsaved material in this page. Save changes you want to keep first.',
  savedMaterial: 'Latest saved material', busy: 'Working…', sourceUnavailable: 'Conversation sources could not be loaded. Your other input is preserved.',
  conflict: 'The case changed elsewhere. Your input is preserved. Reload the saved version and compare before retrying.',
  generic: 'The request could not be completed. Your input is preserved; please try again.',
  errors: {
    AUTH_REQUIRED: 'Your session expired. Sign in again.', CSRF_REJECTED: 'Refresh your sign-in session and retry.', NETWORK_ERROR: 'The connection failed. Your input is preserved.',
    CASE_NOT_FOUND: 'This case is unavailable to your account.', CASE_CONFLICT: 'The case changed elsewhere. Your input is preserved; reload and compare before retrying.',
    DOCUMENT_CONTEXT_CONFLICT: 'A confirmed detail changed elsewhere. Your input is preserved; reload and compare.', DOCUMENT_DETAILS_REQUIRED: 'Some essential information is still missing. Complete the questions shown.',
    DOCUMENT_CONTEXT_INVALID: 'Check the details and their source references.', DOCUMENT_DETAILS_INVALID: 'Check the supplied details, dates and source information.',
    DOCUMENT_CONTENT_INVALID: 'The document is empty, too long or contains unsupported characters.', DOCUMENT_PLACEHOLDERS_REMAIN: 'Remove the remaining placeholders before saving a final version.',
    DOCUMENT_ENGLISH_REQUIRED: 'Keep the document body in English. Exact verified proper names may be preserved.',
    CASE_ISSUE_NOT_FOUND: 'This question is no longer in the case. Reload and compare your input.', CASE_INVALID: 'Check the case values and question fields.', CASE_TOO_LARGE: 'The case exceeds its storage limit. Shorten the material or document.',
    ARTIFACT_STALE: 'This historical final is based on older case information. Generate a fresh final before downloading or printing.',
    ARTIFACT_INVALID: 'Check the document type, title and body.', ARTIFACT_NOT_FOUND: 'This document version is unavailable.', ARTIFACT_SOURCE_INCOMPLETE: 'A final document cannot use an incomplete or unrelated source message.',
    CAPACITY_REACHED: 'This account has reached its storage limit.', LIVE_DISABLED: 'The model service is not enabled. Ask the administrator to configure it.', API_KEY_REQUIRED: 'The administrator must configure the model service.',
    SENSITIVE_DATA: 'Sensitive identifiers were detected. Use only synthetic or thoroughly de-identified material.', DOCUMENT_CONSENT_REQUIRED: 'Confirm that this material may be uploaded for parsing.',
    PDF_UNAVAILABLE: 'PDF parsing is unavailable on the server.', INVALID_PDF: 'This PDF could not be read.', PDF_ENCRYPTED: 'Use an unencrypted, de-identified PDF.', OCR_REQUIRED: 'No readable text was found. Paste reviewed text instead.',
    TEXT_TOO_LARGE: 'The extracted text exceeds 50,000 characters. Use fewer pages or shorter material.', FILE_TOO_LARGE: 'This file is too large.',
    INVALID_WORKBOOK: 'This workbook could not be read.', WORKBOOK_ENCRYPTED: 'Use an unencrypted workbook.', WORKBOOK_TOO_COMPLEX: 'The workbook exceeds the supported complexity.',
    INPUT_INVALID: 'Check the supplied text or file.', INVALID_MAPPING: 'Choose distinct visible plain-value columns.', IMPORT_CONSENT: 'Confirm the upload consent first.', AI_CONSENT: 'Confirm the DeepSeek data-processing consent first.',
    PDF_EXPORT_UNAVAILABLE: 'PDF export is unavailable on this server. Download TXT or use Print instead.', PDF_EXPORT_FAILED: 'PDF export failed. Retry or download TXT.', PDF_EXPORT_BUSY: 'PDF export is busy. Please retry shortly.', PDF_EXPORT_TOO_LARGE: 'This document is too long for PDF export. Download TXT instead.', PDF_EXPORT_UNSUPPORTED_TEXT: 'Some characters cannot be represented faithfully in this PDF. Download TXT or use Print instead.',
    PRINT_BLOCKED: 'The print window was blocked. Allow a popup for this site and retry.', PRINT_FAILED: 'The print page could not be prepared. Download the exact TXT version instead.', CLIPBOARD_FAILED: 'Copy failed. You can select and copy the displayed text.',
    UNSAVED_ARTIFACT: 'Save this edited version before downloading or printing.', UNSAVED_MATERIAL: 'Save the changed case material before generating.', INVALID_RESPONSE: 'The server returned an unexpected response.',
    INVALID_ISSUE: 'Provide a question and, for a resolved item, a nonempty resolution.',
  },
  fields: {property:'Property address',owner:'Owner',pha:'Housing authority',caseReference:'Case reference',rent:'Proposed rent',documentDate:'Document date',recipientName:'Recipient / department',recipientOrganization:'Recipient organization',recipientContact:'Recipient contact/address',salutation:'Salutation',senderName:'Sender name',senderRole:'Sender role',senderOrganization:'Sender organization',senderContact:'Sender contact',attachments:'Actual attachment list',nextActionOwner:'Next-action owner',targetDate:'Target date'},
};
const zh = {
  ...en,
  draftRestored: "已恢复未保存的文档修改。",
  cacheUnavailable: "请复制保留当前修改。",
  title:'文档',eyebrow:'文档',subtitle: "补齐资料，生成并保存文档。",signIn:'请先登录，再查看你的事项文档。',selectCase: "先从客户页打开事项。\n也可前往材料页新建。",loading:'正在加载事项文档…',retry:'重试',reload:'刷新版本',reloadNotice:'已读取最新事项，当前输入仍保留。\n请对照后再保存。',
  missingTitle:'补齐资料',missingHint: "填写必填信息，选填项可留空。",answer:'你的回答',savedValue:'已存内容',confirm:'保存回答',confirmContinue:'保存生成',ready:'所需资料已齐备。',kind:'文档类型',kinds:['跟进信','资料确认','进度摘要'],generate:'生成文档',confirmedDetails:'已存资料',source:'资料出处',confirmedAt:'确认时间',notApplicable:'不适用',notApplicableHelp:'不适用，或已确认没有。',pending:'待核对',reviewed:'已核对',editDetails:'补充资料',detail:'资料项',addAnswer:'加入回答',namesVerified:'我已核实名字、机构、地址和编号。\n需要时保留这些信息的原文。\n文档正文使用英文。',
  issues:'事项问题',issuesHint: "记录问题和处理进度。",addIssue:'新增问题',edit:'编辑',question:'问题',resolution:'处理结果',issueStatus:'状态',statuses:['待补充','已确认','已解决'],saveIssue:'保存问题',cancel:'取消',noIssues:'暂无已保存的问题。',sourceMessage:'消息来源',chooseConversation:'选择对话',chooseMessage:'选择消息',noSource:'不引用',user:'你',assistant:'助手',interrupted:'未完成',versions:'文档版本',noVersions:'暂无已保存版本。',open:'打开',created:'创建时间',version:'版本',draft:'草稿',final:'完成版',historical:'历史版本',stale:'这版文档使用的是旧资料，仍可查看。\n下载或打印前，请生成新的完成版。',preview:'文档预览',previewHint: "修改正文后，另存为新版本。",noPreview:'生成文档或打开已有版本，即可预览。',content:'英文正文',artifactTitle:'版本名称',saveVersion:'另存新版',saveStatus:'版本状态',edited:'尚未保存',copy:'复制正文',download:'下载文本',downloadPdf:'下载 PDF',print:'打印文档',copied:'当前正文已复制。',saved:'已保存。',generated:'完成版已保存。',archived:'原有草稿已保留在文档版本中。',saveBeforeExport:'请先保存这次修改，再下载或打印。',
  material:'事项材料',materialHint: "导入或修改事项材料。",materialText:'材料原文',materialSaved:'事项材料已保存。',saveMaterial:'保存材料',materialDirty:'生成文档前，请先保存已修改的材料。',importFile:'导入文件',importConsent:'我确认材料为虚构，或已去除身份信息。\n同意上传到本应用读取文字。',extract:'提取信息',aiConsent:'我已核对数据处理条款。\n同意将材料发给DeepSeek提取。',extracted: "提取完成，请核对。",extractionHint: "核对后保存。",facts:'核对信息',confirmFacts:'确认保存',originalSource:'原文出处',workbook:'选择数据',sheet:'工作表',row:'数据行',skip:'跳过此项',applyMapping:'确认选列',newFileWarning:'导入会替换本页未保存的材料。\n请先保存需要保留的修改。',savedMaterial:'最新材料',busy:'正在处理…',sourceUnavailable:'暂时无法加载对话来源，其余输入仍保留。',conflict:'事项已在别处修改，输入仍保留。\n请读取最新版本，对照后重试。',generic:'操作未完成，你的输入仍保留，请重试。',
  errors: {
    AUTH_REQUIRED:'登录已过期，请重新登录。',CSRF_REJECTED:'请刷新登录状态后重试。',NETWORK_ERROR:'连接失败，输入仍保留。',CASE_NOT_FOUND:'这个事项不存在或不属于当前账号。',CASE_CONFLICT:'事项已在别处修改，输入仍保留。\n请读取最新版本后对照。',DOCUMENT_CONTEXT_CONFLICT:'已核对的资料有变，输入仍保留。\n请读取最新版本后对照。',DOCUMENT_DETAILS_REQUIRED:'仍缺少关键资料，请补齐页面中的问题。',DOCUMENT_CONTEXT_INVALID:'请检查资料内容及来源引用。',DOCUMENT_DETAILS_INVALID:'请检查资料、日期及来源信息。',DOCUMENT_CONTENT_INVALID:'文档为空、过长或含有不支持的字符。',DOCUMENT_PLACEHOLDERS_REMAIN:'文档仍有待填写标记。\n清除后才能保存完成版。',DOCUMENT_ENGLISH_REQUIRED:'文档正文请使用英文。\n已核实的名字等专名可保留原文。',CASE_ISSUE_NOT_FOUND:'这条问题已不在事项中。\n请刷新后对照当前输入。',CASE_INVALID:'请检查事项资料和问题内容。',CASE_TOO_LARGE:'事项内容过多，请缩短材料或文档。',ARTIFACT_STALE:'这份完成版使用了旧资料。\n请重新生成后，再下载或打印。',ARTIFACT_INVALID:'请检查文档类型、名称和正文。',ARTIFACT_NOT_FOUND:'这版文档不存在或不可访问。',ARTIFACT_SOURCE_INCOMPLETE:'完成版不能引用未完成的消息。\n也不能引用其他事项的消息。',CAPACITY_REACHED:'账号保存空间已满。',LIVE_DISABLED:'助手尚未启用，请联系管理员设置。',API_KEY_REQUIRED:'请联系管理员设置助手。',SENSITIVE_DATA:'检测到敏感身份信息。\n请用虚构材料，或彻底去除身份信息。',DOCUMENT_CONSENT_REQUIRED:'请先允许上传材料并读取文字。',PDF_UNAVAILABLE:'暂时不支持读取PDF。',INVALID_PDF:'无法读取这份 PDF。',PDF_ENCRYPTED:'请用未加密PDF。\n请先去除材料中的身份信息。',OCR_REQUIRED:'没有找到可读文字，请粘贴核对后的文字。',TEXT_TOO_LARGE:'读到的文字超过5万字符。\n请减少页数或缩短材料。',FILE_TOO_LARGE:'文件过大。',INVALID_WORKBOOK:'无法读取这份表格。',WORKBOOK_ENCRYPTED:'请使用未加密的表格。',WORKBOOK_TOO_COMPLEX:'表格超出支持的复杂度。',INPUT_INVALID:'请检查输入文字或文件。',INVALID_MAPPING:'请选择互不重复、可见且不含公式的列。',IMPORT_CONSENT:'请先确认上传授权。',AI_CONSENT:'请先确认向 DeepSeek 发送材料。',PDF_EXPORT_UNAVAILABLE:'暂时无法导出PDF。\n请下载TXT或使用打印。',PDF_EXPORT_FAILED:'PDF导出失败。\n请重试或下载TXT。',PDF_EXPORT_BUSY:'PDF导出繁忙，请稍后重试。',PDF_EXPORT_TOO_LARGE:'文档超出PDF导出限制。\n请下载TXT。',PDF_EXPORT_UNSUPPORTED_TEXT:'部分字符无法在PDF中准确显示。\n请下载TXT或使用打印。',PRINT_BLOCKED:'打印窗口被拦截。\n请允许本站弹出窗口，再重试。',PRINT_FAILED:'打印页面未能打开。\n可下载正文相同的TXT文件。',CLIPBOARD_FAILED:'复制失败，请选中页面正文手动复制。',UNSAVED_ARTIFACT:'请先保存修改后的版本，再下载或打印。',UNSAVED_MATERIAL:'请先保存修改后的事项材料。',INVALID_RESPONSE:'服务器返回了无法识别的结果。',INVALID_ISSUE:'请填写问题。\n标为已解决时，还需填写处理结果。',
  },
  fields:{property:'房屋地址',owner:'业主',pha:'住房机构',caseReference:'事项编号',rent:'申请租金',documentDate:'文档日期',recipientName:'收件方',recipientOrganization:'收件机构',recipientContact:'收件联系',salutation:'称呼',senderName:'发件人',senderRole:'发件身份',senderOrganization:'发件机构',senderContact:'发件联系',attachments:'附件清单',nextActionOwner:'跟进人',targetDate:'目标日期'},
};
export const COPY = Object.freeze({zh, en});
export const documentCopy = lang => COPY[lang === 'en' ? 'en' : 'zh'];
export const documentErrorText = (error, lang) => documentCopy(lang).errors[error?.code || error?.message] || documentCopy(lang).generic;
