const en = {
  draftRestored: "Unsaved document edits restored.",
  cacheUnavailable: "Copy your edits to keep them.",
  title: 'Documents', eyebrow: 'WORKING PAPER / DOCUMENTS', subtitle: "Complete the details, then generate and save a document.",
  signIn: 'Sign in to view your case documents.', selectCase: "Open a case from Customers, or create one in Materials & facts.",
  loading: 'Loading case documents…', retry: 'Try again', reload: 'Reload saved version, keep my edits', reloadNotice: 'The latest saved case is loaded. Your unsaved input is still here; compare it before saving.',
  missingTitle: 'A few details to finish', missingHint: "Complete the required details. Optional fields may stay blank.",
  answer: 'Your answer', savedValue: 'Saved value', confirm: 'Save answers', confirmContinue: 'Save answers & generate final', ready: 'The essential details are ready.',
  kind: 'Document type', kinds: ['Lease-up follow-up', 'Information request', 'Case status summary'], generate: 'Generate final document',
  confirmedDetails: 'Saved facts and document details', source: 'Source', confirmedAt: 'Confirmed', notApplicable: 'Not applicable / explicitly none', pending: 'Needs review', reviewed: 'Confirmed',
  editDetails: 'Edit or add a detail', detail: 'Detail', addAnswer: 'Add to answers', namesVerified: 'Preserve the exact verified names, organizations, addresses and references where needed; the document body is English.',
  issues: 'Case questions', issuesHint: "Track questions and progress.",
  addIssue: 'Add a question', edit: 'Edit', question: 'Question', resolution: 'Answer / resolution', issueStatus: 'Status', statuses: ['Pending', 'Confirmed', 'Resolved'],
  saveIssue: 'Save question', cancel: 'Cancel', noIssues: 'No saved questions for this case.', sourceMessage: 'Conversation source (optional)', chooseConversation: 'Choose a conversation', chooseMessage: 'Choose a message', noSource: 'No message reference',
  user: 'You', assistant: 'Assistant', interrupted: 'Incomplete', versions: 'Document versions', noVersions: 'No saved document versions yet.', open: 'Open', created: 'Created', version: 'Version', draft: 'Draft', final: 'Final', historical: 'Historical',
  stale: 'This version uses earlier case information. It remains readable; generate a fresh final before downloading or printing.',
  preview: 'Document preview', previewHint: "Save your edits as a new version.",
  noPreview: 'Generate a document or open a saved version to preview it.', content: 'English document body', artifactTitle: 'Version title', saveVersion: 'Save new version', saveStatus: 'New version status',
  edited: 'Unsaved edits', copy: 'Copy text', download: 'Download TXT', print: 'Print / Save PDF', copied: 'Copied the displayed text.', saved: 'Saved.', generated: 'Final document saved.',
  archived: 'The earlier case draft has been preserved in document versions.', saveBeforeExport: 'Save this edited version before downloading or printing.',
  material: 'Case material', materialHint: "Import or edit case material.",
  materialText: 'Material text', materialSaved: 'Case material saved.', saveMaterial: 'Save material', materialDirty: 'Save the changed material before generating a document.',
  importFile: 'Import TXT / CSV / PDF / Excel', importConsent: 'I confirm the material is synthetic or de-identified and may be uploaded to this application for parsing.',
  extract: 'Extract with DeepSeek Flash', aiConsent: 'I have checked the processing terms and consent to sending this material to DeepSeek for extraction.',
  extracted: "Extraction complete. Review the results.", extractionHint: "Review and save.",
  facts: 'Review extracted facts', confirmFacts: 'Confirm these facts & save', originalSource: 'Source evidence',
  workbook: 'Choose a sheet, row and column mapping', sheet: 'Sheet', row: 'Row', skip: 'Skip this field', applyMapping: 'Use this reviewed mapping',
  newFileWarning: 'Importing a file replaces only the unsaved material in this page. Save changes you want to keep first.',
  savedMaterial: 'Latest saved material', busy: 'Working…', sourceUnavailable: 'Conversation sources could not be loaded. Your other input is preserved.',
  conflict: 'The case changed elsewhere. Your input is preserved. Reload the saved version and compare before retrying.',
  generic: 'The request could not be completed. Your input is preserved; please try again.',
  errors: {
    AUTH_REQUIRED: 'Your session expired. Sign in again.', CSRF_REJECTED: 'Refresh your sign-in session and retry.', NETWORK_ERROR: 'The connection failed. Your input is preserved.',
    CASE_NOT_FOUND: 'This case is unavailable to your account.', CASE_CONFLICT: 'The case changed elsewhere. Your input is preserved; reload and compare before retrying.',
    DOCUMENT_CONTEXT_CONFLICT: 'A confirmed detail changed elsewhere. Your input is preserved; reload and compare.', DOCUMENT_DETAILS_REQUIRED: 'Some essential information is still missing. Complete the questions shown.',
    DOCUMENT_CONTEXT_INVALID: 'Check the details and their source references.', DOCUMENT_DETAILS_INVALID: 'Check the supplied details, dates and source information.',
    DOCUMENT_CONTENT_INVALID: 'The document is empty, too long or contains unsupported characters.', DOCUMENT_PLACEHOLDERS_REMAIN: 'Remove the remaining placeholders before saving a final version.',
    DOCUMENT_ENGLISH_REQUIRED: 'Keep the document body in English. Exact verified proper names may be preserved.',
    CASE_ISSUE_NOT_FOUND: 'This question is no longer in the case. Reload and compare your input.', CASE_INVALID: 'Check the case values and question fields.', CASE_TOO_LARGE: 'The case exceeds its storage limit. Shorten the material or document.',
    ARTIFACT_STALE: 'This historical final is based on older case information. Generate a fresh final before downloading or printing.',
    ARTIFACT_INVALID: 'Check the document type, title and body.', ARTIFACT_NOT_FOUND: 'This document version is unavailable.', ARTIFACT_SOURCE_INCOMPLETE: 'A final document cannot use an incomplete or unrelated source message.',
    CAPACITY_REACHED: 'This account has reached its storage limit.', LIVE_DISABLED: 'The model service is not enabled. Ask the administrator to configure it.', API_KEY_REQUIRED: 'The administrator must configure the model service.',
    SENSITIVE_DATA: 'Sensitive identifiers were detected. Use only synthetic or thoroughly de-identified material.', DOCUMENT_CONSENT_REQUIRED: 'Confirm that this material may be uploaded for parsing.',
    PDF_UNAVAILABLE: 'PDF parsing is unavailable on the server.', INVALID_PDF: 'This PDF could not be read.', PDF_ENCRYPTED: 'Use an unencrypted, de-identified PDF.', OCR_REQUIRED: 'No readable text was found. Paste reviewed text instead.',
    TEXT_TOO_LARGE: 'The extracted text exceeds 50,000 characters. Use fewer pages or shorter material.', FILE_TOO_LARGE: 'This file is too large.',
    INVALID_WORKBOOK: 'This workbook could not be read.', WORKBOOK_ENCRYPTED: 'Use an unencrypted workbook.', WORKBOOK_TOO_COMPLEX: 'The workbook exceeds the supported complexity.',
    INPUT_INVALID: 'Check the supplied text or file.', INVALID_MAPPING: 'Choose distinct visible plain-value columns.', IMPORT_CONSENT: 'Confirm the upload consent first.', AI_CONSENT: 'Confirm the DeepSeek data-processing consent first.',
    PRINT_BLOCKED: 'The print window was blocked. Allow a popup for this site and retry.', PRINT_FAILED: 'The print page could not be prepared. Download the exact TXT version instead.', CLIPBOARD_FAILED: 'Copy failed. You can select and copy the displayed text.',
    UNSAVED_ARTIFACT: 'Save this edited version before downloading or printing.', UNSAVED_MATERIAL: 'Save the changed case material before generating.', INVALID_RESPONSE: 'The server returned an unexpected response.',
    INVALID_ISSUE: 'Provide a question and, for a resolved item, a nonempty resolution.',
  },
  fields: {property:'Property address',owner:'Owner',pha:'Housing authority',caseReference:'Case reference',rent:'Proposed rent',documentDate:'Document date',recipientName:'Recipient / department',recipientOrganization:'Recipient organization',recipientContact:'Recipient contact/address',salutation:'Salutation',senderName:'Sender name',senderRole:'Sender role',senderOrganization:'Sender organization',senderContact:'Sender contact',attachments:'Actual attachment list',nextActionOwner:'Next-action owner',targetDate:'Target date'},
};
const zh = {
  ...en,
  draftRestored: "已恢复未保存的文档修改。",
  cacheUnavailable: "请复制保留当前修改。",
  title:'文书',eyebrow:'工作纸 / 文书',subtitle: "补齐资料，生成并保存文档。",signIn:'请先登录，再查看你的案件文书。',selectCase: "请先从客户库打开事项，或前往「材料与事实」新建。",loading:'正在加载案件文书…',retry:'重试',reload:'重载已存版本，保留我的输入',reloadNotice:'已载入最新案件，你未保存的输入仍保留。请对照后再保存。',
  missingTitle:'还差几项关键资料',missingHint: "填写必要信息，选填项可留空。",answer:'你的回答',savedValue:'已保存的值',confirm:'保存回答',confirmContinue:'补齐并生成完成版',ready:'关键资料已齐备。',kind:'文书类型',kinds:['租约办理跟进函','资料确认函','案件状态摘要'],generate:'生成完成版',confirmedDetails:'已存事实与文书资料',source:'来源',confirmedAt:'确认时间',notApplicable:'不适用 / 明确没有',pending:'待核实',reviewed:'已确认',editDetails:'修改或补充一项资料',detail:'资料项',addAnswer:'加入待保存回答',namesVerified:'我确认专名、机构、地址与编号已核实，需要时保留原文；文书正文使用英文。',
  issues:'案件问题',issuesHint: "记录问题与处理进度。",addIssue:'新增问题',edit:'编辑',question:'问题',resolution:'回答 / 解决情况',issueStatus:'状态',statuses:['待补充','已确认','已解决'],saveIssue:'保存问题',cancel:'取消',noIssues:'这个案件还没有已保存的问题。',sourceMessage:'对话来源（可选）',chooseConversation:'选择对话',chooseMessage:'选择消息',noSource:'不引用消息',user:'你',assistant:'助手',interrupted:'未完成',versions:'文书版本',noVersions:'还没有已保存的文书版本。',open:'打开',created:'创建时间',version:'版本',draft:'草稿',final:'完成版',historical:'历史版本',stale:'这版文书基于较早的案件资料，仍可查阅；下载或打印前请生成新的完成版。',preview:'文书预览',previewHint: "编辑正文后，保存为新版本。",noPreview:'生成文书或打开一个历史版本后，可在这里预览。',content:'英文文书正文',artifactTitle:'版本名称',saveVersion:'另存为新版本',saveStatus:'新版本状态',edited:'有未保存的修改',copy:'复制正文',download:'下载 TXT',print:'打印 / 保存 PDF',copied:'已复制当前显示的正文。',saved:'已保存。',generated:'完成版已保存。',archived:'之前的案件草稿已保留在文书版本里。',saveBeforeExport:'请先保存这次修改，再下载或打印。',
  material:'案件材料',materialHint: "导入或编辑案件材料。",materialText:'材料文本',materialSaved:'案件材料已保存。',saveMaterial:'保存材料',materialDirty:'生成文书前，请先保存已修改的材料。',importFile:'导入 TXT / CSV / PDF / Excel',importConsent:'我确认材料为虚构或已去标识化，同意上传至本应用进行解析。',extract:'使用 DeepSeek Flash 提取',aiConsent:'我已核对数据处理条款，同意将材料发送给 DeepSeek 提取。',extracted: "提取完成，请核对。",extractionHint: "核对后保存。",facts:'核对提取结果',confirmFacts:'确认这些事实并保存',originalSource:'原始依据',workbook:'选择工作表、行和列映射',sheet:'工作表',row:'行',skip:'跳过此项',applyMapping:'使用此映射',newFileWarning:'导入会替换此页尚未保存的材料，请先保存需要保留的修改。',savedMaterial:'最新已存材料',busy:'正在处理…',sourceUnavailable:'暂时无法加载对话来源，其余输入仍保留。',conflict:'案件已在别处修改，你的输入仍保留。请重载最新版本，对照后再试。',generic:'操作未完成，你的输入仍保留，请重试。',
  errors: {
    AUTH_REQUIRED:'登录已过期，请重新登录。',CSRF_REJECTED:'请刷新登录状态后重试。',NETWORK_ERROR:'连接失败，输入仍保留。',CASE_NOT_FOUND:'这个案件不存在或不属于当前账户。',CASE_CONFLICT:'案件已在别处修改，输入仍保留，请重载后对照。',DOCUMENT_CONTEXT_CONFLICT:'已确认资料发生变化，输入仍保留，请重载后对照。',DOCUMENT_DETAILS_REQUIRED:'仍缺少关键资料，请补齐页面中的问题。',DOCUMENT_CONTEXT_INVALID:'请检查资料内容及来源引用。',DOCUMENT_DETAILS_INVALID:'请检查资料、日期及来源信息。',DOCUMENT_CONTENT_INVALID:'文书为空、过长或含有不支持的字符。',DOCUMENT_PLACEHOLDERS_REMAIN:'文书仍有占位符，清除后才能保存完成版。',DOCUMENT_ENGLISH_REQUIRED:'文书正文请使用英文，已核实的专名可以保留原文。',CASE_ISSUE_NOT_FOUND:'这条问题已不在案件中，请重载后对照输入。',CASE_INVALID:'请检查案件资料与问题字段。',CASE_TOO_LARGE:'案件超过存储限制，请缩短材料或文书。',ARTIFACT_STALE:'这是基于旧资料的历史完成版，请重新生成后再下载或打印。',ARTIFACT_INVALID:'请检查文书类型、名称和正文。',ARTIFACT_NOT_FOUND:'这版文书不存在或不可访问。',ARTIFACT_SOURCE_INCOMPLETE:'完成版不能引用未完成或无关案件的消息。',CAPACITY_REACHED:'账户已达到存储上限。',LIVE_DISABLED:'模型服务尚未启用，请联系管理员配置。',API_KEY_REQUIRED:'请管理员配置模型服务。',SENSITIVE_DATA:'检测到敏感标识，请仅使用虚构或充分去标识化的材料。',DOCUMENT_CONSENT_REQUIRED:'请先确认允许上传材料进行解析。',PDF_UNAVAILABLE:'服务器暂不支持 PDF 解析。',INVALID_PDF:'无法读取这份 PDF。',PDF_ENCRYPTED:'请使用未加密、已去标识化的 PDF。',OCR_REQUIRED:'没有找到可读文本，请粘贴核对后的文字。',TEXT_TOO_LARGE:'提取文本超过 50,000 字符，请减少页数或缩短材料。',FILE_TOO_LARGE:'文件过大。',INVALID_WORKBOOK:'无法读取这份表格。',WORKBOOK_ENCRYPTED:'请使用未加密的表格。',WORKBOOK_TOO_COMPLEX:'表格超出支持的复杂度。',INPUT_INVALID:'请检查输入文本或文件。',INVALID_MAPPING:'请选择互不重复、可见且不含公式的列。',IMPORT_CONSENT:'请先确认上传授权。',AI_CONSENT:'请先确认向 DeepSeek 发送材料。',PRINT_BLOCKED:'打印窗口被拦截，请允许本站弹出窗口后重试。',PRINT_FAILED:'未能准备打印页面，可以下载相同正文的 TXT 文件。',CLIPBOARD_FAILED:'复制失败，请选中页面正文手动复制。',UNSAVED_ARTIFACT:'请先保存修改后的版本，再下载或打印。',UNSAVED_MATERIAL:'请先保存修改后的案件材料。',INVALID_RESPONSE:'服务器返回了无法识别的结果。',INVALID_ISSUE:'请填写问题；标为已解决时，还需填写解决情况。',
  },
  fields:{property:'房屋地址',owner:'业主',pha:'住房机构',caseReference:'案件编号',rent:'拟议租金',documentDate:'文书日期',recipientName:'收件人 / 部门',recipientOrganization:'收件机构',recipientContact:'收件地址 / 联系方式',salutation:'称呼',senderName:'发件人姓名',senderRole:'发件人角色',senderOrganization:'发件机构',senderContact:'发件人联系方式',attachments:'实际附件清单',nextActionOwner:'下一步负责人',targetDate:'目标日期'},
};
export const COPY = Object.freeze({zh, en});
export const documentCopy = lang => COPY[lang === 'en' ? 'en' : 'zh'];
export const documentErrorText = (error, lang) => documentCopy(lang).errors[error?.code || error?.message] || documentCopy(lang).generic;
