// Development DOM + real local HTTP/SQLite acceptance. No response-success mocks or provider calls.
// This is not a real browser, CSP/layout/keyboard acceptance, or production-data test.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, realpath, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawn } from 'node:child_process';
import { randomBytes, scryptSync } from 'node:crypto';
import net from 'node:net';
import { JSDOM } from 'jsdom';
import { createServer as createViteServer } from 'vite';
import { openStorage } from '../../../storage.js';

test('realHTTP + controlledDOM: documents confirm, generate, export, preserve conflicts and persist metadata-only observations', {timeout:30000}, async context => {
  const directory = await mkdtemp(join(await realpath(tmpdir()), 'nestlet-react-documents-'));
  const filename = join(directory, 'nestlet.sqlite');
  const storage = openStorage({filename});
  const record = storage.createCase('owner', {title:'Synthetic Johnny case',sourceText:'Synthetic source evidence',draftType:'followup',draftText:'EARLIER HUMAN-EDITED LETTER',
    fields:['property','owner','pha','caseReference','rent'].map(key => ({key,value:'',source:'Synthetic working copy',confirmed:true,conflict:false}))});
  const other = storage.createCase('owner', {title:'Independent second case',sourceText:'SECOND CASE ONLY',draftType:'followup',draftText:'',fields:[]});
  storage.close();
  const password = 'public-react-document-test-password', salt = randomBytes(16);
  const hash = `scrypt$${salt.toString('base64url')}$${scryptSync(password,salt,32).toString('base64url')}`;
  const reservation = net.createServer(); await new Promise(resolve => reservation.listen(0,'127.0.0.1',resolve));
  const port = reservation.address().port; await new Promise(resolve => reservation.close(resolve));
  const base = `http://127.0.0.1:${port}`;
  const child = spawn(process.execPath,['server.js'],{cwd:new URL('../../../',import.meta.url),env:{...process.env,HOST:'127.0.0.1',PORT:String(port),PUBLIC_ORIGIN:'',NESTLET_DB_PATH:filename,NESTLET_OPERATOR_USERNAME:'owner',NESTLET_OPERATOR_PASSWORD_HASH:hash,DEEPSEEK_API_KEY:'',ENABLE_LIVE_AI:'false',DEEPSEEK_MODEL:'deepseek-flash'},stdio:['ignore','pipe','pipe']});
  let output = ''; child.stdout.on('data',data => output += data); child.stderr.on('data',data => output += data);
  context.after(async () => {if (child.exitCode === null) await new Promise(resolve => {child.once('exit',resolve);child.kill('SIGTERM');});await rm(directory,{recursive:true,force:true});});
  await new Promise((resolve,reject) => {const timer=setTimeout(()=>reject(new Error(output)),5000);child.once('exit',code=>{clearTimeout(timer);reject(new Error(`Server exited ${code}`));});child.stdout.on('data',data=>{if(data.toString().includes('Nestlet available')){clearTimeout(timer);resolve();}});});
  const originalFetch = globalThis.fetch;
  const login = await originalFetch(base+'/api/login',{method:'POST',headers:{Origin:base,'Content-Type':'application/json'},body:JSON.stringify({password})});
  assert.equal(login.status,200); const loginBody = await login.json(), cookie=login.headers.get('set-cookie').split(';')[0];
  const request = async (path,method='GET',body) => originalFetch(base+path,{method,headers:{Origin:base,Cookie:cookie,'X-CSRF-Token':loginBody.csrfToken,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
  const dom = new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>',{url:base+'/next/',pretendToBeVisual:true});
  const globals = new Map(), set = (key,value) => {globals.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});};
  const clipboard=[],downloads=[],prints=[],requests=[],blobs=new Map();
  let delayedPath=null, releaseDelayed, delayedStarted;
  const savedCreate=URL.createObjectURL,savedRevoke=URL.revokeObjectURL;
  set('window',dom.window);set('document',dom.window.document);set('navigator',{userAgent:dom.window.navigator.userAgent,clipboard:{writeText:async value=>clipboard.push(value)}});
  set('HTMLElement',dom.window.HTMLElement);set('HTMLInputElement',dom.window.HTMLInputElement);set('getComputedStyle',dom.window.getComputedStyle.bind(dom.window));set('IS_REACT_ACT_ENVIRONMENT',true);
  set('ResizeObserver',class {observe(){} unobserve(){} disconnect(){}});
  set('fetch',async (path,options={}) => {
    if (typeof path !== 'string' || !path.startsWith('/api/')) return originalFetch(path,options);
    requests.push({path,options});
    const response = await originalFetch(base+path,{...options,headers:{...options.headers,Origin:base,Cookie:cookie}});
    if (path === delayedPath) {delayedStarted?.(); await new Promise(resolve=>{releaseDelayed=resolve;});}
    return response;
  });
  URL.createObjectURL=blob=>{const id=`blob:${base}/${blobs.size}`;blobs.set(id,blob);return id;};URL.revokeObjectURL=()=>{};
  dom.window.HTMLAnchorElement.prototype.click=function(){if(this.download)downloads.push({filename:this.download,blob:blobs.get(this.href)});};
  dom.window.confirm=()=>true;
  dom.window.open=()=>{
    const popup=new JSDOM('<!doctype html><html><head></head><body></body></html>',{url:base+'/next/',pretendToBeVisual:true}).window;
    popup.focus=()=>{};popup.print=()=>prints.push(popup.document.body.textContent);
    const append=popup.document.head.append.bind(popup.document.head);
    popup.document.head.append=(...nodes)=>{append(...nodes);for(const node of nodes)if(node.tagName==='LINK')setTimeout(()=>node.dispatchEvent(new popup.Event('load')),0);};
    return popup;
  };
  const vite=await createViteServer({server:{middlewareMode:true,hmr:false,ws:false,watch:null},appType:'custom',logLevel:'error'});
  context.after(()=>vite.close());
  const {DocumentsPage}=await vite.ssrLoadModule('/features/documents/index.jsx');
  const {SessionProvider,useSession}=await vite.ssrLoadModule('/lib/session.jsx');
  const React=await import('react'),{createRoot}=await import('react-dom/client');
  let journey;
  function Scope({id,children}) {
    const session=useSession(); journey=session.journey;
    React.useLayoutEffect(()=>{if(session.status.authenticated){journey.setScope({workspaceKey:record.id,caseId:id});journey.visit('documents');}},[id,session.status.authenticated,journey]);
    return children;
  }
  const root=createRoot(dom.window.document.getElementById('root'));
  context.after(async()=>{await React.act(async()=>root.unmount());dom.window.close();URL.createObjectURL=savedCreate;URL.revokeObjectURL=savedRevoke;for(const[key,descriptor]of globals){if(descriptor)Object.defineProperty(globalThis,key,descriptor);else delete globalThis[key];}});
  const render=async id=>React.act(async()=>root.render(React.createElement(SessionProvider,null,React.createElement(Scope,{id},React.createElement(DocumentsPage,{lang:'en',caseId:id})))));
  const waitFor=async predicate=>{const end=Date.now()+8000;while(!predicate()){if(Date.now()>end)throw new Error('DOM wait timed out: '+dom.window.document.body.textContent);await React.act(async()=>{await new Promise(resolve=>setTimeout(resolve,15));});}};
  const idle=()=>waitFor(()=>![...dom.window.document.querySelectorAll('[role="status"]')].some(item=>item.textContent==='Working…'));
  const button=text=>[...dom.window.document.querySelectorAll('button')].find(item=>item.textContent.trim()===text);
  const click=async text=>{const item=button(text);assert.ok(item,text);assert.equal(item.disabled,false,text);await React.act(async()=>item.click());await idle();};
  const enter=async (id,value)=>{const element=dom.window.document.getElementById(id);assert.ok(element,id);assert.equal(element.disabled,false,id);const prototype=element.tagName==='TEXTAREA'?dom.window.HTMLTextAreaElement.prototype:dom.window.HTMLInputElement.prototype;await React.act(async()=>{Object.getOwnPropertyDescriptor(prototype,'value').set.call(element,value);element.dispatchEvent(new dom.window.Event('input',{bubbles:true}));});};
  await render(record.id);await waitFor(()=>dom.window.document.getElementById('document-answer-property'));await idle();
  for(const[key,value]of Object.entries({property:'128 Example Lane',recipientName:'Example Intake Team',recipientContact:'intake@example.invalid',senderName:'Example Sender',senderContact:'sender@example.invalid'}))await enter('document-answer-'+key,value);
  await click('Save answers & generate final');
  await waitFor(()=>dom.window.document.getElementById('document-body')?.value.includes('Supplementary correspondence;'));
  const current=await (await request(`/api/cases/${record.id}`)).json();
  assert.equal(current.case.fields.find(item=>item.key==='property').value,'128 Example Lane');
  assert.equal(current.case.documentContext.recipientName.confirmed,true);assert.equal(current.case.draftText,'');
  const patchRequest=requests.find(item=>item.options.method==='PATCH'&&item.path.endsWith('/document-context'));
  const patchBody=JSON.parse(patchRequest.options.body);assert.ok(patchBody.factChanges.property);assert.equal('property'in patchBody.changes,false);
  const artifacts=(await (await request(`/api/cases/${record.id}/artifacts`)).json()).artifacts;
  assert.equal(artifacts.length,2);const final=artifacts.find(item=>item.status==='final'),archived=artifacts.find(item=>item.status==='draft');
  const finalBody=(await (await request(`/api/artifacts/${final.id}`)).json()).artifact.content;
  assert.equal(dom.window.document.getElementById('document-body').value,finalBody);assert.doesNotMatch(finalBody,/\bDRAFT\b|NOT FOR SUBMISSION|DE-IDENTIFIED/u);
  await click('Copy text');await waitFor(()=>clipboard.length===1);assert.equal(clipboard[0],finalBody);
  await click('Download TXT');await waitFor(()=>downloads.length===1);assert.equal(await downloads[0].blob.text(),finalBody);
  await click('Print / Save PDF');await waitFor(()=>prints.length===1);assert.equal(prints[0],finalBody);
  await click('Add a question');await enter('document-issue-question','Which secure channel should be used?');await enter('document-issue-resolution','Confirmed the example agency secure channel.');
  await React.act(async()=>{const select=dom.window.document.getElementById('document-issue-status');select.value='resolved';select.dispatchEvent(new dom.window.Event('change',{bubbles:true}));});
  await click('Save question');await waitFor(()=>!dom.window.document.getElementById('document-issue-question'));
  const updated=(await(await request(`/api/cases/${record.id}`)).json()).case;assert.equal(updated.caseIssues[0].status,'resolved');
  await click('Download TXT');await waitFor(()=>dom.window.document.body.textContent.includes('Generate a fresh final before downloading or printing.'));
  assert.equal(downloads.length,1);assert.equal(dom.window.document.getElementById('document-body').value,finalBody);
  await enter('document-body',finalBody+'\nAn unsaved human edit.');
  const changed=await request(`/api/cases/${record.id}/issues`,'PATCH',{changes:[{question:'Separate update',status:'pending',resolution:''}],expectedVersion:updated.version});assert.equal(changed.status,200);
  await click('Save new version');await waitFor(()=>dom.window.document.body.textContent.includes('The case changed elsewhere.'));
  assert.ok(dom.window.document.getElementById('document-body').value.endsWith('An unsaved human edit.'));
  await React.act(async()=>button('Reload saved version, keep my edits').click());await waitFor(()=>dom.window.document.body.textContent.includes('The latest saved case is loaded.'));await idle();
  assert.ok(dom.window.document.getElementById('document-body').value.endsWith('An unsaved human edit.'));
  await click('Save new version');await waitFor(()=>!dom.window.document.body.textContent.includes('Unsaved edits'));
  await journey.flush();
  const eventRequest=requests.find(item=>/^\/api\/workflows\/[0-9a-f-]{36}\/events$/u.test(item.path));
  assert.ok(eventRequest,'Actual feature actions sent workflow events over HTTP');
  const observedResponse=await request(eventRequest.path);assert.equal(observedResponse.status,200);
  const observed=(await observedResponse.json()).events.filter(item=>item.source==='client');
  for(const event of ['review.confirm','draft.generate','draft.edit','export.copy','export.download','export.print']) assert.ok(observed.some(item=>item.event===event&&item.outcome==='success'),event);
  assert.equal(observed.filter(item=>item.event==='review.confirm').length,1);
  assert.equal(observed.filter(item=>item.event==='draft.generate').length,1);
  assert.ok(observed.some(item=>item.event==='export.download'&&item.outcome==='failure'));
  assert.ok(observed.some(item=>item.event==='draft.edit'&&item.outcome==='failure'));
  assert.ok(observed.every(item=>item.caseId===record.id&&item.requestId===null),'Feature JSON calls do not expose correlation headers; no IDs are invented');
  for(const privateText of ['Synthetic Johnny case','Synthetic source evidence','128 Example Lane','intake@example.invalid','An unsaved human edit.',password,loginBody.csrfToken]) assert.equal(JSON.stringify(observed).includes(privateText),false);
  delayedPath=`/api/artifacts/${archived.id}`;
  const started=new Promise(resolve=>{delayedStarted=resolve;});
  await React.act(async()=>dom.window.document.querySelector(`[data-artifact-id="${archived.id}"] button`).click());await started;
  await render(other.id);await waitFor(()=>dom.window.document.body.textContent.includes('Independent second case'));
  delayedPath=null;releaseDelayed();await React.act(async()=>{await new Promise(resolve=>setTimeout(resolve,30));});
  assert.doesNotMatch(dom.window.document.body.textContent,/EARLIER HUMAN-EDITED LETTER|Synthetic Johnny case/);
  assert.equal(requests.some(item=>item.path==='/api/extract'||item.path==='/api/chat'),false);
  await idle();
  await React.act(async()=>root.unmount());
});
