import {test,expect,signInCustomer,createCustomer,apiWrite,getJson,responseFor,customerRecord} from './customer-case-support.js';
import {navigate,watchBrowser,screenshot,noHorizontalOverflow} from './support.js';

for(const width of [1440,390])test(`experience report: associate, rename, review and delete a case at ${width}px`,async({page,customerApp:app},testInfo)=>{
 await page.setViewportSize({width,height:900});const assertClean=await watchBrowser(page);
 await signInCustomer(page,app);const client=await createCustomer(page,'Synthetic experience client');
 const fields=['property','owner','pha','caseReference','rent'].map(key=>({key,value:{property:'128 Synthetic Lane',owner:'Synthetic Owner',pha:'SFHA',caseReference:'',rent:'$3400'}[key],source:'Synthetic user test',confirmed:key!=='pha'&&key!=='caseReference',conflict:false}));
 const payload={title:'Synthetic unassigned experience',sourceText:'Synthetic original notes',fields,draftType:'followup',draftText:'',namesVerified:true};
 const created=await apiWrite(page,app,'/api/cases','POST',payload);expect(created.status()).toBe(201);let record=(await created.json()).case;
 const details={recipientName:{value:'Synthetic recipient'},recipientContact:{value:'recipient@example.invalid'},senderName:{value:'Synthetic sender'},senderContact:{value:'sender@example.invalid'}};
 const reviewed=await apiWrite(page,app,`/api/cases/${record.id}/document-context`,'PATCH',{changes:details,confirm:true,expectedVersion:record.version});expect(reviewed.status()).toBe(200);record=(await reviewed.json()).case;
 const confirmedContext=record.documentContext;
 // Seed only fixture content through authenticated public endpoints. No paid provider.
 const conv=await apiWrite(page,app,`/api/cases/${record.id}/conversations`,'POST',{title:'Synthetic retained conversation'});expect(conv.status()).toBe(201);const conversation=(await conv.json()).conversation;
 const draft=await apiWrite(page,app,`/api/cases/${record.id}/artifacts`,'POST',{kind:'followup',title:'Synthetic draft',status:'draft',content:'Synthetic supplementary letter.',expectedCaseVersion:record.version});expect(draft.status()).toBe(201);const artifact=(await draft.json()).artifact;
 const {csrfToken}=await getJson(page,app,'/api/status');
 const uploaded=await page.request.post(app.origin+'/api/assets',{headers:{Origin:app.origin,'X-CSRF-Token':csrfToken,'X-Asset-Consent':'persist-private','Content-Type':'text/plain','X-Asset-Filename':'synthetic-experience.txt'},data:Buffer.from('Synthetic original to retain.')});
 expect(uploaded.status()).toBe(201);const asset=(await uploaded.json()).asset;
 const linkAsset=await apiWrite(page,app,`/api/assets/${asset.id}`,'PATCH',{caseId:record.id,expectedVersion:asset.version});expect(linkAsset.status()).toBe(200);
 await navigate(page,'Conversation');await navigate(page,'Customers');
 const manage=()=>page.getByRole('region',{name:'Manage case',exact:true});
 await page.getByRole('button',{name:`Manage case: ${record.title}`,exact:true}).click();
 await expect(manage().getByLabel('Case title',{exact:true})).toHaveValue(record.title);
 if(width===390){const heading=page.getByRole('region',{name:'Saved cases',exact:true}).getByRole('heading',{name:record.title,exact:true});expect((await heading.boundingBox()).width).toBeGreaterThan(160);}
 await noHorizontalOverflow(page);
 await manage().getByLabel('Customer',{exact:true}).selectOption(client.id);
 await manage().getByLabel('Case title',{exact:true}).fill('Synthetic renamed experience');
 const saved=responseFor(page,`/api/cases/${record.id}`,'PUT');await manage().getByRole('button',{name:'Save changes',exact:true}).click();expect((await saved).status()).toBe(200);
 record=(await getJson(page,app,`/api/cases/${record.id}`)).case;
 expect(record.documentContext).toEqual(confirmedContext);
 expect(record).toMatchObject({clientId:client.id,title:'Synthetic renamed experience',sourceText:payload.sourceText,fields});
 await expect(customerRecord(page)).toContainText(record.title);
 await page.getByRole('button',{name:`Open saved case: ${record.title}`,exact:true}).click();
 await navigate(page,'Materials & facts');
 const review=page.getByRole('region',{name:'Fact review result',exact:true});await expect(review).toContainText('Needs review');await expect(review).toContainText('Not supplied');
 await expect(page.getByRole('button',{name:'Choose materials',exact:true})).toBeVisible();
 await navigate(page,'Documents');await page.getByTestId('official-preparation').locator('summary').click();
 await expect(page.getByTestId('official-preparation')).toContainText('not completed RTA forms');
 await expect(page.getByTestId('official-preparation').getByRole('link',{name:/SFHA HUD-52517/})).toHaveAttribute('href',/sfha.org/);
 await expect(page.getByTestId('documents-page')).toContainText('The supplementary document details are ready.');
 if(width===390)await page.getByRole('button',{name:'Open case context',exact:true}).click();
 const guidance=page.getByTestId('agency-guidance');await guidance.locator('summary').first().click();
 await guidance.getByLabel('Reference agency (not confirmed for this case)',{exact:true}).selectOption('oha');
 await expect(page.getByRole('alert').filter({hasText:'reference agency differs'})).toBeVisible();
 await page.getByRole('button',{name:'Use case agency for references',exact:true}).click();
 expect((await getJson(page,app,`/api/cases/${record.id}`)).case.fields.find(field=>field.key==='pha')).toEqual(fields.find(field=>field.key==='pha'));
 if(width===390)await page.getByRole('button',{name:'Close context',exact:true}).click();
 await screenshot(page,testInfo,`experience-documents-${width}`);
 await navigate(page,'Customers');await page.getByRole('button',{name:`Manage case: ${record.title}`,exact:true}).click();
 await expect(manage().getByLabel('Customer',{exact:true})).toHaveValue(client.id);
 await manage().getByLabel('Customer',{exact:true}).selectOption('');
 const unlinked=responseFor(page,`/api/cases/${record.id}`,'PUT');await manage().getByRole('button',{name:'Save changes',exact:true}).click();expect((await unlinked).status()).toBe(200);
 await customerRecord(page).getByRole('button',{name:'Link existing case',exact:true}).click();
 await customerRecord(page).getByLabel('Existing case',{exact:true}).selectOption(record.id);
 await expect(manage().getByLabel('Customer',{exact:true})).toHaveValue(client.id);
 const relinked=responseFor(page,`/api/cases/${record.id}`,'PUT');await manage().getByRole('button',{name:'Save changes',exact:true}).click();expect((await relinked).status()).toBe(200);
 await page.getByRole('button',{name:`Manage case: ${record.title}`,exact:true}).click();
 await manage().getByRole('button',{name:'Delete case',exact:true}).click();
 await expect(manage()).toContainText('Saved original files remain');
 await manage().getByRole('button',{name:'Cancel',exact:true}).last().click();expect((await page.request.get(app.origin+`/api/cases/${record.id}`)).status()).toBe(200);
 await manage().getByRole('button',{name:'Delete case',exact:true}).click();await screenshot(page,testInfo,`experience-delete-${width}`);
 const deleted=responseFor(page,`/api/cases/${record.id}`,'DELETE');await manage().getByRole('button',{name:'Confirm deletion',exact:true}).click();expect((await deleted).status()).toBe(200);
 await expect(page.getByRole('button',{name:`Manage case: ${record.title}`,exact:true})).toHaveCount(0);
 for(const path of [`/api/cases/${record.id}`,`/api/conversations/${conversation.id}`,`/api/artifacts/${artifact.id}`])expect((await page.request.get(app.origin+path)).status()).toBe(404);
 const remaining=await getJson(page,app,`/api/assets/${asset.id}`);expect(remaining.asset.caseId).toBe(null);
 expect((await page.request.get(app.origin+`/api/assets/${asset.id}/download`)).status()).toBe(200);
 await navigate(page,'Conversation');
 await expect(page.locator('[data-feature="chat"]')).not.toHaveAttribute('data-case-id',record.id);
 await assertClean();
});

test('a remote deletion followed by a failed rename preserves unsaved case material',async({page,customerApp:app})=>{
 await signInCustomer(page,app);
 const created=await apiWrite(page,app,'/api/cases','POST',{title:'Synthetic remote deletion',sourceText:'Saved synthetic material',fields:[],draftType:'followup',draftText:''});expect(created.status()).toBe(201);const record=(await created.json()).case;
 await navigate(page,'Customers');await page.getByRole('button',{name:`Open saved case: ${record.title}`,exact:true}).click();
 await navigate(page,'Materials & facts');await page.getByLabel('Case source text',{exact:true}).fill('Unsaved synthetic material must survive');
 await navigate(page,'Customers');await page.getByRole('button',{name:`Manage case: ${record.title}`,exact:true}).click();
 const manage=page.getByRole('region',{name:'Manage case',exact:true});await expect(manage.getByLabel('Case title',{exact:true})).toHaveValue(record.title);
 const removed=await apiWrite(page,app,`/api/cases/${record.id}`,'DELETE',{expectedVersion:record.version});expect(removed.status()).toBe(200);
 const rejected=responseFor(page,`/api/cases/${record.id}`,'PUT');await manage.getByRole('button',{name:'Save changes',exact:true}).click();expect((await rejected).status()).toBe(404);
 await manage.getByRole('button',{name:'Back to list',exact:true}).click();
 await expect(page.getByText('Case unavailable. Workspace drafts were not discarded.',{exact:true})).toBeVisible();
 await navigate(page,'Materials & facts');await expect(page.getByLabel('Case source text',{exact:true})).toHaveValue('Unsaved synthetic material must survive');
});
