const zh = {
  title: '账号管理',
  description: '只有所有者能查看账号列表。\n也只有所有者能更改管理员权限。',
  boundary: '管理员只能查看部分运行状态。\n不能查看其他用户的事项和文件。\n不能查看服务商密钥或设置。\n不能查看账号授权或全站运行数据。\n每个账号只能访问自己的资料。',
  owner: '所有者', administrator: '管理员', ordinary: '普通用户',
  ownerReason: '所有者权限不能在这里修改。',
  bindFirst: '请先让此账号绑定并验证邮箱。\n完成后才能设置为管理员。',
  unavailable: '此账号目前不能被授予管理员权限。',
  noEmail: '未绑邮箱', verified: '已验证', unverified: '未验证',
  email: '邮箱', created: '创建时间', version: '权限版本',
  grant: '设管理员', revoke: '撤销权限',
  confirmGrant: '确认设置', confirmRevoke: '确认撤销',
  confirmTitle: '更改权限',
  grantEffect: '此账号将设为管理员。\n此账号将能查看部分运行状态。\n仍不能查看他人资料和服务商设置。\n也不能查看账号授权。',
  revokeEffect: '将撤销此账号的管理员权限。\n此账号将不能查看管理员运行状态。\n仍可使用自己的事项和文件。',
  confirmHint: '确认后才会更改权限。\n取消不会提交请求。',
  cancel: '取消', loading: '正在加载账号…', saving: '正在保存并重新读取账号状态…',
  reload: '刷新账号', empty: '暂无可显示账号。',
  loadError: '暂时无法加载账号。请重新加载后再操作。',
  conflict: '权限已有变化，本次未覆盖新权限。\n请刷新账号后重新确认。',
  uncertain: '无法确认结果，请勿重复提交。\n请刷新账号，核对权限后再操作。',
  permission: '当前无法操作，请检查登录状态。\n请确认你是所有者，再刷新账号。',
  refreshFailed: '服务器已确认请求，未读到最新状态。\n请刷新账号，核对当前权限。',
  interrupted: '账号读取中断，请刷新查看最新状态。',
  saved: '权限变更已确认，下方已更新账号状态。',
  unchanged: '服务器确认无需变更。\n下方已更新账号状态。',
  directory: '账号列表', selected: '所选账号',
};
const en = {
  title: 'Accounts and administrator access',
  description: 'Only the owner can view the account directory and grant or revoke administrator access.',
  boundary: 'Administrators can view bounded operational status only. They cannot access other users’ cases or files, provider secrets or settings, account grants, or global telemetry. Each account still accesses only its own records.',
  owner: 'Owner', administrator: 'Administrator', ordinary: 'Ordinary user',
  ownerReason: 'Owner access is fixed and cannot be changed here.',
  bindFirst: 'Ask this account to bind and verify an email in account settings before granting administrator access.',
  unavailable: 'Administrator access cannot currently be granted to this account.',
  noEmail: 'No bound email', verified: 'Email verified', unverified: 'Email not verified',
  email: 'Email', created: 'Created', version: 'Capability version',
  grant: 'Grant administrator access', revoke: 'Revoke administrator access',
  confirmGrant: 'Confirm grant', confirmRevoke: 'Confirm revocation',
  confirmTitle: 'Confirm access change',
  grantEffect: 'This account will be able to view bounded operational status. Other users’ records, provider settings, and account grants remain inaccessible.',
  revokeEffect: 'This account will lose administrator operational-status access and keep access to its own cases and files.',
  confirmHint: 'This change is sent only after confirmation. Cancel sends no request.',
  cancel: 'Cancel', loading: 'Loading accounts…', saving: 'Saving and rereading account status…',
  reload: 'Reload accounts', empty: 'There are no accounts to display.',
  loadError: 'Accounts could not be loaded. Reload before making changes.',
  conflict: 'Account access has changed. This request did not overwrite the newer state. Reload accounts and confirm again.',
  uncertain: 'The change result is uncertain. Do not submit it again. Reload accounts and check current access before making another change.',
  permission: 'This session cannot perform the action. Check your sign-in and owner access, then reload accounts.',
  refreshFailed: 'The server acknowledged the change request, but current account status could not be read. Reload accounts to check the result.',
  interrupted: 'The account request was interrupted. Reload to view current status.',
  saved: 'The access change was acknowledged. The accounts below were freshly reread.',
  unchanged: 'The server confirmed no change was needed. The accounts below were freshly reread.',
  directory: 'Account directory', selected: 'Target account',
};
export const accountAdministrationCopy = lang => lang === 'en' ? en : zh;

const diagnosticsZh = {
  title: '运行状态',
  description: '这里只显示服务功能和当前请求数。\n不含用户资料、账号列表和密钥。\n也不含设置管理和全站运行数据。',
  model: '模型', live: '助手调用', pdf: '读取文档', workbook: '读取表格',
  enabled: '已启用', disabled: '未启用', uptime: '运行时长',
  active: '正在处理', chat: '对话', extraction: '信息提取',
  loading: '正在读取运行状态…', reload: '刷新状态',
  error: '暂时无法读取，请刷新重试。',
};
const diagnosticsEn = {
  title: 'Bounded operational status',
  description: 'Read-only service capabilities and current request counts. No user records, account directory, secrets, settings management, or global telemetry.',
  model: 'Model', live: 'Live model calls', pdf: 'PDF parsing', workbook: 'Workbook parsing',
  enabled: 'Enabled', disabled: 'Disabled', uptime: 'Uptime (seconds)',
  active: 'Active requests', chat: 'Chat', extraction: 'Extraction',
  loading: 'Loading operational status…', reload: 'Refresh operational status',
  error: 'Operational status could not be loaded. Refresh manually to try again.',
};
export const operationalDiagnosticsCopy = lang => lang === 'en' ? diagnosticsEn : diagnosticsZh;
