const zh = {
  title: '账号与管理员权限',
  description: '仅所有者可以查看账号目录和授予或撤销管理员权限。',
  boundary: '管理员仅可查看有限的运行状态，无权查看其他用户的事项或文件、服务商密钥或设置、账号授权或全局遥测。每个账号仍只能访问自己的资料。',
  owner: '所有者', administrator: '管理员', ordinary: '普通用户',
  ownerReason: '所有者权限固定，不能在这里修改。',
  bindFirst: '请此账号先在账号设置中绑定并验证邮箱，再授予管理员权限。',
  unavailable: '此账号目前不能被授予管理员权限。',
  noEmail: '尚未绑定邮箱', verified: '邮箱已验证', unverified: '邮箱未验证',
  email: '邮箱', created: '创建时间', version: '权限版本',
  grant: '授予管理员权限', revoke: '撤销管理员权限',
  confirmGrant: '确认授予管理员权限', confirmRevoke: '确认撤销管理员权限',
  confirmTitle: '确认权限变更',
  grantEffect: '此账号将获得有限运行状态的查看权限。其他用户的资料、服务商设置和账号授权仍不可访问。',
  revokeEffect: '此账号将失去管理员运行状态查看权限，仍可使用自己的事项和文件。',
  confirmHint: '仅在确认后提交本次变更。取消不会发送请求。',
  cancel: '取消', loading: '正在加载账号…', saving: '正在保存并重新读取账号状态…',
  reload: '重新加载账号', empty: '当前没有可显示的账号。',
  loadError: '暂时无法加载账号。请重新加载后再操作。',
  conflict: '账号权限已发生变化。本次变更未覆盖新状态；请重新加载账号后重新确认。',
  uncertain: '无法确认变更结果，请勿重复提交。请重新加载账号，核对最新权限后再操作。',
  permission: '当前会话无法执行此操作。请检查登录和所有者权限，再重新加载账号。',
  refreshFailed: '变更请求已被服务端确认，但最新账号状态未能读取。请重新加载账号后核对。',
  interrupted: '账号读取已中断。请重新加载以查看最新状态。',
  saved: '权限变更已确认；下方显示重新读取的最新账号状态。',
  unchanged: '服务端确认无需变更；下方显示重新读取的最新账号状态。',
  directory: '账号目录', selected: '目标账号',
};
const en = {
  title: 'Accounts and administrator access',
  description: 'Only the owner can view the account directory and grant or revoke administrator access.',
  boundary: 'Administrators can view bounded operational status only. They cannot access other users’ cases or files, provider secrets or settings, account grants, or global telemetry. Each account still accesses only its own records.',
  owner: 'Owner', administrator: 'Administrator', ordinary: 'Ordinary user',
  ownerReason: 'Owner access is fixed and cannot be changed here.',
  bindFirst: 'Ask this account to bind and verify an email in account settings before granting administrator access.',
  unavailable: 'Administrator access cannot currently be granted to this account.',
  noEmail: 'No bound email', verified: 'Email verified', unverified: 'Email not verified',
  email: 'Email', created: 'Created', version: 'Capability version',
  grant: 'Grant administrator access', revoke: 'Revoke administrator access',
  confirmGrant: 'Confirm grant', confirmRevoke: 'Confirm revocation',
  confirmTitle: 'Confirm access change',
  grantEffect: 'This account will be able to view bounded operational status. Other users’ records, provider settings, and account grants remain inaccessible.',
  revokeEffect: 'This account will lose administrator operational-status access and keep access to its own cases and files.',
  confirmHint: 'This change is sent only after confirmation. Cancel sends no request.',
  cancel: 'Cancel', loading: 'Loading accounts…', saving: 'Saving and rereading account status…',
  reload: 'Reload accounts', empty: 'There are no accounts to display.',
  loadError: 'Accounts could not be loaded. Reload before making changes.',
  conflict: 'Account access has changed. This request did not overwrite the newer state. Reload accounts and confirm again.',
  uncertain: 'The change result is uncertain. Do not submit it again. Reload accounts and check current access before making another change.',
  permission: 'This session cannot perform the action. Check your sign-in and owner access, then reload accounts.',
  refreshFailed: 'The server acknowledged the change request, but current account status could not be read. Reload accounts to check the result.',
  interrupted: 'The account request was interrupted. Reload to view current status.',
  saved: 'The access change was acknowledged. The accounts below were freshly reread.',
  unchanged: 'The server confirmed no change was needed. The accounts below were freshly reread.',
  directory: 'Account directory', selected: 'Target account',
};
export const accountAdministrationCopy = lang => lang === 'en' ? en : zh;

const diagnosticsZh = {
  title: '有限运行状态',
  description: '只读服务能力与当前请求数量，不包含用户资料、账号目录、密钥、设置管理或全局遥测。',
  model: '模型', live: '在线模型调用', pdf: 'PDF 解析', workbook: '表格解析',
  enabled: '已启用', disabled: '未启用', uptime: '运行时间（秒）',
  active: '当前活动请求', chat: '对话', extraction: '提取',
  loading: '正在读取运行状态…', reload: '刷新运行状态',
  error: '暂时无法读取运行状态，请手动刷新。',
};
const diagnosticsEn = {
  title: 'Bounded operational status',
  description: 'Read-only service capabilities and current request counts. No user records, account directory, secrets, settings management, or global telemetry.',
  model: 'Model', live: 'Live model calls', pdf: 'PDF parsing', workbook: 'Workbook parsing',
  enabled: 'Enabled', disabled: 'Disabled', uptime: 'Uptime (seconds)',
  active: 'Active requests', chat: 'Chat', extraction: 'Extraction',
  loading: 'Loading operational status…', reload: 'Refresh operational status',
  error: 'Operational status could not be loaded. Refresh manually to try again.',
};
export const operationalDiagnosticsCopy = lang => lang === 'en' ? diagnosticsEn : diagnosticsZh;
